//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Marketing.GestaoVerbas.AuthenticationService {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSAutenticacaoTokenDMZSoap", Namespace="http://tempuri.org/")]
    public partial class WSAutenticacaoTokenDMZ : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback WSAutenticacaoDMZOperationCompleted;
        
        private System.Threading.SendOrPostCallback WSAutenticacaoDMZSemTokenOperationCompleted;
        
        private System.Threading.SendOrPostCallback WSAutenticacaoDMZRetornaGrupoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSAutenticacaoTokenDMZ() {
            this.Url = global::Marketing.GestaoVerbas.Properties.Settings.Default.Marketing_GestaoVerbas_AuthenticationService_WSAutenticacaoTokenDMZ;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event WSAutenticacaoDMZCompletedEventHandler WSAutenticacaoDMZCompleted;
        
        /// <remarks/>
        public event WSAutenticacaoDMZSemTokenCompletedEventHandler WSAutenticacaoDMZSemTokenCompleted;
        
        /// <remarks/>
        public event WSAutenticacaoDMZRetornaGrupoCompletedEventHandler WSAutenticacaoDMZRetornaGrupoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WSAutenticacaoDMZ", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WSAutenticacaoDMZ(string usuario, string senha, string token) {
            object[] results = this.Invoke("WSAutenticacaoDMZ", new object[] {
                        usuario,
                        senha,
                        token});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WSAutenticacaoDMZAsync(string usuario, string senha, string token) {
            this.WSAutenticacaoDMZAsync(usuario, senha, token, null);
        }
        
        /// <remarks/>
        public void WSAutenticacaoDMZAsync(string usuario, string senha, string token, object userState) {
            if ((this.WSAutenticacaoDMZOperationCompleted == null)) {
                this.WSAutenticacaoDMZOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWSAutenticacaoDMZOperationCompleted);
            }
            this.InvokeAsync("WSAutenticacaoDMZ", new object[] {
                        usuario,
                        senha,
                        token}, this.WSAutenticacaoDMZOperationCompleted, userState);
        }
        
        private void OnWSAutenticacaoDMZOperationCompleted(object arg) {
            if ((this.WSAutenticacaoDMZCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WSAutenticacaoDMZCompleted(this, new WSAutenticacaoDMZCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WSAutenticacaoDMZSemToken", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WSAutenticacaoDMZSemToken(string usuario, string senha) {
            object[] results = this.Invoke("WSAutenticacaoDMZSemToken", new object[] {
                        usuario,
                        senha});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WSAutenticacaoDMZSemTokenAsync(string usuario, string senha) {
            this.WSAutenticacaoDMZSemTokenAsync(usuario, senha, null);
        }
        
        /// <remarks/>
        public void WSAutenticacaoDMZSemTokenAsync(string usuario, string senha, object userState) {
            if ((this.WSAutenticacaoDMZSemTokenOperationCompleted == null)) {
                this.WSAutenticacaoDMZSemTokenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWSAutenticacaoDMZSemTokenOperationCompleted);
            }
            this.InvokeAsync("WSAutenticacaoDMZSemToken", new object[] {
                        usuario,
                        senha}, this.WSAutenticacaoDMZSemTokenOperationCompleted, userState);
        }
        
        private void OnWSAutenticacaoDMZSemTokenOperationCompleted(object arg) {
            if ((this.WSAutenticacaoDMZSemTokenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WSAutenticacaoDMZSemTokenCompleted(this, new WSAutenticacaoDMZSemTokenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WSAutenticacaoDMZRetornaGrupo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WSAutenticacaoDMZRetornaGrupo(string usuario, string senha) {
            object[] results = this.Invoke("WSAutenticacaoDMZRetornaGrupo", new object[] {
                        usuario,
                        senha});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WSAutenticacaoDMZRetornaGrupoAsync(string usuario, string senha) {
            this.WSAutenticacaoDMZRetornaGrupoAsync(usuario, senha, null);
        }
        
        /// <remarks/>
        public void WSAutenticacaoDMZRetornaGrupoAsync(string usuario, string senha, object userState) {
            if ((this.WSAutenticacaoDMZRetornaGrupoOperationCompleted == null)) {
                this.WSAutenticacaoDMZRetornaGrupoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWSAutenticacaoDMZRetornaGrupoOperationCompleted);
            }
            this.InvokeAsync("WSAutenticacaoDMZRetornaGrupo", new object[] {
                        usuario,
                        senha}, this.WSAutenticacaoDMZRetornaGrupoOperationCompleted, userState);
        }
        
        private void OnWSAutenticacaoDMZRetornaGrupoOperationCompleted(object arg) {
            if ((this.WSAutenticacaoDMZRetornaGrupoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WSAutenticacaoDMZRetornaGrupoCompleted(this, new WSAutenticacaoDMZRetornaGrupoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void WSAutenticacaoDMZCompletedEventHandler(object sender, WSAutenticacaoDMZCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WSAutenticacaoDMZCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WSAutenticacaoDMZCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void WSAutenticacaoDMZSemTokenCompletedEventHandler(object sender, WSAutenticacaoDMZSemTokenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WSAutenticacaoDMZSemTokenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WSAutenticacaoDMZSemTokenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void WSAutenticacaoDMZRetornaGrupoCompletedEventHandler(object sender, WSAutenticacaoDMZRetornaGrupoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WSAutenticacaoDMZRetornaGrupoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WSAutenticacaoDMZRetornaGrupoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591