var TREE_ITEMS = [
	['Menu', '',
		['GAC', '',
			['Extra Acordo', '',
				['Extra Acordo', 'AcordoListar.aspx'],
				['Carimbo', 'VerbaCarimbo.aspx']
			],			
			['Baixa Acordo', 'BaixaAcordo/BaixaAcordo.aspx'],			
			['Cancelar Perda Ctt.', 'CancelarPerdaAcordo.aspx'],
			['Recebimento Acordos', '',
				['Cadastrar Cheque', 'ChequeListar.aspx'],
				['Cadastrar OP', 'OPListar.aspx'],
				['Recebimentos', 'Recebimento.aspx'],
				['Opera&ccedil;&otilde;es OP', 'OperacoesOP.aspx'],
				['Hist&oacute;rico Baixa OP', 'RelatorioHistoricoBaixaOP.aspx']
			],
			['Par&acirc;metros', '',
				['Empenho', 'EmpenhoListar.aspx'],
				['Forma de Pagto', 'FormaPagamentoListar.aspx'],
				['Tipo lan&ccedil;amento', 'TipoLancamentoListar.aspx'],
				['Tipo Ped./Cl&#225;usula', 'TipoPedidoCompraListar.aspx'],
				['Tipo Ped./Empenho', 'RelacaoEmpenhoTipoPedidoCompraListar.aspx'],
				['Banco', 'BancoListar.aspx'],
				['Ag&ecirc;ncia', 'AgenciaListar.aspx'],			
				['Gerais', 'GeraisListar.aspx'],
				['Fornecedor MMM', 'ParametroFornecedorMMM.aspx'],				
				['Rel.Usu&#225;rio C&#233;lula', 'RelacaoUsuarioCelulaListar.aspx'],								
				['Inibir DED Autom&aacute;tico', 'InibirDedAutomatico.aspx'],
				['Tipo Objetivo Verba', 'TipoObjetivoVerbaListar.aspx'],
				['Transf.Verbas', '',
					['Tipo', 'TipoTransferenciaVerbaListar.aspx'],
					['Rel.Usu&#225;rio', 'RelacaoUsuarioTransferenciaVerbaListar.aspx'],
					['Relacionamento', 'RelacionamentoTransferenciaVerbaListar.aspx']
				],
				['Verbas Marketing', '',
					['Tipo Grupo Mkt', 'VerbasMarketing/TipoGrupoMktListar.aspx'],
					['Rel. Grupos Mkt', 'VerbasMarketing/RelacaoGrupoMktListar.aspx'],
					['Mkt. Exa. Acordo', 'VerbasMarketing/MktExtraAcordoListar.aspx']
				]
			]			
		],
		['Conta Corrente Fornecedor', '',
			['Extrato', '',
				['Fornecedor', 'Extrato.aspx'],
				['Fornecedor GAC', 'ExtratoFornecedor.aspx']			
			],
			['Lan&ccedil;amento', 'LancamentoListar.aspx'],
			['Transfer&ecirc;ncia', '',
				['GAC', 'TransferenciaGac.aspx'],
				['Compras', 'Transferencia.aspx'],
				['Fluxo', 'EmpenhosDoFornecedor/EmpenhoFornecedorListar.aspx']
			],
		],	
		['Acordo Fornecimento', '',
			['Contrato', 'ContratoListar.aspx'],
			['Apura&ccedil;&atilde;o', 'Apuracao.aspx'],
			['Altera Forma Pgto', 'AlteraFormaPagamento.aspx'],
			['Troca T&iacute;tulo <span class=3DSpellE>Pagto', 'TrocaTituloPagamento.aspx'],
			['Altera Valor Efetivo', 'AlteraValorEfetivo.aspx'],
			['Par&acirc;metros', '',
				['Tipo Abrang&ecirc;ncia', 'TipoAbrangenciaListar.aspx'],
				['Tipo Base C&#225;lculo', 'TipoBaseCalculoListar.aspx'],
				['Tipo Encargo Fin.', 'TipoEncargoFinanceiroListar.aspx'],
				['Tipo Forma Pagto', 'TipoFormaPagamentoListar.aspx'],
				['Tipo Fornecedor', 'TipoFornecedorListar.aspx'],
				['Tipo Pgto', 'TipoPagamentoListar.aspx'],
				['Tipo Relacion.', 'TipoRelacionamentoListar.aspx'],			
				['Tipo Servi&ccedilo', 'TipoServicoListar.aspx'],
				['Unidade Pagadora', 'UnidadePagamentoListar.aspx'],
				['Prog. Incentivo', 'Incentivo/ProgramaIncentivoListar.aspx'],
				['Prog. X Fornecedor', 'Incentivo/RelacaoProgramaIncentivoListar.aspx']
			]			
		],
		['Relat&oacute;rios', '',
			['Contas a Receber', 'RelatorioContasAReceber.aspx'],
			['Acordo Fornecimento', 'RelatorioAcordoFornecimento.aspx'],
			['Hist&oacute;rico do Acordo', 'RelatorioHistoricoAcordo.aspx'],
			['Confer. A&ccedil;&atilde;o T&aacute;tica', 'RelatorioConferenciaAcaoTatica.aspx'],
			['Acordo s/NF p/Deduction', 'RelatorioAcordoSemNfDeduction.aspx'],
			['Acordo p/Deduction', 'RelatorioAcordoParaDeduction.aspx'],
			['Contrato', 'RelatorioContrato.aspx'],
			['Recup/Preven&#231;&#227;o Perdas', 'RelatorioComparativoValores.aspx'],
			['Acordos Canc/Perdas', 'RelatorioAcordosCanceladosPerdas.aspx'],
			['Previs&#227;o Apura&#231;&#227;o', 'RelatorioPrevisaoApuracao.aspx'],
			['Valores Contabilizados Carimbos', 'ValoresContabilizadosCarimbos.aspx'],		
		],
		['Cancelamento Acordo', 'FluxoDeCancelamentoDeAcordos/FluxoDeCancelamentoDeAcordosListar.aspx'],	
		['Sobre', 'Sobre.aspx'],	
	]
];