'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2500
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Runtime.Serialization
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2500.
'
Namespace wsUsuario
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="UsuarioSoap", [Namespace]:="http://tempuri.org/Martins.Web.Services.Usuario/Usuario")>  _
    Public Class Usuario
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Dim urlSetting As String = System.Configuration.ConfigurationSettings.AppSettings("Martins.Web.UI.AcoesComerciais.wsUsuario.Usuario")
            If (Not (urlSetting) Is Nothing) Then
                Me.Url = String.Concat(urlSetting, "")
            Else
                Me.Url = "http://localhost/Martins.Web.Services.Usuario/Usuario.asmx"
            End If
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Martins.Web.Services.Usuario/Usuario/ObterUsuario", RequestNamespace:="http://tempuri.org/Martins.Web.Services.Usuario/Usuario", ResponseNamespace:="http://tempuri.org/Martins.Web.Services.Usuario/Usuario", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ObterUsuario(ByVal codigoUsuario As Decimal) As DataSetUsuario
            Dim results() As Object = Me.Invoke("ObterUsuario", New Object() {codigoUsuario})
            Return CType(results(0),DataSetUsuario)
        End Function
        
        '<remarks/>
        Public Function BeginObterUsuario(ByVal codigoUsuario As Decimal, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ObterUsuario", New Object() {codigoUsuario}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndObterUsuario(ByVal asyncResult As System.IAsyncResult) As DataSetUsuario
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),DataSetUsuario)
        End Function
    End Class
    
    <Serializable(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Diagnostics.DebuggerStepThrough(),  _
     System.ComponentModel.ToolboxItem(true)>  _
    Public Class DataSetUsuario
        Inherits DataSet
        
        Private tableUsuario As UsuarioDataTable
        
        Public Sub New()
            MyBase.New
            Me.InitClass
            Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
            AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
            AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
        End Sub
        
        Protected Sub New(ByVal info As SerializationInfo, ByVal context As StreamingContext)
            MyBase.New
            Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(System.String)),String)
            If (Not (strSchema) Is Nothing) Then
                Dim ds As DataSet = New DataSet
                ds.ReadXmlSchema(New XmlTextReader(New System.IO.StringReader(strSchema)))
                If (Not (ds.Tables("Usuario")) Is Nothing) Then
                    Me.Tables.Add(New UsuarioDataTable(ds.Tables("Usuario")))
                End If
                Me.DataSetName = ds.DataSetName
                Me.Prefix = ds.Prefix
                Me.Namespace = ds.Namespace
                Me.Locale = ds.Locale
                Me.CaseSensitive = ds.CaseSensitive
                Me.EnforceConstraints = ds.EnforceConstraints
                Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
                Me.InitVars
            Else
                Me.InitClass
            End If
            Me.GetSerializationData(info, context)
            Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
            AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
            AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
        End Sub
        
        <System.ComponentModel.Browsable(false),  _
         System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
        Public ReadOnly Property Usuario As UsuarioDataTable
            Get
                Return Me.tableUsuario
            End Get
        End Property
        
        Public Overrides Function Clone() As DataSet
            Dim cln As DataSetUsuario = CType(MyBase.Clone,DataSetUsuario)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function ShouldSerializeTables() As Boolean
            Return false
        End Function
        
        Protected Overrides Function ShouldSerializeRelations() As Boolean
            Return false
        End Function
        
        Protected Overrides Sub ReadXmlSerializable(ByVal reader As XmlReader)
            Me.Reset
            Dim ds As DataSet = New DataSet
            ds.ReadXml(reader)
            If (Not (ds.Tables("Usuario")) Is Nothing) Then
                Me.Tables.Add(New UsuarioDataTable(ds.Tables("Usuario")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        End Sub
        
        Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
            Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
            Me.WriteXmlSchema(New XmlTextWriter(stream, Nothing))
            stream.Position = 0
            Return System.Xml.Schema.XmlSchema.Read(New XmlTextReader(stream), Nothing)
        End Function
        
        Friend Sub InitVars()
            Me.tableUsuario = CType(Me.Tables("Usuario"),UsuarioDataTable)
            If (Not (Me.tableUsuario) Is Nothing) Then
                Me.tableUsuario.InitVars
            End If
        End Sub
        
        Private Sub InitClass()
            Me.DataSetName = "DataSetUsuario"
            Me.Prefix = ""
            Me.Namespace = "http://tempuri.org/DataSetUsuario.xsd"
            Me.Locale = New System.Globalization.CultureInfo("en-US")
            Me.CaseSensitive = false
            Me.EnforceConstraints = true
            Me.tableUsuario = New UsuarioDataTable
            Me.Tables.Add(Me.tableUsuario)
        End Sub
        
        Private Function ShouldSerializeUsuario() As Boolean
            Return false
        End Function
        
        Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
            If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
                Me.InitVars
            End If
        End Sub
        
        Public Delegate Sub UsuarioRowChangeEventHandler(ByVal sender As Object, ByVal e As UsuarioRowChangeEvent)
        
        <System.Diagnostics.DebuggerStepThrough()>  _
        Public Class UsuarioDataTable
            Inherits DataTable
            Implements System.Collections.IEnumerable
            
            Private columnNOMUSRARZ As DataColumn
            
            Private columnCODFNC As DataColumn
            
            Private columnCODCLI As DataColumn
            
            Private columnCODFRN As DataColumn
            
            Private columnCODSUP As DataColumn
            
            Private columnCODGER As DataColumn
            
            Private columnCODREP As DataColumn
            
            Private columnCODEMPTRP As DataColumn
            
            Private columnCODEMP As DataColumn
            
            Friend Sub New()
                MyBase.New("Usuario")
                Me.InitClass
            End Sub
            
            Friend Sub New(ByVal table As DataTable)
                MyBase.New(table.TableName)
                If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                    Me.CaseSensitive = table.CaseSensitive
                End If
                If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                    Me.Locale = table.Locale
                End If
                If (table.Namespace <> table.DataSet.Namespace) Then
                    Me.Namespace = table.Namespace
                End If
                Me.Prefix = table.Prefix
                Me.MinimumCapacity = table.MinimumCapacity
                Me.DisplayExpression = table.DisplayExpression
            End Sub
            
            <System.ComponentModel.Browsable(false)>  _
            Public ReadOnly Property Count As Integer
                Get
                    Return Me.Rows.Count
                End Get
            End Property
            
            Friend ReadOnly Property NOMUSRARZColumn As DataColumn
                Get
                    Return Me.columnNOMUSRARZ
                End Get
            End Property
            
            Friend ReadOnly Property CODFNCColumn As DataColumn
                Get
                    Return Me.columnCODFNC
                End Get
            End Property
            
            Friend ReadOnly Property CODCLIColumn As DataColumn
                Get
                    Return Me.columnCODCLI
                End Get
            End Property
            
            Friend ReadOnly Property CODFRNColumn As DataColumn
                Get
                    Return Me.columnCODFRN
                End Get
            End Property
            
            Friend ReadOnly Property CODSUPColumn As DataColumn
                Get
                    Return Me.columnCODSUP
                End Get
            End Property
            
            Friend ReadOnly Property CODGERColumn As DataColumn
                Get
                    Return Me.columnCODGER
                End Get
            End Property
            
            Friend ReadOnly Property CODREPColumn As DataColumn
                Get
                    Return Me.columnCODREP
                End Get
            End Property
            
            Friend ReadOnly Property CODEMPTRPColumn As DataColumn
                Get
                    Return Me.columnCODEMPTRP
                End Get
            End Property
            
            Friend ReadOnly Property CODEMPColumn As DataColumn
                Get
                    Return Me.columnCODEMP
                End Get
            End Property
            
            Public Default ReadOnly Property Item(ByVal index As Integer) As UsuarioRow
                Get
                    Return CType(Me.Rows(index),UsuarioRow)
                End Get
            End Property
            
            Public Event UsuarioRowChanged As UsuarioRowChangeEventHandler
            
            Public Event UsuarioRowChanging As UsuarioRowChangeEventHandler
            
            Public Event UsuarioRowDeleted As UsuarioRowChangeEventHandler
            
            Public Event UsuarioRowDeleting As UsuarioRowChangeEventHandler
            
            Public Overloads Sub AddUsuarioRow(ByVal row As UsuarioRow)
                Me.Rows.Add(row)
            End Sub
            
            Public Overloads Function AddUsuarioRow(ByVal NOMUSRARZ As String, ByVal CODFNC As Decimal, ByVal CODCLI As Decimal, ByVal CODFRN As Decimal, ByVal CODSUP As Decimal, ByVal CODGER As Decimal, ByVal CODREP As Decimal, ByVal CODEMPTRP As Decimal, ByVal CODEMP As Decimal) As UsuarioRow
                Dim rowUsuarioRow As UsuarioRow = CType(Me.NewRow,UsuarioRow)
                rowUsuarioRow.ItemArray = New Object() {NOMUSRARZ, CODFNC, CODCLI, CODFRN, CODSUP, CODGER, CODREP, CODEMPTRP, CODEMP}
                Me.Rows.Add(rowUsuarioRow)
                Return rowUsuarioRow
            End Function
            
            Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
                Return Me.Rows.GetEnumerator
            End Function
            
            Public Overrides Function Clone() As DataTable
                Dim cln As UsuarioDataTable = CType(MyBase.Clone,UsuarioDataTable)
                cln.InitVars
                Return cln
            End Function
            
            Protected Overrides Function CreateInstance() As DataTable
                Return New UsuarioDataTable
            End Function
            
            Friend Sub InitVars()
                Me.columnNOMUSRARZ = Me.Columns("NOMUSRARZ")
                Me.columnCODFNC = Me.Columns("CODFNC")
                Me.columnCODCLI = Me.Columns("CODCLI")
                Me.columnCODFRN = Me.Columns("CODFRN")
                Me.columnCODSUP = Me.Columns("CODSUP")
                Me.columnCODGER = Me.Columns("CODGER")
                Me.columnCODREP = Me.Columns("CODREP")
                Me.columnCODEMPTRP = Me.Columns("CODEMPTRP")
                Me.columnCODEMP = Me.Columns("CODEMP")
            End Sub
            
            Private Sub InitClass()
                Me.columnNOMUSRARZ = New DataColumn("NOMUSRARZ", GetType(System.String), Nothing, System.Data.MappingType.Element)
                Me.Columns.Add(Me.columnNOMUSRARZ)
                Me.columnCODFNC = New DataColumn("CODFNC", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
                Me.Columns.Add(Me.columnCODFNC)
                Me.columnCODCLI = New DataColumn("CODCLI", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
                Me.Columns.Add(Me.columnCODCLI)
                Me.columnCODFRN = New DataColumn("CODFRN", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
                Me.Columns.Add(Me.columnCODFRN)
                Me.columnCODSUP = New DataColumn("CODSUP", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
                Me.Columns.Add(Me.columnCODSUP)
                Me.columnCODGER = New DataColumn("CODGER", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
                Me.Columns.Add(Me.columnCODGER)
                Me.columnCODREP = New DataColumn("CODREP", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
                Me.Columns.Add(Me.columnCODREP)
                Me.columnCODEMPTRP = New DataColumn("CODEMPTRP", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
                Me.Columns.Add(Me.columnCODEMPTRP)
                Me.columnCODEMP = New DataColumn("CODEMP", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
                Me.Columns.Add(Me.columnCODEMP)
            End Sub
            
            Public Function NewUsuarioRow() As UsuarioRow
                Return CType(Me.NewRow,UsuarioRow)
            End Function
            
            Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
                Return New UsuarioRow(builder)
            End Function
            
            Protected Overrides Function GetRowType() As System.Type
                Return GetType(UsuarioRow)
            End Function
            
            Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
                MyBase.OnRowChanged(e)
                If (Not (Me.UsuarioRowChangedEvent) Is Nothing) Then
                    RaiseEvent UsuarioRowChanged(Me, New UsuarioRowChangeEvent(CType(e.Row,UsuarioRow), e.Action))
                End If
            End Sub
            
            Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
                MyBase.OnRowChanging(e)
                If (Not (Me.UsuarioRowChangingEvent) Is Nothing) Then
                    RaiseEvent UsuarioRowChanging(Me, New UsuarioRowChangeEvent(CType(e.Row,UsuarioRow), e.Action))
                End If
            End Sub
            
            Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
                MyBase.OnRowDeleted(e)
                If (Not (Me.UsuarioRowDeletedEvent) Is Nothing) Then
                    RaiseEvent UsuarioRowDeleted(Me, New UsuarioRowChangeEvent(CType(e.Row,UsuarioRow), e.Action))
                End If
            End Sub
            
            Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
                MyBase.OnRowDeleting(e)
                If (Not (Me.UsuarioRowDeletingEvent) Is Nothing) Then
                    RaiseEvent UsuarioRowDeleting(Me, New UsuarioRowChangeEvent(CType(e.Row,UsuarioRow), e.Action))
                End If
            End Sub
            
            Public Sub RemoveUsuarioRow(ByVal row As UsuarioRow)
                Me.Rows.Remove(row)
            End Sub
        End Class
        
        <System.Diagnostics.DebuggerStepThrough()>  _
        Public Class UsuarioRow
            Inherits DataRow
            
            Private tableUsuario As UsuarioDataTable
            
            Friend Sub New(ByVal rb As DataRowBuilder)
                MyBase.New(rb)
                Me.tableUsuario = CType(Me.Table,UsuarioDataTable)
            End Sub
            
            Public Property NOMUSRARZ As String
                Get
                    Try 
                        Return CType(Me(Me.tableUsuario.NOMUSRARZColumn),String)
                    Catch e As InvalidCastException
                        Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                    End Try
                End Get
                Set
                    Me(Me.tableUsuario.NOMUSRARZColumn) = value
                End Set
            End Property
            
            Public Property CODFNC As Decimal
                Get
                    Try 
                        Return CType(Me(Me.tableUsuario.CODFNCColumn),Decimal)
                    Catch e As InvalidCastException
                        Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                    End Try
                End Get
                Set
                    Me(Me.tableUsuario.CODFNCColumn) = value
                End Set
            End Property
            
            Public Property CODCLI As Decimal
                Get
                    Try 
                        Return CType(Me(Me.tableUsuario.CODCLIColumn),Decimal)
                    Catch e As InvalidCastException
                        Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                    End Try
                End Get
                Set
                    Me(Me.tableUsuario.CODCLIColumn) = value
                End Set
            End Property
            
            Public Property CODFRN As Decimal
                Get
                    Try 
                        Return CType(Me(Me.tableUsuario.CODFRNColumn),Decimal)
                    Catch e As InvalidCastException
                        Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                    End Try
                End Get
                Set
                    Me(Me.tableUsuario.CODFRNColumn) = value
                End Set
            End Property
            
            Public Property CODSUP As Decimal
                Get
                    Try 
                        Return CType(Me(Me.tableUsuario.CODSUPColumn),Decimal)
                    Catch e As InvalidCastException
                        Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                    End Try
                End Get
                Set
                    Me(Me.tableUsuario.CODSUPColumn) = value
                End Set
            End Property
            
            Public Property CODGER As Decimal
                Get
                    Try 
                        Return CType(Me(Me.tableUsuario.CODGERColumn),Decimal)
                    Catch e As InvalidCastException
                        Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                    End Try
                End Get
                Set
                    Me(Me.tableUsuario.CODGERColumn) = value
                End Set
            End Property
            
            Public Property CODREP As Decimal
                Get
                    Try 
                        Return CType(Me(Me.tableUsuario.CODREPColumn),Decimal)
                    Catch e As InvalidCastException
                        Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                    End Try
                End Get
                Set
                    Me(Me.tableUsuario.CODREPColumn) = value
                End Set
            End Property
            
            Public Property CODEMPTRP As Decimal
                Get
                    Try 
                        Return CType(Me(Me.tableUsuario.CODEMPTRPColumn),Decimal)
                    Catch e As InvalidCastException
                        Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                    End Try
                End Get
                Set
                    Me(Me.tableUsuario.CODEMPTRPColumn) = value
                End Set
            End Property
            
            Public Property CODEMP As Decimal
                Get
                    Try 
                        Return CType(Me(Me.tableUsuario.CODEMPColumn),Decimal)
                    Catch e As InvalidCastException
                        Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                    End Try
                End Get
                Set
                    Me(Me.tableUsuario.CODEMPColumn) = value
                End Set
            End Property
            
            Public Function IsNOMUSRARZNull() As Boolean
                Return Me.IsNull(Me.tableUsuario.NOMUSRARZColumn)
            End Function
            
            Public Sub SetNOMUSRARZNull()
                Me(Me.tableUsuario.NOMUSRARZColumn) = System.Convert.DBNull
            End Sub
            
            Public Function IsCODFNCNull() As Boolean
                Return Me.IsNull(Me.tableUsuario.CODFNCColumn)
            End Function
            
            Public Sub SetCODFNCNull()
                Me(Me.tableUsuario.CODFNCColumn) = System.Convert.DBNull
            End Sub
            
            Public Function IsCODCLINull() As Boolean
                Return Me.IsNull(Me.tableUsuario.CODCLIColumn)
            End Function
            
            Public Sub SetCODCLINull()
                Me(Me.tableUsuario.CODCLIColumn) = System.Convert.DBNull
            End Sub
            
            Public Function IsCODFRNNull() As Boolean
                Return Me.IsNull(Me.tableUsuario.CODFRNColumn)
            End Function
            
            Public Sub SetCODFRNNull()
                Me(Me.tableUsuario.CODFRNColumn) = System.Convert.DBNull
            End Sub
            
            Public Function IsCODSUPNull() As Boolean
                Return Me.IsNull(Me.tableUsuario.CODSUPColumn)
            End Function
            
            Public Sub SetCODSUPNull()
                Me(Me.tableUsuario.CODSUPColumn) = System.Convert.DBNull
            End Sub
            
            Public Function IsCODGERNull() As Boolean
                Return Me.IsNull(Me.tableUsuario.CODGERColumn)
            End Function
            
            Public Sub SetCODGERNull()
                Me(Me.tableUsuario.CODGERColumn) = System.Convert.DBNull
            End Sub
            
            Public Function IsCODREPNull() As Boolean
                Return Me.IsNull(Me.tableUsuario.CODREPColumn)
            End Function
            
            Public Sub SetCODREPNull()
                Me(Me.tableUsuario.CODREPColumn) = System.Convert.DBNull
            End Sub
            
            Public Function IsCODEMPTRPNull() As Boolean
                Return Me.IsNull(Me.tableUsuario.CODEMPTRPColumn)
            End Function
            
            Public Sub SetCODEMPTRPNull()
                Me(Me.tableUsuario.CODEMPTRPColumn) = System.Convert.DBNull
            End Sub
            
            Public Function IsCODEMPNull() As Boolean
                Return Me.IsNull(Me.tableUsuario.CODEMPColumn)
            End Function
            
            Public Sub SetCODEMPNull()
                Me(Me.tableUsuario.CODEMPColumn) = System.Convert.DBNull
            End Sub
        End Class
        
        <System.Diagnostics.DebuggerStepThrough()>  _
        Public Class UsuarioRowChangeEvent
            Inherits EventArgs
            
            Private eventRow As UsuarioRow
            
            Private eventAction As DataRowAction
            
            Public Sub New(ByVal row As UsuarioRow, ByVal action As DataRowAction)
                MyBase.New
                Me.eventRow = row
                Me.eventAction = action
            End Sub
            
            Public ReadOnly Property Row As UsuarioRow
                Get
                    Return Me.eventRow
                End Get
            End Property
            
            Public ReadOnly Property Action As DataRowAction
                Get
                    Return Me.eventAction
                End Get
            End Property
        End Class
    End Class
End Namespace
