'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2407
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Runtime.Serialization
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2407.
'
Namespace wsCobrancaBancaria
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="CobrancaBancariaSoap", [Namespace]:="http://tempuri.org/Martins.Web.Services.Administracao.CobrancaBancaria/Administra"& _ 
"cao.CobrancaBancaria")>  _
    Public Class CobrancaBancaria
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Dim urlSetting As String = System.Configuration.ConfigurationSettings.AppSettings("Martins.Web.UI.AcoesComerciais.wsCobrancaBancaria.CobrancaBancaria")
            If (Not (urlSetting) Is Nothing) Then
                Me.Url = String.Concat(urlSetting, "")
            Else
                Me.Url = "http://localhost/Martins.Web.Services.Administracao.CobrancaBancaria/CobrancaBanc"& _ 
"aria.asmx"
            End If
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Martins.Web.Services.Administracao.CobrancaBancaria/Administra"& _ 
"cao.CobrancaBancaria/ObterBanco", RequestNamespace:="http://tempuri.org/Martins.Web.Services.Administracao.CobrancaBancaria/Administra"& _ 
"cao.CobrancaBancaria", ResponseNamespace:="http://tempuri.org/Martins.Web.Services.Administracao.CobrancaBancaria/Administra"& _ 
"cao.CobrancaBancaria", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ObterBanco(ByVal CODBCO As Decimal) As DatasetBanco
            Dim results() As Object = Me.Invoke("ObterBanco", New Object() {CODBCO})
            Return CType(results(0),DatasetBanco)
        End Function
        
        '<remarks/>
        Public Function BeginObterBanco(ByVal CODBCO As Decimal, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ObterBanco", New Object() {CODBCO}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndObterBanco(ByVal asyncResult As System.IAsyncResult) As DatasetBanco
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),DatasetBanco)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Martins.Web.Services.Administracao.CobrancaBancaria/Administra"& _ 
"cao.CobrancaBancaria/ObterBancos", RequestNamespace:="http://tempuri.org/Martins.Web.Services.Administracao.CobrancaBancaria/Administra"& _ 
"cao.CobrancaBancaria", ResponseNamespace:="http://tempuri.org/Martins.Web.Services.Administracao.CobrancaBancaria/Administra"& _ 
"cao.CobrancaBancaria", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ObterBancos(ByVal CODCID As Decimal, ByVal ENDBCO As String, ByVal INDBCOCVNFNDIVT As Decimal, ByVal NOMBCO As String, ByVal TIPSITBCO As Decimal) As DatasetBanco
            Dim results() As Object = Me.Invoke("ObterBancos", New Object() {CODCID, ENDBCO, INDBCOCVNFNDIVT, NOMBCO, TIPSITBCO})
            Return CType(results(0),DatasetBanco)
        End Function
        
        '<remarks/>
        Public Function BeginObterBancos(ByVal CODCID As Decimal, ByVal ENDBCO As String, ByVal INDBCOCVNFNDIVT As Decimal, ByVal NOMBCO As String, ByVal TIPSITBCO As Decimal, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ObterBancos", New Object() {CODCID, ENDBCO, INDBCOCVNFNDIVT, NOMBCO, TIPSITBCO}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndObterBancos(ByVal asyncResult As System.IAsyncResult) As DatasetBanco
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),DatasetBanco)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Martins.Web.Services.Administracao.CobrancaBancaria/Administra"& _ 
"cao.CobrancaBancaria/ObterAgencia", RequestNamespace:="http://tempuri.org/Martins.Web.Services.Administracao.CobrancaBancaria/Administra"& _ 
"cao.CobrancaBancaria", ResponseNamespace:="http://tempuri.org/Martins.Web.Services.Administracao.CobrancaBancaria/Administra"& _ 
"cao.CobrancaBancaria", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ObterAgencia(ByVal CODAGEBCO As Decimal, ByVal CODBCO As Decimal) As DatasetAgencia
            Dim results() As Object = Me.Invoke("ObterAgencia", New Object() {CODAGEBCO, CODBCO})
            Return CType(results(0),DatasetAgencia)
        End Function
        
        '<remarks/>
        Public Function BeginObterAgencia(ByVal CODAGEBCO As Decimal, ByVal CODBCO As Decimal, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ObterAgencia", New Object() {CODAGEBCO, CODBCO}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndObterAgencia(ByVal asyncResult As System.IAsyncResult) As DatasetAgencia
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),DatasetAgencia)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Martins.Web.Services.Administracao.CobrancaBancaria/Administra"& _ 
"cao.CobrancaBancaria/ObterAgencias", RequestNamespace:="http://tempuri.org/Martins.Web.Services.Administracao.CobrancaBancaria/Administra"& _ 
"cao.CobrancaBancaria", ResponseNamespace:="http://tempuri.org/Martins.Web.Services.Administracao.CobrancaBancaria/Administra"& _ 
"cao.CobrancaBancaria", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ObterAgencias(ByVal CODAGEBCO As Decimal, ByVal CODBCO As Decimal, ByVal CODCEPAGEBCO As Decimal, ByVal CODCIDAGEBCO As Decimal, ByVal FLGAGECDTCOBBCO As String, ByVal NOMAGEBCO As String) As DatasetAgencia
            Dim results() As Object = Me.Invoke("ObterAgencias", New Object() {CODAGEBCO, CODBCO, CODCEPAGEBCO, CODCIDAGEBCO, FLGAGECDTCOBBCO, NOMAGEBCO})
            Return CType(results(0),DatasetAgencia)
        End Function
        
        '<remarks/>
        Public Function BeginObterAgencias(ByVal CODAGEBCO As Decimal, ByVal CODBCO As Decimal, ByVal CODCEPAGEBCO As Decimal, ByVal CODCIDAGEBCO As Decimal, ByVal FLGAGECDTCOBBCO As String, ByVal NOMAGEBCO As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ObterAgencias", New Object() {CODAGEBCO, CODBCO, CODCEPAGEBCO, CODCIDAGEBCO, FLGAGECDTCOBBCO, NOMAGEBCO}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndObterAgencias(ByVal asyncResult As System.IAsyncResult) As DatasetAgencia
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),DatasetAgencia)
        End Function
    End Class
    
    <Serializable(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Diagnostics.DebuggerStepThrough(),  _
     System.ComponentModel.ToolboxItem(true)>  _
    Public Class DatasetAgencia
        Inherits DataSet
        
        Private tableT0104413 As T0104413DataTable
        
        Public Sub New()
            MyBase.New
            Me.InitClass
            Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
            AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
            AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
        End Sub
        
        Protected Sub New(ByVal info As SerializationInfo, ByVal context As StreamingContext)
            MyBase.New
            Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(System.String)),String)
            If (Not (strSchema) Is Nothing) Then
                Dim ds As DataSet = New DataSet
                ds.ReadXmlSchema(New XmlTextReader(New System.IO.StringReader(strSchema)))
                If (Not (ds.Tables("T0104413")) Is Nothing) Then
                    Me.Tables.Add(New T0104413DataTable(ds.Tables("T0104413")))
                End If
                Me.DataSetName = ds.DataSetName
                Me.Prefix = ds.Prefix
                Me.Namespace = ds.Namespace
                Me.Locale = ds.Locale
                Me.CaseSensitive = ds.CaseSensitive
                Me.EnforceConstraints = ds.EnforceConstraints
                Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
                Me.InitVars
            Else
                Me.InitClass
            End If
            Me.GetSerializationData(info, context)
            Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
            AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
            AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
        End Sub
        
        <System.ComponentModel.Browsable(false),  _
         System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
        Public ReadOnly Property T0104413 As T0104413DataTable
            Get
                Return Me.tableT0104413
            End Get
        End Property
        
        Public Overrides Function Clone() As DataSet
            Dim cln As DatasetAgencia = CType(MyBase.Clone,DatasetAgencia)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function ShouldSerializeTables() As Boolean
            Return false
        End Function
        
        Protected Overrides Function ShouldSerializeRelations() As Boolean
            Return false
        End Function
        
        Protected Overrides Sub ReadXmlSerializable(ByVal reader As XmlReader)
            Me.Reset
            Dim ds As DataSet = New DataSet
            ds.ReadXml(reader)
            If (Not (ds.Tables("T0104413")) Is Nothing) Then
                Me.Tables.Add(New T0104413DataTable(ds.Tables("T0104413")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        End Sub
        
        Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
            Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
            Me.WriteXmlSchema(New XmlTextWriter(stream, Nothing))
            stream.Position = 0
            Return System.Xml.Schema.XmlSchema.Read(New XmlTextReader(stream), Nothing)
        End Function
        
        Friend Sub InitVars()
            Me.tableT0104413 = CType(Me.Tables("T0104413"),T0104413DataTable)
            If (Not (Me.tableT0104413) Is Nothing) Then
                Me.tableT0104413.InitVars
            End If
        End Sub
        
        Private Sub InitClass()
            Me.DataSetName = "DatasetAgencia"
            Me.Prefix = ""
            Me.Namespace = "http://tempuri.org/DatasetAgencia.xsd"
            Me.Locale = New System.Globalization.CultureInfo("en-US")
            Me.CaseSensitive = false
            Me.EnforceConstraints = true
            Me.tableT0104413 = New T0104413DataTable
            Me.Tables.Add(Me.tableT0104413)
        End Sub
        
        Private Function ShouldSerializeT0104413() As Boolean
            Return false
        End Function
        
        Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
            If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
                Me.InitVars
            End If
        End Sub
        
        Public Delegate Sub T0104413RowChangeEventHandler(ByVal sender As Object, ByVal e As T0104413RowChangeEvent)
        
        <System.Diagnostics.DebuggerStepThrough()>  _
        Public Class T0104413DataTable
            Inherits DataTable
            Implements System.Collections.IEnumerable
            
            Private columnCODBCO As DataColumn
            
            Private columnCODAGEBCO As DataColumn
            
            Private columnNUMDIGVRFAGEBCO As DataColumn
            
            Private columnNOMAGEBCO As DataColumn
            
            Private columnCODCIDAGEBCO As DataColumn
            
            Private columnENDAGEBCO As DataColumn
            
            Private columnCODCEPAGEBCO As DataColumn
            
            Private columnNUMTLFAGEBCO As DataColumn
            
            Private columnNUMCGCAGEBCO As DataColumn
            
            Private columnFLGAGECOBBCO As DataColumn
            
            Private columnNUMDGTVRFCNTCRRCDT As DataColumn
            
            Private columnFLGAGECDTCOBBCO As DataColumn
            
            Private columnNUMCNTCRRCDT As DataColumn
            
            Private columnNUMFAXAGEBCO As DataColumn
            
            Friend Sub New()
                MyBase.New("T0104413")
                Me.InitClass
            End Sub
            
            Friend Sub New(ByVal table As DataTable)
                MyBase.New(table.TableName)
                If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                    Me.CaseSensitive = table.CaseSensitive
                End If
                If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                    Me.Locale = table.Locale
                End If
                If (table.Namespace <> table.DataSet.Namespace) Then
                    Me.Namespace = table.Namespace
                End If
                Me.Prefix = table.Prefix
                Me.MinimumCapacity = table.MinimumCapacity
                Me.DisplayExpression = table.DisplayExpression
            End Sub
            
            <System.ComponentModel.Browsable(false)>  _
            Public ReadOnly Property Count As Integer
                Get
                    Return Me.Rows.Count
                End Get
            End Property
            
            Friend ReadOnly Property CODBCOColumn As DataColumn
                Get
                    Return Me.columnCODBCO
                End Get
            End Property
            
            Friend ReadOnly Property CODAGEBCOColumn As DataColumn
                Get
                    Return Me.columnCODAGEBCO
                End Get
            End Property
            
            Friend ReadOnly Property NUMDIGVRFAGEBCOColumn As DataColumn
                Get
                    Return Me.columnNUMDIGVRFAGEBCO
                End Get
            End Property
            
            Friend ReadOnly Property NOMAGEBCOColumn As DataColumn
                Get
                    Return Me.columnNOMAGEBCO
                End Get
            End Property
            
            Friend ReadOnly Property CODCIDAGEBCOColumn As DataColumn
                Get
                    Return Me.columnCODCIDAGEBCO
                End Get
            End Property
            
            Friend ReadOnly Property ENDAGEBCOColumn As DataColumn
                Get
                    Return Me.columnENDAGEBCO
                End Get
            End Property
            
            Friend ReadOnly Property CODCEPAGEBCOColumn As DataColumn
                Get
                    Return Me.columnCODCEPAGEBCO
                End Get
            End Property
            
            Friend ReadOnly Property NUMTLFAGEBCOColumn As DataColumn
                Get
                    Return Me.columnNUMTLFAGEBCO
                End Get
            End Property
            
            Friend ReadOnly Property NUMCGCAGEBCOColumn As DataColumn
                Get
                    Return Me.columnNUMCGCAGEBCO
                End Get
            End Property
            
            Friend ReadOnly Property FLGAGECOBBCOColumn As DataColumn
                Get
                    Return Me.columnFLGAGECOBBCO
                End Get
            End Property
            
            Friend ReadOnly Property NUMDGTVRFCNTCRRCDTColumn As DataColumn
                Get
                    Return Me.columnNUMDGTVRFCNTCRRCDT
                End Get
            End Property
            
            Friend ReadOnly Property FLGAGECDTCOBBCOColumn As DataColumn
                Get
                    Return Me.columnFLGAGECDTCOBBCO
                End Get
            End Property
            
            Friend ReadOnly Property NUMCNTCRRCDTColumn As DataColumn
                Get
                    Return Me.columnNUMCNTCRRCDT
                End Get
            End Property
            
            Friend ReadOnly Property NUMFAXAGEBCOColumn As DataColumn
                Get
                    Return Me.columnNUMFAXAGEBCO
                End Get
            End Property
            
            Public Default ReadOnly Property Item(ByVal index As Integer) As T0104413Row
                Get
                    Return CType(Me.Rows(index),T0104413Row)
                End Get
            End Property
            
            Public Event T0104413RowChanged As T0104413RowChangeEventHandler
            
            Public Event T0104413RowChanging As T0104413RowChangeEventHandler
            
            Public Event T0104413RowDeleted As T0104413RowChangeEventHandler
            
            Public Event T0104413RowDeleting As T0104413RowChangeEventHandler
            
            Public Overloads Sub AddT0104413Row(ByVal row As T0104413Row)
                Me.Rows.Add(row)
            End Sub
            
            Public Overloads Function AddT0104413Row(ByVal CODBCO As Decimal, ByVal CODAGEBCO As Decimal, ByVal NUMDIGVRFAGEBCO As String, ByVal NOMAGEBCO As String, ByVal CODCIDAGEBCO As Decimal, ByVal ENDAGEBCO As String, ByVal CODCEPAGEBCO As Decimal, ByVal NUMTLFAGEBCO As String, ByVal NUMCGCAGEBCO As String, ByVal FLGAGECOBBCO As String, ByVal NUMDGTVRFCNTCRRCDT As Decimal, ByVal FLGAGECDTCOBBCO As String, ByVal NUMCNTCRRCDT As Decimal, ByVal NUMFAXAGEBCO As String) As T0104413Row
                Dim rowT0104413Row As T0104413Row = CType(Me.NewRow,T0104413Row)
                rowT0104413Row.ItemArray = New Object() {CODBCO, CODAGEBCO, NUMDIGVRFAGEBCO, NOMAGEBCO, CODCIDAGEBCO, ENDAGEBCO, CODCEPAGEBCO, NUMTLFAGEBCO, NUMCGCAGEBCO, FLGAGECOBBCO, NUMDGTVRFCNTCRRCDT, FLGAGECDTCOBBCO, NUMCNTCRRCDT, NUMFAXAGEBCO}
                Me.Rows.Add(rowT0104413Row)
                Return rowT0104413Row
            End Function
            
            Public Function FindByCODBCOCODAGEBCO(ByVal CODBCO As Decimal, ByVal CODAGEBCO As Decimal) As T0104413Row
                Return CType(Me.Rows.Find(New Object() {CODBCO, CODAGEBCO}),T0104413Row)
            End Function
            
            Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
                Return Me.Rows.GetEnumerator
            End Function
            
            Public Overrides Function Clone() As DataTable
                Dim cln As T0104413DataTable = CType(MyBase.Clone,T0104413DataTable)
                cln.InitVars
                Return cln
            End Function
            
            Protected Overrides Function CreateInstance() As DataTable
                Return New T0104413DataTable
            End Function
            
            Friend Sub InitVars()
                Me.columnCODBCO = Me.Columns("CODBCO")
                Me.columnCODAGEBCO = Me.Columns("CODAGEBCO")
                Me.columnNUMDIGVRFAGEBCO = Me.Columns("NUMDIGVRFAGEBCO")
                Me.columnNOMAGEBCO = Me.Columns("NOMAGEBCO")
                Me.columnCODCIDAGEBCO = Me.Columns("CODCIDAGEBCO")
                Me.columnENDAGEBCO = Me.Columns("ENDAGEBCO")
                Me.columnCODCEPAGEBCO = Me.Columns("CODCEPAGEBCO")
                Me.columnNUMTLFAGEBCO = Me.Columns("NUMTLFAGEBCO")
                Me.columnNUMCGCAGEBCO = Me.Columns("NUMCGCAGEBCO")
                Me.columnFLGAGECOBBCO = Me.Columns("FLGAGECOBBCO")
                Me.columnNUMDGTVRFCNTCRRCDT = Me.Columns("NUMDGTVRFCNTCRRCDT")
                Me.columnFLGAGECDTCOBBCO = Me.Columns("FLGAGECDTCOBBCO")
                Me.columnNUMCNTCRRCDT = Me.Columns("NUMCNTCRRCDT")
                Me.columnNUMFAXAGEBCO = Me.Columns("NUMFAXAGEBCO")
            End Sub
            
            Private Sub InitClass()
                Me.columnCODBCO = New DataColumn("CODBCO", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
                Me.Columns.Add(Me.columnCODBCO)
                Me.columnCODAGEBCO = New DataColumn("CODAGEBCO", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
                Me.Columns.Add(Me.columnCODAGEBCO)
                Me.columnNUMDIGVRFAGEBCO = New DataColumn("NUMDIGVRFAGEBCO", GetType(System.String), Nothing, System.Data.MappingType.Element)
                Me.Columns.Add(Me.columnNUMDIGVRFAGEBCO)
                Me.columnNOMAGEBCO = New DataColumn("NOMAGEBCO", GetType(System.String), Nothing, System.Data.MappingType.Element)
                Me.Columns.Add(Me.columnNOMAGEBCO)
                Me.columnCODCIDAGEBCO = New DataColumn("CODCIDAGEBCO", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
                Me.Columns.Add(Me.columnCODCIDAGEBCO)
                Me.columnENDAGEBCO = New DataColumn("ENDAGEBCO", GetType(System.String), Nothing, System.Data.MappingType.Element)
                Me.Columns.Add(Me.columnENDAGEBCO)
                Me.columnCODCEPAGEBCO = New DataColumn("CODCEPAGEBCO", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
                Me.Columns.Add(Me.columnCODCEPAGEBCO)
                Me.columnNUMTLFAGEBCO = New DataColumn("NUMTLFAGEBCO", GetType(System.String), Nothing, System.Data.MappingType.Element)
                Me.Columns.Add(Me.columnNUMTLFAGEBCO)
                Me.columnNUMCGCAGEBCO = New DataColumn("NUMCGCAGEBCO", GetType(System.String), Nothing, System.Data.MappingType.Element)
                Me.Columns.Add(Me.columnNUMCGCAGEBCO)
                Me.columnFLGAGECOBBCO = New DataColumn("FLGAGECOBBCO", GetType(System.String), Nothing, System.Data.MappingType.Element)
                Me.Columns.Add(Me.columnFLGAGECOBBCO)
                Me.columnNUMDGTVRFCNTCRRCDT = New DataColumn("NUMDGTVRFCNTCRRCDT", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
                Me.Columns.Add(Me.columnNUMDGTVRFCNTCRRCDT)
                Me.columnFLGAGECDTCOBBCO = New DataColumn("FLGAGECDTCOBBCO", GetType(System.String), Nothing, System.Data.MappingType.Element)
                Me.Columns.Add(Me.columnFLGAGECDTCOBBCO)
                Me.columnNUMCNTCRRCDT = New DataColumn("NUMCNTCRRCDT", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
                Me.Columns.Add(Me.columnNUMCNTCRRCDT)
                Me.columnNUMFAXAGEBCO = New DataColumn("NUMFAXAGEBCO", GetType(System.String), Nothing, System.Data.MappingType.Element)
                Me.Columns.Add(Me.columnNUMFAXAGEBCO)
                Me.Constraints.Add(New UniqueConstraint("DatasetAgenciaKey1", New DataColumn() {Me.columnCODBCO, Me.columnCODAGEBCO}, true))
                Me.columnCODBCO.AllowDBNull = false
                Me.columnCODAGEBCO.AllowDBNull = false
                Me.columnNUMDIGVRFAGEBCO.AllowDBNull = false
                Me.columnNOMAGEBCO.AllowDBNull = false
                Me.columnCODCIDAGEBCO.AllowDBNull = false
                Me.columnENDAGEBCO.AllowDBNull = false
                Me.columnCODCEPAGEBCO.AllowDBNull = false
                Me.columnNUMTLFAGEBCO.AllowDBNull = false
                Me.columnNUMCGCAGEBCO.AllowDBNull = false
                Me.columnFLGAGECOBBCO.AllowDBNull = false
                Me.columnNUMDGTVRFCNTCRRCDT.AllowDBNull = false
                Me.columnFLGAGECDTCOBBCO.AllowDBNull = false
                Me.columnNUMCNTCRRCDT.AllowDBNull = false
                Me.columnNUMFAXAGEBCO.AllowDBNull = false
            End Sub
            
            Public Function NewT0104413Row() As T0104413Row
                Return CType(Me.NewRow,T0104413Row)
            End Function
            
            Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
                Return New T0104413Row(builder)
            End Function
            
            Protected Overrides Function GetRowType() As System.Type
                Return GetType(T0104413Row)
            End Function
            
            Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
                MyBase.OnRowChanged(e)
                If (Not (Me.T0104413RowChangedEvent) Is Nothing) Then
                    RaiseEvent T0104413RowChanged(Me, New T0104413RowChangeEvent(CType(e.Row,T0104413Row), e.Action))
                End If
            End Sub
            
            Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
                MyBase.OnRowChanging(e)
                If (Not (Me.T0104413RowChangingEvent) Is Nothing) Then
                    RaiseEvent T0104413RowChanging(Me, New T0104413RowChangeEvent(CType(e.Row,T0104413Row), e.Action))
                End If
            End Sub
            
            Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
                MyBase.OnRowDeleted(e)
                If (Not (Me.T0104413RowDeletedEvent) Is Nothing) Then
                    RaiseEvent T0104413RowDeleted(Me, New T0104413RowChangeEvent(CType(e.Row,T0104413Row), e.Action))
                End If
            End Sub
            
            Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
                MyBase.OnRowDeleting(e)
                If (Not (Me.T0104413RowDeletingEvent) Is Nothing) Then
                    RaiseEvent T0104413RowDeleting(Me, New T0104413RowChangeEvent(CType(e.Row,T0104413Row), e.Action))
                End If
            End Sub
            
            Public Sub RemoveT0104413Row(ByVal row As T0104413Row)
                Me.Rows.Remove(row)
            End Sub
        End Class
        
        <System.Diagnostics.DebuggerStepThrough()>  _
        Public Class T0104413Row
            Inherits DataRow
            
            Private tableT0104413 As T0104413DataTable
            
            Friend Sub New(ByVal rb As DataRowBuilder)
                MyBase.New(rb)
                Me.tableT0104413 = CType(Me.Table,T0104413DataTable)
            End Sub
            
            Public Property CODBCO As Decimal
                Get
                    Return CType(Me(Me.tableT0104413.CODBCOColumn),Decimal)
                End Get
                Set
                    Me(Me.tableT0104413.CODBCOColumn) = value
                End Set
            End Property
            
            Public Property CODAGEBCO As Decimal
                Get
                    Return CType(Me(Me.tableT0104413.CODAGEBCOColumn),Decimal)
                End Get
                Set
                    Me(Me.tableT0104413.CODAGEBCOColumn) = value
                End Set
            End Property
            
            Public Property NUMDIGVRFAGEBCO As String
                Get
                    Return CType(Me(Me.tableT0104413.NUMDIGVRFAGEBCOColumn),String)
                End Get
                Set
                    Me(Me.tableT0104413.NUMDIGVRFAGEBCOColumn) = value
                End Set
            End Property
            
            Public Property NOMAGEBCO As String
                Get
                    Return CType(Me(Me.tableT0104413.NOMAGEBCOColumn),String)
                End Get
                Set
                    Me(Me.tableT0104413.NOMAGEBCOColumn) = value
                End Set
            End Property
            
            Public Property CODCIDAGEBCO As Decimal
                Get
                    Return CType(Me(Me.tableT0104413.CODCIDAGEBCOColumn),Decimal)
                End Get
                Set
                    Me(Me.tableT0104413.CODCIDAGEBCOColumn) = value
                End Set
            End Property
            
            Public Property ENDAGEBCO As String
                Get
                    Return CType(Me(Me.tableT0104413.ENDAGEBCOColumn),String)
                End Get
                Set
                    Me(Me.tableT0104413.ENDAGEBCOColumn) = value
                End Set
            End Property
            
            Public Property CODCEPAGEBCO As Decimal
                Get
                    Return CType(Me(Me.tableT0104413.CODCEPAGEBCOColumn),Decimal)
                End Get
                Set
                    Me(Me.tableT0104413.CODCEPAGEBCOColumn) = value
                End Set
            End Property
            
            Public Property NUMTLFAGEBCO As String
                Get
                    Return CType(Me(Me.tableT0104413.NUMTLFAGEBCOColumn),String)
                End Get
                Set
                    Me(Me.tableT0104413.NUMTLFAGEBCOColumn) = value
                End Set
            End Property
            
            Public Property NUMCGCAGEBCO As String
                Get
                    Return CType(Me(Me.tableT0104413.NUMCGCAGEBCOColumn),String)
                End Get
                Set
                    Me(Me.tableT0104413.NUMCGCAGEBCOColumn) = value
                End Set
            End Property
            
            Public Property FLGAGECOBBCO As String
                Get
                    Return CType(Me(Me.tableT0104413.FLGAGECOBBCOColumn),String)
                End Get
                Set
                    Me(Me.tableT0104413.FLGAGECOBBCOColumn) = value
                End Set
            End Property
            
            Public Property NUMDGTVRFCNTCRRCDT As Decimal
                Get
                    Return CType(Me(Me.tableT0104413.NUMDGTVRFCNTCRRCDTColumn),Decimal)
                End Get
                Set
                    Me(Me.tableT0104413.NUMDGTVRFCNTCRRCDTColumn) = value
                End Set
            End Property
            
            Public Property FLGAGECDTCOBBCO As String
                Get
                    Return CType(Me(Me.tableT0104413.FLGAGECDTCOBBCOColumn),String)
                End Get
                Set
                    Me(Me.tableT0104413.FLGAGECDTCOBBCOColumn) = value
                End Set
            End Property
            
            Public Property NUMCNTCRRCDT As Decimal
                Get
                    Return CType(Me(Me.tableT0104413.NUMCNTCRRCDTColumn),Decimal)
                End Get
                Set
                    Me(Me.tableT0104413.NUMCNTCRRCDTColumn) = value
                End Set
            End Property
            
            Public Property NUMFAXAGEBCO As String
                Get
                    Return CType(Me(Me.tableT0104413.NUMFAXAGEBCOColumn),String)
                End Get
                Set
                    Me(Me.tableT0104413.NUMFAXAGEBCOColumn) = value
                End Set
            End Property
        End Class
        
        <System.Diagnostics.DebuggerStepThrough()>  _
        Public Class T0104413RowChangeEvent
            Inherits EventArgs
            
            Private eventRow As T0104413Row
            
            Private eventAction As DataRowAction
            
            Public Sub New(ByVal row As T0104413Row, ByVal action As DataRowAction)
                MyBase.New
                Me.eventRow = row
                Me.eventAction = action
            End Sub
            
            Public ReadOnly Property Row As T0104413Row
                Get
                    Return Me.eventRow
                End Get
            End Property
            
            Public ReadOnly Property Action As DataRowAction
                Get
                    Return Me.eventAction
                End Get
            End Property
        End Class
    End Class
    
    <Serializable(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Diagnostics.DebuggerStepThrough(),  _
     System.ComponentModel.ToolboxItem(true)>  _
    Public Class DatasetBanco
        Inherits DataSet
        
        Private tableT0100345 As T0100345DataTable
        
        Public Sub New()
            MyBase.New
            Me.InitClass
            Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
            AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
            AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
        End Sub
        
        Protected Sub New(ByVal info As SerializationInfo, ByVal context As StreamingContext)
            MyBase.New
            Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(System.String)),String)
            If (Not (strSchema) Is Nothing) Then
                Dim ds As DataSet = New DataSet
                ds.ReadXmlSchema(New XmlTextReader(New System.IO.StringReader(strSchema)))
                If (Not (ds.Tables("T0100345")) Is Nothing) Then
                    Me.Tables.Add(New T0100345DataTable(ds.Tables("T0100345")))
                End If
                Me.DataSetName = ds.DataSetName
                Me.Prefix = ds.Prefix
                Me.Namespace = ds.Namespace
                Me.Locale = ds.Locale
                Me.CaseSensitive = ds.CaseSensitive
                Me.EnforceConstraints = ds.EnforceConstraints
                Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
                Me.InitVars
            Else
                Me.InitClass
            End If
            Me.GetSerializationData(info, context)
            Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
            AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
            AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
        End Sub
        
        <System.ComponentModel.Browsable(false),  _
         System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
        Public ReadOnly Property T0100345 As T0100345DataTable
            Get
                Return Me.tableT0100345
            End Get
        End Property
        
        Public Overrides Function Clone() As DataSet
            Dim cln As DatasetBanco = CType(MyBase.Clone,DatasetBanco)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function ShouldSerializeTables() As Boolean
            Return false
        End Function
        
        Protected Overrides Function ShouldSerializeRelations() As Boolean
            Return false
        End Function
        
        Protected Overrides Sub ReadXmlSerializable(ByVal reader As XmlReader)
            Me.Reset
            Dim ds As DataSet = New DataSet
            ds.ReadXml(reader)
            If (Not (ds.Tables("T0100345")) Is Nothing) Then
                Me.Tables.Add(New T0100345DataTable(ds.Tables("T0100345")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        End Sub
        
        Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
            Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
            Me.WriteXmlSchema(New XmlTextWriter(stream, Nothing))
            stream.Position = 0
            Return System.Xml.Schema.XmlSchema.Read(New XmlTextReader(stream), Nothing)
        End Function
        
        Friend Sub InitVars()
            Me.tableT0100345 = CType(Me.Tables("T0100345"),T0100345DataTable)
            If (Not (Me.tableT0100345) Is Nothing) Then
                Me.tableT0100345.InitVars
            End If
        End Sub
        
        Private Sub InitClass()
            Me.DataSetName = "DatasetBanco"
            Me.Prefix = ""
            Me.Namespace = "http://tempuri.org/DatasetBanco.xsd"
            Me.Locale = New System.Globalization.CultureInfo("en-US")
            Me.CaseSensitive = false
            Me.EnforceConstraints = true
            Me.tableT0100345 = New T0100345DataTable
            Me.Tables.Add(Me.tableT0100345)
        End Sub
        
        Private Function ShouldSerializeT0100345() As Boolean
            Return false
        End Function
        
        Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
            If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
                Me.InitVars
            End If
        End Sub
        
        Public Delegate Sub T0100345RowChangeEventHandler(ByVal sender As Object, ByVal e As T0100345RowChangeEvent)
        
        <System.Diagnostics.DebuggerStepThrough()>  _
        Public Class T0100345DataTable
            Inherits DataTable
            Implements System.Collections.IEnumerable
            
            Private columnCODBCO As DataColumn
            
            Private columnNOMBCO As DataColumn
            
            Private columnVLRCTTVDR As DataColumn
            
            Private columnENDBCO As DataColumn
            
            Private columnCODCID As DataColumn
            
            Private columnNUMCGCBCO As DataColumn
            
            Private columnVLRLIMCRDRTTVDR As DataColumn
            
            Private columnVLRLIMBDREMS As DataColumn
            
            Private columnVLRCTTVDRDIV As DataColumn
            
            Private columnVLRLIMCRDRTTVDRDIV As DataColumn
            
            Private columnTIPCVNBCO As DataColumn
            
            Private columnTIPSITBCO As DataColumn
            
            Private columnVLRMNMTITCOBBCO As DataColumn
            
            Private columnCODCRTBCO As DataColumn
            
            Private columnCODEMPBCO As DataColumn
            
            Private columnNUMDIABXATITBCO As DataColumn
            
            Private columnFLGBCODFTIPRBLT As DataColumn
            
            Private columnHRALIMEMSCTTVDR As DataColumn
            
            Private columnVLRTRFCOBBCO As DataColumn
            
            Private columnNUMPRXRMSBCO As DataColumn
            
            Private columnCODCNTCTBBCO As DataColumn
            
            Private columnINDBCOCVNFNDIVT As DataColumn
            
            Friend Sub New()
                MyBase.New("T0100345")
                Me.InitClass
            End Sub
            
            Friend Sub New(ByVal table As DataTable)
                MyBase.New(table.TableName)
                If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                    Me.CaseSensitive = table.CaseSensitive
                End If
                If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                    Me.Locale = table.Locale
                End If
                If (table.Namespace <> table.DataSet.Namespace) Then
                    Me.Namespace = table.Namespace
                End If
                Me.Prefix = table.Prefix
                Me.MinimumCapacity = table.MinimumCapacity
                Me.DisplayExpression = table.DisplayExpression
            End Sub
            
            <System.ComponentModel.Browsable(false)>  _
            Public ReadOnly Property Count As Integer
                Get
                    Return Me.Rows.Count
                End Get
            End Property
            
            Friend ReadOnly Property CODBCOColumn As DataColumn
                Get
                    Return Me.columnCODBCO
                End Get
            End Property
            
            Friend ReadOnly Property NOMBCOColumn As DataColumn
                Get
                    Return Me.columnNOMBCO
                End Get
            End Property
            
            Friend ReadOnly Property VLRCTTVDRColumn As DataColumn
                Get
                    Return Me.columnVLRCTTVDR
                End Get
            End Property
            
            Friend ReadOnly Property ENDBCOColumn As DataColumn
                Get
                    Return Me.columnENDBCO
                End Get
            End Property
            
            Friend ReadOnly Property CODCIDColumn As DataColumn
                Get
                    Return Me.columnCODCID
                End Get
            End Property
            
            Friend ReadOnly Property NUMCGCBCOColumn As DataColumn
                Get
                    Return Me.columnNUMCGCBCO
                End Get
            End Property
            
            Friend ReadOnly Property VLRLIMCRDRTTVDRColumn As DataColumn
                Get
                    Return Me.columnVLRLIMCRDRTTVDR
                End Get
            End Property
            
            Friend ReadOnly Property VLRLIMBDREMSColumn As DataColumn
                Get
                    Return Me.columnVLRLIMBDREMS
                End Get
            End Property
            
            Friend ReadOnly Property VLRCTTVDRDIVColumn As DataColumn
                Get
                    Return Me.columnVLRCTTVDRDIV
                End Get
            End Property
            
            Friend ReadOnly Property VLRLIMCRDRTTVDRDIVColumn As DataColumn
                Get
                    Return Me.columnVLRLIMCRDRTTVDRDIV
                End Get
            End Property
            
            Friend ReadOnly Property TIPCVNBCOColumn As DataColumn
                Get
                    Return Me.columnTIPCVNBCO
                End Get
            End Property
            
            Friend ReadOnly Property TIPSITBCOColumn As DataColumn
                Get
                    Return Me.columnTIPSITBCO
                End Get
            End Property
            
            Friend ReadOnly Property VLRMNMTITCOBBCOColumn As DataColumn
                Get
                    Return Me.columnVLRMNMTITCOBBCO
                End Get
            End Property
            
            Friend ReadOnly Property CODCRTBCOColumn As DataColumn
                Get
                    Return Me.columnCODCRTBCO
                End Get
            End Property
            
            Friend ReadOnly Property CODEMPBCOColumn As DataColumn
                Get
                    Return Me.columnCODEMPBCO
                End Get
            End Property
            
            Friend ReadOnly Property NUMDIABXATITBCOColumn As DataColumn
                Get
                    Return Me.columnNUMDIABXATITBCO
                End Get
            End Property
            
            Friend ReadOnly Property FLGBCODFTIPRBLTColumn As DataColumn
                Get
                    Return Me.columnFLGBCODFTIPRBLT
                End Get
            End Property
            
            Friend ReadOnly Property HRALIMEMSCTTVDRColumn As DataColumn
                Get
                    Return Me.columnHRALIMEMSCTTVDR
                End Get
            End Property
            
            Friend ReadOnly Property VLRTRFCOBBCOColumn As DataColumn
                Get
                    Return Me.columnVLRTRFCOBBCO
                End Get
            End Property
            
            Friend ReadOnly Property NUMPRXRMSBCOColumn As DataColumn
                Get
                    Return Me.columnNUMPRXRMSBCO
                End Get
            End Property
            
            Friend ReadOnly Property CODCNTCTBBCOColumn As DataColumn
                Get
                    Return Me.columnCODCNTCTBBCO
                End Get
            End Property
            
            Friend ReadOnly Property INDBCOCVNFNDIVTColumn As DataColumn
                Get
                    Return Me.columnINDBCOCVNFNDIVT
                End Get
            End Property
            
            Public Default ReadOnly Property Item(ByVal index As Integer) As T0100345Row
                Get
                    Return CType(Me.Rows(index),T0100345Row)
                End Get
            End Property
            
            Public Event T0100345RowChanged As T0100345RowChangeEventHandler
            
            Public Event T0100345RowChanging As T0100345RowChangeEventHandler
            
            Public Event T0100345RowDeleted As T0100345RowChangeEventHandler
            
            Public Event T0100345RowDeleting As T0100345RowChangeEventHandler
            
            Public Overloads Sub AddT0100345Row(ByVal row As T0100345Row)
                Me.Rows.Add(row)
            End Sub
            
            Public Overloads Function AddT0100345Row( _
                        ByVal CODBCO As Decimal,  _
                        ByVal NOMBCO As String,  _
                        ByVal VLRCTTVDR As Decimal,  _
                        ByVal ENDBCO As String,  _
                        ByVal CODCID As Decimal,  _
                        ByVal NUMCGCBCO As String,  _
                        ByVal VLRLIMCRDRTTVDR As Decimal,  _
                        ByVal VLRLIMBDREMS As Decimal,  _
                        ByVal VLRCTTVDRDIV As Decimal,  _
                        ByVal VLRLIMCRDRTTVDRDIV As Decimal,  _
                        ByVal TIPCVNBCO As Decimal,  _
                        ByVal TIPSITBCO As Decimal,  _
                        ByVal VLRMNMTITCOBBCO As Decimal,  _
                        ByVal CODCRTBCO As String,  _
                        ByVal CODEMPBCO As Decimal,  _
                        ByVal NUMDIABXATITBCO As Decimal,  _
                        ByVal FLGBCODFTIPRBLT As String,  _
                        ByVal HRALIMEMSCTTVDR As Date,  _
                        ByVal VLRTRFCOBBCO As Decimal,  _
                        ByVal NUMPRXRMSBCO As Decimal,  _
                        ByVal CODCNTCTBBCO As Decimal,  _
                        ByVal INDBCOCVNFNDIVT As Decimal) As T0100345Row
                Dim rowT0100345Row As T0100345Row = CType(Me.NewRow,T0100345Row)
                rowT0100345Row.ItemArray = New Object() {CODBCO, NOMBCO, VLRCTTVDR, ENDBCO, CODCID, NUMCGCBCO, VLRLIMCRDRTTVDR, VLRLIMBDREMS, VLRCTTVDRDIV, VLRLIMCRDRTTVDRDIV, TIPCVNBCO, TIPSITBCO, VLRMNMTITCOBBCO, CODCRTBCO, CODEMPBCO, NUMDIABXATITBCO, FLGBCODFTIPRBLT, HRALIMEMSCTTVDR, VLRTRFCOBBCO, NUMPRXRMSBCO, CODCNTCTBBCO, INDBCOCVNFNDIVT}
                Me.Rows.Add(rowT0100345Row)
                Return rowT0100345Row
            End Function
            
            Public Function FindByCODBCO(ByVal CODBCO As Decimal) As T0100345Row
                Return CType(Me.Rows.Find(New Object() {CODBCO}),T0100345Row)
            End Function
            
            Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
                Return Me.Rows.GetEnumerator
            End Function
            
            Public Overrides Function Clone() As DataTable
                Dim cln As T0100345DataTable = CType(MyBase.Clone,T0100345DataTable)
                cln.InitVars
                Return cln
            End Function
            
            Protected Overrides Function CreateInstance() As DataTable
                Return New T0100345DataTable
            End Function
            
            Friend Sub InitVars()
                Me.columnCODBCO = Me.Columns("CODBCO")
                Me.columnNOMBCO = Me.Columns("NOMBCO")
                Me.columnVLRCTTVDR = Me.Columns("VLRCTTVDR")
                Me.columnENDBCO = Me.Columns("ENDBCO")
                Me.columnCODCID = Me.Columns("CODCID")
                Me.columnNUMCGCBCO = Me.Columns("NUMCGCBCO")
                Me.columnVLRLIMCRDRTTVDR = Me.Columns("VLRLIMCRDRTTVDR")
                Me.columnVLRLIMBDREMS = Me.Columns("VLRLIMBDREMS")
                Me.columnVLRCTTVDRDIV = Me.Columns("VLRCTTVDRDIV")
                Me.columnVLRLIMCRDRTTVDRDIV = Me.Columns("VLRLIMCRDRTTVDRDIV")
                Me.columnTIPCVNBCO = Me.Columns("TIPCVNBCO")
                Me.columnTIPSITBCO = Me.Columns("TIPSITBCO")
                Me.columnVLRMNMTITCOBBCO = Me.Columns("VLRMNMTITCOBBCO")
                Me.columnCODCRTBCO = Me.Columns("CODCRTBCO")
                Me.columnCODEMPBCO = Me.Columns("CODEMPBCO")
                Me.columnNUMDIABXATITBCO = Me.Columns("NUMDIABXATITBCO")
                Me.columnFLGBCODFTIPRBLT = Me.Columns("FLGBCODFTIPRBLT")
                Me.columnHRALIMEMSCTTVDR = Me.Columns("HRALIMEMSCTTVDR")
                Me.columnVLRTRFCOBBCO = Me.Columns("VLRTRFCOBBCO")
                Me.columnNUMPRXRMSBCO = Me.Columns("NUMPRXRMSBCO")
                Me.columnCODCNTCTBBCO = Me.Columns("CODCNTCTBBCO")
                Me.columnINDBCOCVNFNDIVT = Me.Columns("INDBCOCVNFNDIVT")
            End Sub
            
            Private Sub InitClass()
                Me.columnCODBCO = New DataColumn("CODBCO", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
                Me.Columns.Add(Me.columnCODBCO)
                Me.columnNOMBCO = New DataColumn("NOMBCO", GetType(System.String), Nothing, System.Data.MappingType.Element)
                Me.Columns.Add(Me.columnNOMBCO)
                Me.columnVLRCTTVDR = New DataColumn("VLRCTTVDR", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
                Me.Columns.Add(Me.columnVLRCTTVDR)
                Me.columnENDBCO = New DataColumn("ENDBCO", GetType(System.String), Nothing, System.Data.MappingType.Element)
                Me.Columns.Add(Me.columnENDBCO)
                Me.columnCODCID = New DataColumn("CODCID", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
                Me.Columns.Add(Me.columnCODCID)
                Me.columnNUMCGCBCO = New DataColumn("NUMCGCBCO", GetType(System.String), Nothing, System.Data.MappingType.Element)
                Me.Columns.Add(Me.columnNUMCGCBCO)
                Me.columnVLRLIMCRDRTTVDR = New DataColumn("VLRLIMCRDRTTVDR", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
                Me.Columns.Add(Me.columnVLRLIMCRDRTTVDR)
                Me.columnVLRLIMBDREMS = New DataColumn("VLRLIMBDREMS", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
                Me.Columns.Add(Me.columnVLRLIMBDREMS)
                Me.columnVLRCTTVDRDIV = New DataColumn("VLRCTTVDRDIV", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
                Me.Columns.Add(Me.columnVLRCTTVDRDIV)
                Me.columnVLRLIMCRDRTTVDRDIV = New DataColumn("VLRLIMCRDRTTVDRDIV", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
                Me.Columns.Add(Me.columnVLRLIMCRDRTTVDRDIV)
                Me.columnTIPCVNBCO = New DataColumn("TIPCVNBCO", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
                Me.Columns.Add(Me.columnTIPCVNBCO)
                Me.columnTIPSITBCO = New DataColumn("TIPSITBCO", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
                Me.Columns.Add(Me.columnTIPSITBCO)
                Me.columnVLRMNMTITCOBBCO = New DataColumn("VLRMNMTITCOBBCO", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
                Me.Columns.Add(Me.columnVLRMNMTITCOBBCO)
                Me.columnCODCRTBCO = New DataColumn("CODCRTBCO", GetType(System.String), Nothing, System.Data.MappingType.Element)
                Me.Columns.Add(Me.columnCODCRTBCO)
                Me.columnCODEMPBCO = New DataColumn("CODEMPBCO", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
                Me.Columns.Add(Me.columnCODEMPBCO)
                Me.columnNUMDIABXATITBCO = New DataColumn("NUMDIABXATITBCO", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
                Me.Columns.Add(Me.columnNUMDIABXATITBCO)
                Me.columnFLGBCODFTIPRBLT = New DataColumn("FLGBCODFTIPRBLT", GetType(System.String), Nothing, System.Data.MappingType.Element)
                Me.Columns.Add(Me.columnFLGBCODFTIPRBLT)
                Me.columnHRALIMEMSCTTVDR = New DataColumn("HRALIMEMSCTTVDR", GetType(System.DateTime), Nothing, System.Data.MappingType.Element)
                Me.Columns.Add(Me.columnHRALIMEMSCTTVDR)
                Me.columnVLRTRFCOBBCO = New DataColumn("VLRTRFCOBBCO", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
                Me.Columns.Add(Me.columnVLRTRFCOBBCO)
                Me.columnNUMPRXRMSBCO = New DataColumn("NUMPRXRMSBCO", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
                Me.Columns.Add(Me.columnNUMPRXRMSBCO)
                Me.columnCODCNTCTBBCO = New DataColumn("CODCNTCTBBCO", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
                Me.Columns.Add(Me.columnCODCNTCTBBCO)
                Me.columnINDBCOCVNFNDIVT = New DataColumn("INDBCOCVNFNDIVT", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
                Me.Columns.Add(Me.columnINDBCOCVNFNDIVT)
                Me.Constraints.Add(New UniqueConstraint("DatasetBancoKey1", New DataColumn() {Me.columnCODBCO}, true))
                Me.columnCODBCO.AllowDBNull = false
                Me.columnCODBCO.Unique = true
                Me.columnNOMBCO.AllowDBNull = false
                Me.columnVLRCTTVDR.AllowDBNull = false
                Me.columnENDBCO.AllowDBNull = false
                Me.columnCODCID.AllowDBNull = false
                Me.columnVLRLIMCRDRTTVDR.AllowDBNull = false
                Me.columnVLRLIMBDREMS.AllowDBNull = false
                Me.columnVLRCTTVDRDIV.AllowDBNull = false
                Me.columnVLRLIMCRDRTTVDRDIV.AllowDBNull = false
                Me.columnTIPCVNBCO.AllowDBNull = false
                Me.columnTIPSITBCO.AllowDBNull = false
                Me.columnVLRMNMTITCOBBCO.AllowDBNull = false
                Me.columnCODCRTBCO.AllowDBNull = false
                Me.columnCODEMPBCO.AllowDBNull = false
                Me.columnNUMDIABXATITBCO.AllowDBNull = false
                Me.columnFLGBCODFTIPRBLT.AllowDBNull = false
                Me.columnHRALIMEMSCTTVDR.AllowDBNull = false
                Me.columnVLRTRFCOBBCO.AllowDBNull = false
                Me.columnNUMPRXRMSBCO.AllowDBNull = false
                Me.columnCODCNTCTBBCO.AllowDBNull = false
                Me.columnINDBCOCVNFNDIVT.AllowDBNull = false
            End Sub
            
            Public Function NewT0100345Row() As T0100345Row
                Return CType(Me.NewRow,T0100345Row)
            End Function
            
            Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
                Return New T0100345Row(builder)
            End Function
            
            Protected Overrides Function GetRowType() As System.Type
                Return GetType(T0100345Row)
            End Function
            
            Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
                MyBase.OnRowChanged(e)
                If (Not (Me.T0100345RowChangedEvent) Is Nothing) Then
                    RaiseEvent T0100345RowChanged(Me, New T0100345RowChangeEvent(CType(e.Row,T0100345Row), e.Action))
                End If
            End Sub
            
            Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
                MyBase.OnRowChanging(e)
                If (Not (Me.T0100345RowChangingEvent) Is Nothing) Then
                    RaiseEvent T0100345RowChanging(Me, New T0100345RowChangeEvent(CType(e.Row,T0100345Row), e.Action))
                End If
            End Sub
            
            Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
                MyBase.OnRowDeleted(e)
                If (Not (Me.T0100345RowDeletedEvent) Is Nothing) Then
                    RaiseEvent T0100345RowDeleted(Me, New T0100345RowChangeEvent(CType(e.Row,T0100345Row), e.Action))
                End If
            End Sub
            
            Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
                MyBase.OnRowDeleting(e)
                If (Not (Me.T0100345RowDeletingEvent) Is Nothing) Then
                    RaiseEvent T0100345RowDeleting(Me, New T0100345RowChangeEvent(CType(e.Row,T0100345Row), e.Action))
                End If
            End Sub
            
            Public Sub RemoveT0100345Row(ByVal row As T0100345Row)
                Me.Rows.Remove(row)
            End Sub
        End Class
        
        <System.Diagnostics.DebuggerStepThrough()>  _
        Public Class T0100345Row
            Inherits DataRow
            
            Private tableT0100345 As T0100345DataTable
            
            Friend Sub New(ByVal rb As DataRowBuilder)
                MyBase.New(rb)
                Me.tableT0100345 = CType(Me.Table,T0100345DataTable)
            End Sub
            
            Public Property CODBCO As Decimal
                Get
                    Return CType(Me(Me.tableT0100345.CODBCOColumn),Decimal)
                End Get
                Set
                    Me(Me.tableT0100345.CODBCOColumn) = value
                End Set
            End Property
            
            Public Property NOMBCO As String
                Get
                    Return CType(Me(Me.tableT0100345.NOMBCOColumn),String)
                End Get
                Set
                    Me(Me.tableT0100345.NOMBCOColumn) = value
                End Set
            End Property
            
            Public Property VLRCTTVDR As Decimal
                Get
                    Return CType(Me(Me.tableT0100345.VLRCTTVDRColumn),Decimal)
                End Get
                Set
                    Me(Me.tableT0100345.VLRCTTVDRColumn) = value
                End Set
            End Property
            
            Public Property ENDBCO As String
                Get
                    Return CType(Me(Me.tableT0100345.ENDBCOColumn),String)
                End Get
                Set
                    Me(Me.tableT0100345.ENDBCOColumn) = value
                End Set
            End Property
            
            Public Property CODCID As Decimal
                Get
                    Return CType(Me(Me.tableT0100345.CODCIDColumn),Decimal)
                End Get
                Set
                    Me(Me.tableT0100345.CODCIDColumn) = value
                End Set
            End Property
            
            Public Property NUMCGCBCO As String
                Get
                    Try 
                        Return CType(Me(Me.tableT0100345.NUMCGCBCOColumn),String)
                    Catch e As InvalidCastException
                        Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                    End Try
                End Get
                Set
                    Me(Me.tableT0100345.NUMCGCBCOColumn) = value
                End Set
            End Property
            
            Public Property VLRLIMCRDRTTVDR As Decimal
                Get
                    Return CType(Me(Me.tableT0100345.VLRLIMCRDRTTVDRColumn),Decimal)
                End Get
                Set
                    Me(Me.tableT0100345.VLRLIMCRDRTTVDRColumn) = value
                End Set
            End Property
            
            Public Property VLRLIMBDREMS As Decimal
                Get
                    Return CType(Me(Me.tableT0100345.VLRLIMBDREMSColumn),Decimal)
                End Get
                Set
                    Me(Me.tableT0100345.VLRLIMBDREMSColumn) = value
                End Set
            End Property
            
            Public Property VLRCTTVDRDIV As Decimal
                Get
                    Return CType(Me(Me.tableT0100345.VLRCTTVDRDIVColumn),Decimal)
                End Get
                Set
                    Me(Me.tableT0100345.VLRCTTVDRDIVColumn) = value
                End Set
            End Property
            
            Public Property VLRLIMCRDRTTVDRDIV As Decimal
                Get
                    Return CType(Me(Me.tableT0100345.VLRLIMCRDRTTVDRDIVColumn),Decimal)
                End Get
                Set
                    Me(Me.tableT0100345.VLRLIMCRDRTTVDRDIVColumn) = value
                End Set
            End Property
            
            Public Property TIPCVNBCO As Decimal
                Get
                    Return CType(Me(Me.tableT0100345.TIPCVNBCOColumn),Decimal)
                End Get
                Set
                    Me(Me.tableT0100345.TIPCVNBCOColumn) = value
                End Set
            End Property
            
            Public Property TIPSITBCO As Decimal
                Get
                    Return CType(Me(Me.tableT0100345.TIPSITBCOColumn),Decimal)
                End Get
                Set
                    Me(Me.tableT0100345.TIPSITBCOColumn) = value
                End Set
            End Property
            
            Public Property VLRMNMTITCOBBCO As Decimal
                Get
                    Return CType(Me(Me.tableT0100345.VLRMNMTITCOBBCOColumn),Decimal)
                End Get
                Set
                    Me(Me.tableT0100345.VLRMNMTITCOBBCOColumn) = value
                End Set
            End Property
            
            Public Property CODCRTBCO As String
                Get
                    Return CType(Me(Me.tableT0100345.CODCRTBCOColumn),String)
                End Get
                Set
                    Me(Me.tableT0100345.CODCRTBCOColumn) = value
                End Set
            End Property
            
            Public Property CODEMPBCO As Decimal
                Get
                    Return CType(Me(Me.tableT0100345.CODEMPBCOColumn),Decimal)
                End Get
                Set
                    Me(Me.tableT0100345.CODEMPBCOColumn) = value
                End Set
            End Property
            
            Public Property NUMDIABXATITBCO As Decimal
                Get
                    Return CType(Me(Me.tableT0100345.NUMDIABXATITBCOColumn),Decimal)
                End Get
                Set
                    Me(Me.tableT0100345.NUMDIABXATITBCOColumn) = value
                End Set
            End Property
            
            Public Property FLGBCODFTIPRBLT As String
                Get
                    Return CType(Me(Me.tableT0100345.FLGBCODFTIPRBLTColumn),String)
                End Get
                Set
                    Me(Me.tableT0100345.FLGBCODFTIPRBLTColumn) = value
                End Set
            End Property
            
            Public Property HRALIMEMSCTTVDR As Date
                Get
                    Return CType(Me(Me.tableT0100345.HRALIMEMSCTTVDRColumn),Date)
                End Get
                Set
                    Me(Me.tableT0100345.HRALIMEMSCTTVDRColumn) = value
                End Set
            End Property
            
            Public Property VLRTRFCOBBCO As Decimal
                Get
                    Return CType(Me(Me.tableT0100345.VLRTRFCOBBCOColumn),Decimal)
                End Get
                Set
                    Me(Me.tableT0100345.VLRTRFCOBBCOColumn) = value
                End Set
            End Property
            
            Public Property NUMPRXRMSBCO As Decimal
                Get
                    Return CType(Me(Me.tableT0100345.NUMPRXRMSBCOColumn),Decimal)
                End Get
                Set
                    Me(Me.tableT0100345.NUMPRXRMSBCOColumn) = value
                End Set
            End Property
            
            Public Property CODCNTCTBBCO As Decimal
                Get
                    Return CType(Me(Me.tableT0100345.CODCNTCTBBCOColumn),Decimal)
                End Get
                Set
                    Me(Me.tableT0100345.CODCNTCTBBCOColumn) = value
                End Set
            End Property
            
            Public Property INDBCOCVNFNDIVT As Decimal
                Get
                    Return CType(Me(Me.tableT0100345.INDBCOCVNFNDIVTColumn),Decimal)
                End Get
                Set
                    Me(Me.tableT0100345.INDBCOCVNFNDIVTColumn) = value
                End Set
            End Property
            
            Public Function IsNUMCGCBCONull() As Boolean
                Return Me.IsNull(Me.tableT0100345.NUMCGCBCOColumn)
            End Function
            
            Public Sub SetNUMCGCBCONull()
                Me(Me.tableT0100345.NUMCGCBCOColumn) = System.Convert.DBNull
            End Sub
        End Class
        
        <System.Diagnostics.DebuggerStepThrough()>  _
        Public Class T0100345RowChangeEvent
            Inherits EventArgs
            
            Private eventRow As T0100345Row
            
            Private eventAction As DataRowAction
            
            Public Sub New(ByVal row As T0100345Row, ByVal action As DataRowAction)
                MyBase.New
                Me.eventRow = row
                Me.eventAction = action
            End Sub
            
            Public ReadOnly Property Row As T0100345Row
                Get
                    Return Me.eventRow
                End Get
            End Property
            
            Public ReadOnly Property Action As DataRowAction
                Get
                    Return Me.eventAction
                End Get
            End Property
        End Class
    End Class
End Namespace
