'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Data
Imports System.Runtime.Serialization
Imports System.Xml


<Serializable(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Diagnostics.DebuggerStepThrough(),  _
 System.ComponentModel.ToolboxItem(true)>  _
Public Class DatasetContaCorrenteFornecedor
    Inherits DataSet
    
    Private tableT0123086 As T0123086DataTable
    
    Private tableT0100426 As T0100426DataTable
    
    Private relationT0100426T0123086 As DataRelation
    
    Public Sub New()
        MyBase.New
        Me.InitClass
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    Protected Sub New(ByVal info As SerializationInfo, ByVal context As StreamingContext)
        MyBase.New
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(System.String)),String)
        If (Not (strSchema) Is Nothing) Then
            Dim ds As DataSet = New DataSet
            ds.ReadXmlSchema(New XmlTextReader(New System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("T0123086")) Is Nothing) Then
                Me.Tables.Add(New T0123086DataTable(ds.Tables("T0123086")))
            End If
            If (Not (ds.Tables("T0100426")) Is Nothing) Then
                Me.Tables.Add(New T0100426DataTable(ds.Tables("T0100426")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.InitClass
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property T0123086 As T0123086DataTable
        Get
            Return Me.tableT0123086
        End Get
    End Property
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property T0100426 As T0100426DataTable
        Get
            Return Me.tableT0100426
        End Get
    End Property
    
    Public Overrides Function Clone() As DataSet
        Dim cln As DatasetContaCorrenteFornecedor = CType(MyBase.Clone,DatasetContaCorrenteFornecedor)
        cln.InitVars
        Return cln
    End Function
    
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As XmlReader)
        Me.Reset
        Dim ds As DataSet = New DataSet
        ds.ReadXml(reader)
        If (Not (ds.Tables("T0123086")) Is Nothing) Then
            Me.Tables.Add(New T0123086DataTable(ds.Tables("T0123086")))
        End If
        If (Not (ds.Tables("T0100426")) Is Nothing) Then
            Me.Tables.Add(New T0100426DataTable(ds.Tables("T0100426")))
        End If
        Me.DataSetName = ds.DataSetName
        Me.Prefix = ds.Prefix
        Me.Namespace = ds.Namespace
        Me.Locale = ds.Locale
        Me.CaseSensitive = ds.CaseSensitive
        Me.EnforceConstraints = ds.EnforceConstraints
        Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
        Me.InitVars
    End Sub
    
    Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
        Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
        Me.WriteXmlSchema(New XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return System.Xml.Schema.XmlSchema.Read(New XmlTextReader(stream), Nothing)
    End Function
    
    Friend Sub InitVars()
        Me.tableT0123086 = CType(Me.Tables("T0123086"),T0123086DataTable)
        If (Not (Me.tableT0123086) Is Nothing) Then
            Me.tableT0123086.InitVars
        End If
        Me.tableT0100426 = CType(Me.Tables("T0100426"),T0100426DataTable)
        If (Not (Me.tableT0100426) Is Nothing) Then
            Me.tableT0100426.InitVars
        End If
        Me.relationT0100426T0123086 = Me.Relations("T0100426T0123086")
    End Sub
    
    Private Sub InitClass()
        Me.DataSetName = "DatasetContaCorrenteFornecedor"
        Me.Prefix = ""
        Me.Namespace = "http://tempuri.org/DatasetContaCorrenteFornecedor.xsd"
        Me.Locale = New System.Globalization.CultureInfo("en-US")
        Me.CaseSensitive = false
        Me.EnforceConstraints = true
        Me.tableT0123086 = New T0123086DataTable
        Me.Tables.Add(Me.tableT0123086)
        Me.tableT0100426 = New T0100426DataTable
        Me.Tables.Add(Me.tableT0100426)
        Dim fkc As ForeignKeyConstraint
        fkc = New ForeignKeyConstraint("T0100426T0123086", New DataColumn() {Me.tableT0100426.CODFRNColumn}, New DataColumn() {Me.tableT0123086.CODFRNColumn})
        Me.tableT0123086.Constraints.Add(fkc)
        fkc.AcceptRejectRule = System.Data.AcceptRejectRule.None
        fkc.DeleteRule = System.Data.Rule.Cascade
        fkc.UpdateRule = System.Data.Rule.Cascade
        Me.relationT0100426T0123086 = New DataRelation("T0100426T0123086", New DataColumn() {Me.tableT0100426.CODFRNColumn}, New DataColumn() {Me.tableT0123086.CODFRNColumn}, false)
        Me.Relations.Add(Me.relationT0100426T0123086)
    End Sub
    
    Private Function ShouldSerializeT0123086() As Boolean
        Return false
    End Function
    
    Private Function ShouldSerializeT0100426() As Boolean
        Return false
    End Function
    
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    Public Delegate Sub T0123086RowChangeEventHandler(ByVal sender As Object, ByVal e As T0123086RowChangeEvent)
    
    Public Delegate Sub T0100426RowChangeEventHandler(ByVal sender As Object, ByVal e As T0100426RowChangeEvent)
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class T0123086DataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable
        
        Private columnCODFRN As DataColumn
        
        Private columnTIPDSNDSCBNF As DataColumn
        
        Private columnDATREFLMT As DataColumn
        
        Private columnCODGDC As DataColumn
        
        Private columnNUMSEQLMT As DataColumn
        
        Private columnCODTIPLMT As DataColumn
        
        Private columnCODCNTCRD As DataColumn
        
        Private columnCODCENCSTCRD As DataColumn
        
        Private columnCODCNTDEB As DataColumn
        
        Private columnCODCENCSTDEB As DataColumn
        
        Private columnVLRLMTCTB As DataColumn
        
        Private columnDESHSTLMT As DataColumn
        
        Private columnDESVARHSTPAD As DataColumn
        
        Private columnDATCTBLMT As DataColumn
        
        Private columnNOMACSUSRGRCLMT As DataColumn
        
        Private columnCODFILEMP As DataColumn
        
        Private columnCODPMS As DataColumn
        
        Private columnTIPDSNDSCEVTACOCMC As DataColumn
        
        Friend Sub New()
            MyBase.New("T0123086")
            Me.InitClass
        End Sub
        
        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Friend ReadOnly Property CODFRNColumn As DataColumn
            Get
                Return Me.columnCODFRN
            End Get
        End Property
        
        Friend ReadOnly Property TIPDSNDSCBNFColumn As DataColumn
            Get
                Return Me.columnTIPDSNDSCBNF
            End Get
        End Property
        
        Friend ReadOnly Property DATREFLMTColumn As DataColumn
            Get
                Return Me.columnDATREFLMT
            End Get
        End Property
        
        Friend ReadOnly Property CODGDCColumn As DataColumn
            Get
                Return Me.columnCODGDC
            End Get
        End Property
        
        Friend ReadOnly Property NUMSEQLMTColumn As DataColumn
            Get
                Return Me.columnNUMSEQLMT
            End Get
        End Property
        
        Friend ReadOnly Property CODTIPLMTColumn As DataColumn
            Get
                Return Me.columnCODTIPLMT
            End Get
        End Property
        
        Friend ReadOnly Property CODCNTCRDColumn As DataColumn
            Get
                Return Me.columnCODCNTCRD
            End Get
        End Property
        
        Friend ReadOnly Property CODCENCSTCRDColumn As DataColumn
            Get
                Return Me.columnCODCENCSTCRD
            End Get
        End Property
        
        Friend ReadOnly Property CODCNTDEBColumn As DataColumn
            Get
                Return Me.columnCODCNTDEB
            End Get
        End Property
        
        Friend ReadOnly Property CODCENCSTDEBColumn As DataColumn
            Get
                Return Me.columnCODCENCSTDEB
            End Get
        End Property
        
        Friend ReadOnly Property VLRLMTCTBColumn As DataColumn
            Get
                Return Me.columnVLRLMTCTB
            End Get
        End Property
        
        Friend ReadOnly Property DESHSTLMTColumn As DataColumn
            Get
                Return Me.columnDESHSTLMT
            End Get
        End Property
        
        Friend ReadOnly Property DESVARHSTPADColumn As DataColumn
            Get
                Return Me.columnDESVARHSTPAD
            End Get
        End Property
        
        Friend ReadOnly Property DATCTBLMTColumn As DataColumn
            Get
                Return Me.columnDATCTBLMT
            End Get
        End Property
        
        Friend ReadOnly Property NOMACSUSRGRCLMTColumn As DataColumn
            Get
                Return Me.columnNOMACSUSRGRCLMT
            End Get
        End Property
        
        Friend ReadOnly Property CODFILEMPColumn As DataColumn
            Get
                Return Me.columnCODFILEMP
            End Get
        End Property
        
        Friend ReadOnly Property CODPMSColumn As DataColumn
            Get
                Return Me.columnCODPMS
            End Get
        End Property
        
        Friend ReadOnly Property TIPDSNDSCEVTACOCMCColumn As DataColumn
            Get
                Return Me.columnTIPDSNDSCEVTACOCMC
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As T0123086Row
            Get
                Return CType(Me.Rows(index),T0123086Row)
            End Get
        End Property
        
        Public Event T0123086RowChanged As T0123086RowChangeEventHandler
        
        Public Event T0123086RowChanging As T0123086RowChangeEventHandler
        
        Public Event T0123086RowDeleted As T0123086RowChangeEventHandler
        
        Public Event T0123086RowDeleting As T0123086RowChangeEventHandler
        
        Public Overloads Sub AddT0123086Row(ByVal row As T0123086Row)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function AddT0123086Row( _
                    ByVal parentT0100426RowByT0100426T0123086 As T0100426Row,  _
                    ByVal TIPDSNDSCBNF As Decimal,  _
                    ByVal DATREFLMT As Date,  _
                    ByVal CODGDC As String,  _
                    ByVal NUMSEQLMT As Decimal,  _
                    ByVal CODTIPLMT As Decimal,  _
                    ByVal CODCNTCRD As String,  _
                    ByVal CODCENCSTCRD As String,  _
                    ByVal CODCNTDEB As String,  _
                    ByVal CODCENCSTDEB As String,  _
                    ByVal VLRLMTCTB As Decimal,  _
                    ByVal DESHSTLMT As String,  _
                    ByVal DESVARHSTPAD As String,  _
                    ByVal DATCTBLMT As Date,  _
                    ByVal NOMACSUSRGRCLMT As String,  _
                    ByVal CODFILEMP As Decimal,  _
                    ByVal CODPMS As Decimal,  _
                    ByVal TIPDSNDSCEVTACOCMC As Decimal) As T0123086Row
            Dim rowT0123086Row As T0123086Row = CType(Me.NewRow,T0123086Row)
            rowT0123086Row.ItemArray = New Object() {parentT0100426RowByT0100426T0123086(0), TIPDSNDSCBNF, DATREFLMT, CODGDC, NUMSEQLMT, CODTIPLMT, CODCNTCRD, CODCENCSTCRD, CODCNTDEB, CODCENCSTDEB, VLRLMTCTB, DESHSTLMT, DESVARHSTPAD, DATCTBLMT, NOMACSUSRGRCLMT, CODFILEMP, CODPMS, TIPDSNDSCEVTACOCMC}
            Me.Rows.Add(rowT0123086Row)
            Return rowT0123086Row
        End Function
        
        Public Function FindByCODFRNTIPDSNDSCBNFDATREFLMTCODGDCNUMSEQLMT(ByVal CODFRN As Decimal, ByVal TIPDSNDSCBNF As Decimal, ByVal DATREFLMT As Date, ByVal CODGDC As String, ByVal NUMSEQLMT As Decimal) As T0123086Row
            Return CType(Me.Rows.Find(New Object() {CODFRN, TIPDSNDSCBNF, DATREFLMT, CODGDC, NUMSEQLMT}),T0123086Row)
        End Function
        
        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As DataTable
            Dim cln As T0123086DataTable = CType(MyBase.Clone,T0123086DataTable)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function CreateInstance() As DataTable
            Return New T0123086DataTable
        End Function
        
        Friend Sub InitVars()
            Me.columnCODFRN = Me.Columns("CODFRN")
            Me.columnTIPDSNDSCBNF = Me.Columns("TIPDSNDSCBNF")
            Me.columnDATREFLMT = Me.Columns("DATREFLMT")
            Me.columnCODGDC = Me.Columns("CODGDC")
            Me.columnNUMSEQLMT = Me.Columns("NUMSEQLMT")
            Me.columnCODTIPLMT = Me.Columns("CODTIPLMT")
            Me.columnCODCNTCRD = Me.Columns("CODCNTCRD")
            Me.columnCODCENCSTCRD = Me.Columns("CODCENCSTCRD")
            Me.columnCODCNTDEB = Me.Columns("CODCNTDEB")
            Me.columnCODCENCSTDEB = Me.Columns("CODCENCSTDEB")
            Me.columnVLRLMTCTB = Me.Columns("VLRLMTCTB")
            Me.columnDESHSTLMT = Me.Columns("DESHSTLMT")
            Me.columnDESVARHSTPAD = Me.Columns("DESVARHSTPAD")
            Me.columnDATCTBLMT = Me.Columns("DATCTBLMT")
            Me.columnNOMACSUSRGRCLMT = Me.Columns("NOMACSUSRGRCLMT")
            Me.columnCODFILEMP = Me.Columns("CODFILEMP")
            Me.columnCODPMS = Me.Columns("CODPMS")
            Me.columnTIPDSNDSCEVTACOCMC = Me.Columns("TIPDSNDSCEVTACOCMC")
        End Sub
        
        Private Sub InitClass()
            Me.columnCODFRN = New DataColumn("CODFRN", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCODFRN)
            Me.columnTIPDSNDSCBNF = New DataColumn("TIPDSNDSCBNF", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnTIPDSNDSCBNF)
            Me.columnDATREFLMT = New DataColumn("DATREFLMT", GetType(System.DateTime), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnDATREFLMT)
            Me.columnCODGDC = New DataColumn("CODGDC", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCODGDC)
            Me.columnNUMSEQLMT = New DataColumn("NUMSEQLMT", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnNUMSEQLMT)
            Me.columnCODTIPLMT = New DataColumn("CODTIPLMT", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCODTIPLMT)
            Me.columnCODCNTCRD = New DataColumn("CODCNTCRD", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCODCNTCRD)
            Me.columnCODCENCSTCRD = New DataColumn("CODCENCSTCRD", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCODCENCSTCRD)
            Me.columnCODCNTDEB = New DataColumn("CODCNTDEB", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCODCNTDEB)
            Me.columnCODCENCSTDEB = New DataColumn("CODCENCSTDEB", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCODCENCSTDEB)
            Me.columnVLRLMTCTB = New DataColumn("VLRLMTCTB", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnVLRLMTCTB)
            Me.columnDESHSTLMT = New DataColumn("DESHSTLMT", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnDESHSTLMT)
            Me.columnDESVARHSTPAD = New DataColumn("DESVARHSTPAD", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnDESVARHSTPAD)
            Me.columnDATCTBLMT = New DataColumn("DATCTBLMT", GetType(System.DateTime), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnDATCTBLMT)
            Me.columnNOMACSUSRGRCLMT = New DataColumn("NOMACSUSRGRCLMT", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnNOMACSUSRGRCLMT)
            Me.columnCODFILEMP = New DataColumn("CODFILEMP", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCODFILEMP)
            Me.columnCODPMS = New DataColumn("CODPMS", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCODPMS)
            Me.columnTIPDSNDSCEVTACOCMC = New DataColumn("TIPDSNDSCEVTACOCMC", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnTIPDSNDSCEVTACOCMC)
            Me.Constraints.Add(New UniqueConstraint("DatasetContaCorrenteFornecedorKey1", New DataColumn() {Me.columnCODFRN, Me.columnTIPDSNDSCBNF, Me.columnDATREFLMT, Me.columnCODGDC, Me.columnNUMSEQLMT}, true))
            Me.columnCODFRN.AllowDBNull = false
            Me.columnTIPDSNDSCBNF.AllowDBNull = false
            Me.columnDATREFLMT.AllowDBNull = false
            Me.columnCODGDC.AllowDBNull = false
            Me.columnNUMSEQLMT.AllowDBNull = false
            Me.columnCODTIPLMT.AllowDBNull = false
            Me.columnCODCNTCRD.AllowDBNull = false
            Me.columnCODCENCSTCRD.AllowDBNull = false
            Me.columnCODCNTDEB.AllowDBNull = false
            Me.columnCODCENCSTDEB.AllowDBNull = false
            Me.columnVLRLMTCTB.AllowDBNull = false
            Me.columnDESHSTLMT.AllowDBNull = false
            Me.columnDESVARHSTPAD.AllowDBNull = false
            Me.columnNOMACSUSRGRCLMT.AllowDBNull = false
        End Sub
        
        Public Function NewT0123086Row() As T0123086Row
            Return CType(Me.NewRow,T0123086Row)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New T0123086Row(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(T0123086Row)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.T0123086RowChangedEvent) Is Nothing) Then
                RaiseEvent T0123086RowChanged(Me, New T0123086RowChangeEvent(CType(e.Row,T0123086Row), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.T0123086RowChangingEvent) Is Nothing) Then
                RaiseEvent T0123086RowChanging(Me, New T0123086RowChangeEvent(CType(e.Row,T0123086Row), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.T0123086RowDeletedEvent) Is Nothing) Then
                RaiseEvent T0123086RowDeleted(Me, New T0123086RowChangeEvent(CType(e.Row,T0123086Row), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.T0123086RowDeletingEvent) Is Nothing) Then
                RaiseEvent T0123086RowDeleting(Me, New T0123086RowChangeEvent(CType(e.Row,T0123086Row), e.Action))
            End If
        End Sub
        
        Public Sub RemoveT0123086Row(ByVal row As T0123086Row)
            Me.Rows.Remove(row)
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class T0123086Row
        Inherits DataRow
        
        Private tableT0123086 As T0123086DataTable
        
        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tableT0123086 = CType(Me.Table,T0123086DataTable)
        End Sub
        
        Public Property CODFRN As Decimal
            Get
                Return CType(Me(Me.tableT0123086.CODFRNColumn),Decimal)
            End Get
            Set
                Me(Me.tableT0123086.CODFRNColumn) = value
            End Set
        End Property
        
        Public Property TIPDSNDSCBNF As Decimal
            Get
                Return CType(Me(Me.tableT0123086.TIPDSNDSCBNFColumn),Decimal)
            End Get
            Set
                Me(Me.tableT0123086.TIPDSNDSCBNFColumn) = value
            End Set
        End Property
        
        Public Property DATREFLMT As Date
            Get
                Return CType(Me(Me.tableT0123086.DATREFLMTColumn),Date)
            End Get
            Set
                Me(Me.tableT0123086.DATREFLMTColumn) = value
            End Set
        End Property
        
        Public Property CODGDC As String
            Get
                Return CType(Me(Me.tableT0123086.CODGDCColumn),String)
            End Get
            Set
                Me(Me.tableT0123086.CODGDCColumn) = value
            End Set
        End Property
        
        Public Property NUMSEQLMT As Decimal
            Get
                Return CType(Me(Me.tableT0123086.NUMSEQLMTColumn),Decimal)
            End Get
            Set
                Me(Me.tableT0123086.NUMSEQLMTColumn) = value
            End Set
        End Property
        
        Public Property CODTIPLMT As Decimal
            Get
                Return CType(Me(Me.tableT0123086.CODTIPLMTColumn),Decimal)
            End Get
            Set
                Me(Me.tableT0123086.CODTIPLMTColumn) = value
            End Set
        End Property
        
        Public Property CODCNTCRD As String
            Get
                Return CType(Me(Me.tableT0123086.CODCNTCRDColumn),String)
            End Get
            Set
                Me(Me.tableT0123086.CODCNTCRDColumn) = value
            End Set
        End Property
        
        Public Property CODCENCSTCRD As String
            Get
                Return CType(Me(Me.tableT0123086.CODCENCSTCRDColumn),String)
            End Get
            Set
                Me(Me.tableT0123086.CODCENCSTCRDColumn) = value
            End Set
        End Property
        
        Public Property CODCNTDEB As String
            Get
                Return CType(Me(Me.tableT0123086.CODCNTDEBColumn),String)
            End Get
            Set
                Me(Me.tableT0123086.CODCNTDEBColumn) = value
            End Set
        End Property
        
        Public Property CODCENCSTDEB As String
            Get
                Return CType(Me(Me.tableT0123086.CODCENCSTDEBColumn),String)
            End Get
            Set
                Me(Me.tableT0123086.CODCENCSTDEBColumn) = value
            End Set
        End Property
        
        Public Property VLRLMTCTB As Decimal
            Get
                Return CType(Me(Me.tableT0123086.VLRLMTCTBColumn),Decimal)
            End Get
            Set
                Me(Me.tableT0123086.VLRLMTCTBColumn) = value
            End Set
        End Property
        
        Public Property DESHSTLMT As String
            Get
                Return CType(Me(Me.tableT0123086.DESHSTLMTColumn),String)
            End Get
            Set
                Me(Me.tableT0123086.DESHSTLMTColumn) = value
            End Set
        End Property
        
        Public Property DESVARHSTPAD As String
            Get
                Return CType(Me(Me.tableT0123086.DESVARHSTPADColumn),String)
            End Get
            Set
                Me(Me.tableT0123086.DESVARHSTPADColumn) = value
            End Set
        End Property
        
        Public Property DATCTBLMT As Date
            Get
                Try 
                    Return CType(Me(Me.tableT0123086.DATCTBLMTColumn),Date)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableT0123086.DATCTBLMTColumn) = value
            End Set
        End Property
        
        Public Property NOMACSUSRGRCLMT As String
            Get
                Return CType(Me(Me.tableT0123086.NOMACSUSRGRCLMTColumn),String)
            End Get
            Set
                Me(Me.tableT0123086.NOMACSUSRGRCLMTColumn) = value
            End Set
        End Property
        
        Public Property CODFILEMP As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableT0123086.CODFILEMPColumn),Decimal)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableT0123086.CODFILEMPColumn) = value
            End Set
        End Property
        
        Public Property CODPMS As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableT0123086.CODPMSColumn),Decimal)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableT0123086.CODPMSColumn) = value
            End Set
        End Property
        
        Public Property TIPDSNDSCEVTACOCMC As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableT0123086.TIPDSNDSCEVTACOCMCColumn),Decimal)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableT0123086.TIPDSNDSCEVTACOCMCColumn) = value
            End Set
        End Property
        
        Public Property T0100426Row As T0100426Row
            Get
                Return CType(Me.GetParentRow(Me.Table.ParentRelations("T0100426T0123086")),T0100426Row)
            End Get
            Set
                Me.SetParentRow(value, Me.Table.ParentRelations("T0100426T0123086"))
            End Set
        End Property
        
        Public Function IsDATCTBLMTNull() As Boolean
            Return Me.IsNull(Me.tableT0123086.DATCTBLMTColumn)
        End Function
        
        Public Sub SetDATCTBLMTNull()
            Me(Me.tableT0123086.DATCTBLMTColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsCODFILEMPNull() As Boolean
            Return Me.IsNull(Me.tableT0123086.CODFILEMPColumn)
        End Function
        
        Public Sub SetCODFILEMPNull()
            Me(Me.tableT0123086.CODFILEMPColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsCODPMSNull() As Boolean
            Return Me.IsNull(Me.tableT0123086.CODPMSColumn)
        End Function
        
        Public Sub SetCODPMSNull()
            Me(Me.tableT0123086.CODPMSColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsTIPDSNDSCEVTACOCMCNull() As Boolean
            Return Me.IsNull(Me.tableT0123086.TIPDSNDSCEVTACOCMCColumn)
        End Function
        
        Public Sub SetTIPDSNDSCEVTACOCMCNull()
            Me(Me.tableT0123086.TIPDSNDSCEVTACOCMCColumn) = System.Convert.DBNull
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class T0123086RowChangeEvent
        Inherits EventArgs
        
        Private eventRow As T0123086Row
        
        Private eventAction As DataRowAction
        
        Public Sub New(ByVal row As T0123086Row, ByVal action As DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row As T0123086Row
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class T0100426DataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable
        
        Private columnCODFRN As DataColumn
        
        Private columnNOMFRN As DataColumn
        
        Friend Sub New()
            MyBase.New("T0100426")
            Me.InitClass
        End Sub
        
        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Friend ReadOnly Property CODFRNColumn As DataColumn
            Get
                Return Me.columnCODFRN
            End Get
        End Property
        
        Friend ReadOnly Property NOMFRNColumn As DataColumn
            Get
                Return Me.columnNOMFRN
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As T0100426Row
            Get
                Return CType(Me.Rows(index),T0100426Row)
            End Get
        End Property
        
        Public Event T0100426RowChanged As T0100426RowChangeEventHandler
        
        Public Event T0100426RowChanging As T0100426RowChangeEventHandler
        
        Public Event T0100426RowDeleted As T0100426RowChangeEventHandler
        
        Public Event T0100426RowDeleting As T0100426RowChangeEventHandler
        
        Public Overloads Sub AddT0100426Row(ByVal row As T0100426Row)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function AddT0100426Row(ByVal CODFRN As Decimal, ByVal NOMFRN As String) As T0100426Row
            Dim rowT0100426Row As T0100426Row = CType(Me.NewRow,T0100426Row)
            rowT0100426Row.ItemArray = New Object() {CODFRN, NOMFRN}
            Me.Rows.Add(rowT0100426Row)
            Return rowT0100426Row
        End Function
        
        Public Function FindByCODFRN(ByVal CODFRN As Decimal) As T0100426Row
            Return CType(Me.Rows.Find(New Object() {CODFRN}),T0100426Row)
        End Function
        
        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As DataTable
            Dim cln As T0100426DataTable = CType(MyBase.Clone,T0100426DataTable)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function CreateInstance() As DataTable
            Return New T0100426DataTable
        End Function
        
        Friend Sub InitVars()
            Me.columnCODFRN = Me.Columns("CODFRN")
            Me.columnNOMFRN = Me.Columns("NOMFRN")
        End Sub
        
        Private Sub InitClass()
            Me.columnCODFRN = New DataColumn("CODFRN", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCODFRN)
            Me.columnNOMFRN = New DataColumn("NOMFRN", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnNOMFRN)
            Me.Constraints.Add(New UniqueConstraint("DatasetContaCorrenteFornecedorKey2", New DataColumn() {Me.columnCODFRN}, true))
            Me.columnCODFRN.AllowDBNull = false
            Me.columnCODFRN.Unique = true
            Me.columnNOMFRN.AllowDBNull = false
        End Sub
        
        Public Function NewT0100426Row() As T0100426Row
            Return CType(Me.NewRow,T0100426Row)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New T0100426Row(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(T0100426Row)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.T0100426RowChangedEvent) Is Nothing) Then
                RaiseEvent T0100426RowChanged(Me, New T0100426RowChangeEvent(CType(e.Row,T0100426Row), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.T0100426RowChangingEvent) Is Nothing) Then
                RaiseEvent T0100426RowChanging(Me, New T0100426RowChangeEvent(CType(e.Row,T0100426Row), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.T0100426RowDeletedEvent) Is Nothing) Then
                RaiseEvent T0100426RowDeleted(Me, New T0100426RowChangeEvent(CType(e.Row,T0100426Row), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.T0100426RowDeletingEvent) Is Nothing) Then
                RaiseEvent T0100426RowDeleting(Me, New T0100426RowChangeEvent(CType(e.Row,T0100426Row), e.Action))
            End If
        End Sub
        
        Public Sub RemoveT0100426Row(ByVal row As T0100426Row)
            Me.Rows.Remove(row)
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class T0100426Row
        Inherits DataRow
        
        Private tableT0100426 As T0100426DataTable
        
        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tableT0100426 = CType(Me.Table,T0100426DataTable)
        End Sub
        
        Public Property CODFRN As Decimal
            Get
                Return CType(Me(Me.tableT0100426.CODFRNColumn),Decimal)
            End Get
            Set
                Me(Me.tableT0100426.CODFRNColumn) = value
            End Set
        End Property
        
        Public Property NOMFRN As String
            Get
                Return CType(Me(Me.tableT0100426.NOMFRNColumn),String)
            End Get
            Set
                Me(Me.tableT0100426.NOMFRNColumn) = value
            End Set
        End Property
        
        Public Function GetT0123086Rows() As T0123086Row()
            Return CType(Me.GetChildRows(Me.Table.ChildRelations("T0100426T0123086")),T0123086Row())
        End Function
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class T0100426RowChangeEvent
        Inherits EventArgs
        
        Private eventRow As T0100426Row
        
        Private eventAction As DataRowAction
        
        Public Sub New(ByVal row As T0100426Row, ByVal action As DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row As T0100426Row
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
