'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2407
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Data
Imports System.Runtime.Serialization
Imports System.Xml


<Serializable(), _
 System.ComponentModel.DesignerCategoryAttribute("code"), _
 System.Diagnostics.DebuggerStepThrough(), _
 System.ComponentModel.ToolboxItem(True)> _
Public Class DatasetDiretoriaCelulas
    Inherits DataSet

    Private tableT0123183 As T0123183DataTable

    Public Sub New()
        MyBase.New()
        Me.InitClass()
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub

    Protected Sub New(ByVal info As SerializationInfo, ByVal context As StreamingContext)
        MyBase.New()
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(System.String)), String)
        If (Not (strSchema) Is Nothing) Then
            Dim ds As DataSet = New DataSet
            ds.ReadXmlSchema(New XmlTextReader(New System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("T0123183")) Is Nothing) Then
                Me.Tables.Add(New T0123183DataTable(ds.Tables("T0123183")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, False, System.Data.MissingSchemaAction.Add)
            Me.InitVars()
        Else
            Me.InitClass()
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub

    <System.ComponentModel.Browsable(False), _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)> _
    Public ReadOnly Property T0123183() As T0123183DataTable
        Get
            Return Me.tableT0123183
        End Get
    End Property

    Public Overrides Function Clone() As DataSet
        Dim cln As DatasetDiretoriaCelulas = CType(MyBase.Clone, DatasetDiretoriaCelulas)
        cln.InitVars()
        Return cln
    End Function

    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return False
    End Function

    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return False
    End Function

    Protected Overrides Sub ReadXmlSerializable(ByVal reader As XmlReader)
        Me.Reset()
        Dim ds As DataSet = New DataSet
        ds.ReadXml(reader)
        If (Not (ds.Tables("T0123183")) Is Nothing) Then
            Me.Tables.Add(New T0123183DataTable(ds.Tables("T0123183")))
        End If
        Me.DataSetName = ds.DataSetName
        Me.Prefix = ds.Prefix
        Me.Namespace = ds.Namespace
        Me.Locale = ds.Locale
        Me.CaseSensitive = ds.CaseSensitive
        Me.EnforceConstraints = ds.EnforceConstraints
        Me.Merge(ds, False, System.Data.MissingSchemaAction.Add)
        Me.InitVars()
    End Sub

    Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
        Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
        Me.WriteXmlSchema(New XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return System.Xml.Schema.XmlSchema.Read(New XmlTextReader(stream), Nothing)
    End Function

    Friend Sub InitVars()
        Me.tableT0123183 = CType(Me.Tables("T0123183"), T0123183DataTable)
        If (Not (Me.tableT0123183) Is Nothing) Then
            Me.tableT0123183.InitVars()
        End If
    End Sub

    Private Sub InitClass()
        Me.DataSetName = "DatasetDiretoriaCelulas"
        Me.Prefix = ""
        Me.Namespace = "http://tempuri.org/DatasetDiretoriaCelulas.xsd"
        Me.Locale = New System.Globalization.CultureInfo("en-US")
        Me.CaseSensitive = False
        Me.EnforceConstraints = True
        Me.tableT0123183 = New T0123183DataTable
        Me.Tables.Add(Me.tableT0123183)
    End Sub

    Private Function ShouldSerializeT0123183() As Boolean
        Return False
    End Function

    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars()
        End If
    End Sub

    Public Delegate Sub T0123183RowChangeEventHandler(ByVal sender As Object, ByVal e As T0123183RowChangeEvent)

    <System.Diagnostics.DebuggerStepThrough()> _
    Public Class T0123183DataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable

        Private columnCODDRTCMP As DataColumn

        Private columnCODCPR As DataColumn

        Private columnDESDRTCMP As DataColumn

        Private columnCODUNDESRNGC As DataColumn

        Private columnCODDRT As DataColumn

        Friend Sub New()
            MyBase.New("T0123183")
            Me.InitClass()
        End Sub

        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub

        <System.ComponentModel.Browsable(False)> _
        Public ReadOnly Property Count() As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property

        Friend ReadOnly Property CODDRTCMPColumn() As DataColumn
            Get
                Return Me.columnCODDRTCMP
            End Get
        End Property

        Friend ReadOnly Property CODCPRColumn() As DataColumn
            Get
                Return Me.columnCODCPR
            End Get
        End Property

        Friend ReadOnly Property DESDRTCMPColumn() As DataColumn
            Get
                Return Me.columnDESDRTCMP
            End Get
        End Property

        Friend ReadOnly Property CODUNDESRNGCColumn() As DataColumn
            Get
                Return Me.columnCODUNDESRNGC
            End Get
        End Property

        Friend ReadOnly Property CODDRTColumn() As DataColumn
            Get
                Return Me.columnCODDRT
            End Get
        End Property

        Default Public ReadOnly Property Item(ByVal index As Integer) As T0123183Row
            Get
                Return CType(Me.Rows(index), T0123183Row)
            End Get
        End Property

        Public Event T0123183RowChanged As T0123183RowChangeEventHandler

        Public Event T0123183RowChanging As T0123183RowChangeEventHandler

        Public Event T0123183RowDeleted As T0123183RowChangeEventHandler

        Public Event T0123183RowDeleting As T0123183RowChangeEventHandler

        Public Overloads Sub AddT0123183Row(ByVal row As T0123183Row)
            Me.Rows.Add(row)
        End Sub

        Public Overloads Function AddT0123183Row(ByVal CODDRTCMP As Decimal, ByVal CODCPR As Decimal, ByVal DESDRTCMP As String, ByVal CODUNDESRNGC As Decimal, ByVal CODDRT As Decimal) As T0123183Row
            Dim rowT0123183Row As T0123183Row = CType(Me.NewRow, T0123183Row)
            rowT0123183Row.ItemArray = New Object() {CODDRTCMP, CODCPR, DESDRTCMP, CODUNDESRNGC, CODDRT}
            Me.Rows.Add(rowT0123183Row)
            Return rowT0123183Row
        End Function

        Public Function FindByCODDRTCMP(ByVal CODDRTCMP As Decimal) As T0123183Row
            Return CType(Me.Rows.Find(New Object() {CODDRTCMP}), T0123183Row)
        End Function

        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function

        Public Overrides Function Clone() As DataTable
            Dim cln As T0123183DataTable = CType(MyBase.Clone, T0123183DataTable)
            cln.InitVars()
            Return cln
        End Function

        Protected Overrides Function CreateInstance() As DataTable
            Return New T0123183DataTable
        End Function

        Friend Sub InitVars()
            Me.columnCODDRTCMP = Me.Columns("CODDRTCMP")
            Me.columnCODCPR = Me.Columns("CODCPR")
            Me.columnDESDRTCMP = Me.Columns("DESDRTCMP")
            Me.columnCODUNDESRNGC = Me.Columns("CODUNDESRNGC")
            Me.columnCODDRT = Me.Columns("CODDRT")
        End Sub

        Private Sub InitClass()
            Me.columnCODDRTCMP = New DataColumn("CODDRTCMP", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCODDRTCMP)
            Me.columnCODCPR = New DataColumn("CODCPR", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCODCPR)
            Me.columnDESDRTCMP = New DataColumn("DESDRTCMP", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnDESDRTCMP)
            Me.columnCODUNDESRNGC = New DataColumn("CODUNDESRNGC", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCODUNDESRNGC)
            Me.columnCODDRT = New DataColumn("CODDRT", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCODDRT)
            Me.Constraints.Add(New UniqueConstraint("DatasetDiretoriaCelulasKey1", New DataColumn() {Me.columnCODDRTCMP}, True))
            Me.columnCODDRTCMP.AllowDBNull = False
            Me.columnCODDRTCMP.Unique = True
            Me.columnCODCPR.AllowDBNull = False
            Me.columnDESDRTCMP.AllowDBNull = False
            Me.columnCODUNDESRNGC.AllowDBNull = False
            Me.columnCODDRT.AllowDBNull = False
        End Sub

        Public Function NewT0123183Row() As T0123183Row
            Return CType(Me.NewRow, T0123183Row)
        End Function

        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New T0123183Row(builder)
        End Function

        Protected Overrides Function GetRowType() As System.Type
            Return GetType(T0123183Row)
        End Function

        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.T0123183RowChangedEvent) Is Nothing) Then
                RaiseEvent T0123183RowChanged(Me, New T0123183RowChangeEvent(CType(e.Row, T0123183Row), e.Action))
            End If
        End Sub

        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.T0123183RowChangingEvent) Is Nothing) Then
                RaiseEvent T0123183RowChanging(Me, New T0123183RowChangeEvent(CType(e.Row, T0123183Row), e.Action))
            End If
        End Sub

        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.T0123183RowDeletedEvent) Is Nothing) Then
                RaiseEvent T0123183RowDeleted(Me, New T0123183RowChangeEvent(CType(e.Row, T0123183Row), e.Action))
            End If
        End Sub

        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.T0123183RowDeletingEvent) Is Nothing) Then
                RaiseEvent T0123183RowDeleting(Me, New T0123183RowChangeEvent(CType(e.Row, T0123183Row), e.Action))
            End If
        End Sub

        Public Sub RemoveT0123183Row(ByVal row As T0123183Row)
            Me.Rows.Remove(row)
        End Sub
    End Class

    <System.Diagnostics.DebuggerStepThrough()> _
    Public Class T0123183Row
        Inherits DataRow

        Private tableT0123183 As T0123183DataTable

        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tableT0123183 = CType(Me.Table, T0123183DataTable)
        End Sub

        Public Property CODDRTCMP() As Decimal
            Get
                Return CType(Me(Me.tableT0123183.CODDRTCMPColumn), Decimal)
            End Get
            Set(ByVal Value As Decimal)
                Me(Me.tableT0123183.CODDRTCMPColumn) = Value
            End Set
        End Property

        Public Property CODCPR() As Decimal
            Get
                Return CType(Me(Me.tableT0123183.CODCPRColumn), Decimal)
            End Get
            Set(ByVal Value As Decimal)
                Me(Me.tableT0123183.CODCPRColumn) = Value
            End Set
        End Property

        Public Property DESDRTCMP() As String
            Get
                Return CType(Me(Me.tableT0123183.DESDRTCMPColumn), String)
            End Get
            Set(ByVal Value As String)
                Me(Me.tableT0123183.DESDRTCMPColumn) = Value
            End Set
        End Property

        Public Property CODUNDESRNGC() As Decimal
            Get
                Return CType(Me(Me.tableT0123183.CODUNDESRNGCColumn), Decimal)
            End Get
            Set(ByVal Value As Decimal)
                Me(Me.tableT0123183.CODUNDESRNGCColumn) = Value
            End Set
        End Property

        Public Property CODDRT() As Decimal
            Get
                Return CType(Me(Me.tableT0123183.CODDRTColumn), Decimal)
            End Get
            Set(ByVal Value As Decimal)
                Me(Me.tableT0123183.CODDRTColumn) = Value
            End Set
        End Property
    End Class

    <System.Diagnostics.DebuggerStepThrough()> _
    Public Class T0123183RowChangeEvent
        Inherits EventArgs

        Private eventRow As T0123183Row

        Private eventAction As DataRowAction

        Public Sub New(ByVal row As T0123183Row, ByVal action As DataRowAction)
            MyBase.New()
            Me.eventRow = row
            Me.eventAction = action
        End Sub

        Public ReadOnly Property Row() As T0123183Row
            Get
                Return Me.eventRow
            End Get
        End Property

        Public ReadOnly Property Action() As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
