'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2407
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Data
Imports System.Runtime.Serialization
Imports System.Xml


<Serializable(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Diagnostics.DebuggerStepThrough(),  _
 System.ComponentModel.ToolboxItem(true)>  _
Public Class DatasetAcordoACancelarEmFluxoCancelamentoAcordo
    Inherits DataSet
    
    Private tableT0118066Pesquisa As T0118066PesquisaDataTable
    
    Public Sub New()
        MyBase.New
        Me.InitClass
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    Protected Sub New(ByVal info As SerializationInfo, ByVal context As StreamingContext)
        MyBase.New
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(System.String)),String)
        If (Not (strSchema) Is Nothing) Then
            Dim ds As DataSet = New DataSet
            ds.ReadXmlSchema(New XmlTextReader(New System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("T0118066Pesquisa")) Is Nothing) Then
                Me.Tables.Add(New T0118066PesquisaDataTable(ds.Tables("T0118066Pesquisa")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.InitClass
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property T0118066Pesquisa As T0118066PesquisaDataTable
        Get
            Return Me.tableT0118066Pesquisa
        End Get
    End Property
    
    Public Overrides Function Clone() As DataSet
        Dim cln As DatasetAcordoACancelarEmFluxoCancelamentoAcordo = CType(MyBase.Clone,DatasetAcordoACancelarEmFluxoCancelamentoAcordo)
        cln.InitVars
        Return cln
    End Function
    
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As XmlReader)
        Me.Reset
        Dim ds As DataSet = New DataSet
        ds.ReadXml(reader)
        If (Not (ds.Tables("T0118066Pesquisa")) Is Nothing) Then
            Me.Tables.Add(New T0118066PesquisaDataTable(ds.Tables("T0118066Pesquisa")))
        End If
        Me.DataSetName = ds.DataSetName
        Me.Prefix = ds.Prefix
        Me.Namespace = ds.Namespace
        Me.Locale = ds.Locale
        Me.CaseSensitive = ds.CaseSensitive
        Me.EnforceConstraints = ds.EnforceConstraints
        Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
        Me.InitVars
    End Sub
    
    Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
        Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
        Me.WriteXmlSchema(New XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return System.Xml.Schema.XmlSchema.Read(New XmlTextReader(stream), Nothing)
    End Function
    
    Friend Sub InitVars()
        Me.tableT0118066Pesquisa = CType(Me.Tables("T0118066Pesquisa"),T0118066PesquisaDataTable)
        If (Not (Me.tableT0118066Pesquisa) Is Nothing) Then
            Me.tableT0118066Pesquisa.InitVars
        End If
    End Sub
    
    Private Sub InitClass()
        Me.DataSetName = "DatasetAcordoACancelarEmFluxoCancelamentoAcordo"
        Me.Prefix = ""
        Me.Namespace = "http://tempuri.org/DatasetAcordoACancelarEmFluxoCancelamentoAcordo.xsd"
        Me.Locale = New System.Globalization.CultureInfo("en-US")
        Me.CaseSensitive = false
        Me.EnforceConstraints = true
        Me.tableT0118066Pesquisa = New T0118066PesquisaDataTable
        Me.Tables.Add(Me.tableT0118066Pesquisa)
    End Sub
    
    Private Function ShouldSerializeT0118066Pesquisa() As Boolean
        Return false
    End Function
    
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    Public Delegate Sub T0118066PesquisaRowChangeEventHandler(ByVal sender As Object, ByVal e As T0118066PesquisaRowChangeEvent)
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class T0118066PesquisaDataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable
        
        Private columnCODPMS As DataColumn
        
        Private columnDATNGCPMS As DataColumn
        
        Private columnDATPRVRCBPMS As DataColumn
        
        Private columnDESDSNDSCBNF As DataColumn
        
        Private columnVLRNGCPMS As DataColumn
        
        Private columnVLRPGOPMS As DataColumn
        
        Private columnCODEMP As DataColumn
        
        Private columnCODFILEMP As DataColumn
        
        Private columnTIPDSNDSCBNF As DataColumn
        
        Private columnTIPFRMDSCBNF As DataColumn
        
        Private columnCODFRN As DataColumn
        
        Private columnNUMPEDCNCACOCMC As DataColumn
        
        Private columnVLRSLDPMSFRN As DataColumn
        
        Private columnVLRDSPPMS As DataColumn
        
        Private columnFLGSITNGCDUP As DataColumn
        
        Private columnDESFRMDSCBNF As DataColumn
        
        Friend Sub New()
            MyBase.New("T0118066Pesquisa")
            Me.InitClass
        End Sub
        
        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Friend ReadOnly Property CODPMSColumn As DataColumn
            Get
                Return Me.columnCODPMS
            End Get
        End Property
        
        Friend ReadOnly Property DATNGCPMSColumn As DataColumn
            Get
                Return Me.columnDATNGCPMS
            End Get
        End Property
        
        Friend ReadOnly Property DATPRVRCBPMSColumn As DataColumn
            Get
                Return Me.columnDATPRVRCBPMS
            End Get
        End Property
        
        Friend ReadOnly Property DESDSNDSCBNFColumn As DataColumn
            Get
                Return Me.columnDESDSNDSCBNF
            End Get
        End Property
        
        Friend ReadOnly Property VLRNGCPMSColumn As DataColumn
            Get
                Return Me.columnVLRNGCPMS
            End Get
        End Property
        
        Friend ReadOnly Property VLRPGOPMSColumn As DataColumn
            Get
                Return Me.columnVLRPGOPMS
            End Get
        End Property
        
        Friend ReadOnly Property CODEMPColumn As DataColumn
            Get
                Return Me.columnCODEMP
            End Get
        End Property
        
        Friend ReadOnly Property CODFILEMPColumn As DataColumn
            Get
                Return Me.columnCODFILEMP
            End Get
        End Property
        
        Friend ReadOnly Property TIPDSNDSCBNFColumn As DataColumn
            Get
                Return Me.columnTIPDSNDSCBNF
            End Get
        End Property
        
        Friend ReadOnly Property TIPFRMDSCBNFColumn As DataColumn
            Get
                Return Me.columnTIPFRMDSCBNF
            End Get
        End Property
        
        Friend ReadOnly Property CODFRNColumn As DataColumn
            Get
                Return Me.columnCODFRN
            End Get
        End Property
        
        Friend ReadOnly Property NUMPEDCNCACOCMCColumn As DataColumn
            Get
                Return Me.columnNUMPEDCNCACOCMC
            End Get
        End Property
        
        Friend ReadOnly Property VLRSLDPMSFRNColumn As DataColumn
            Get
                Return Me.columnVLRSLDPMSFRN
            End Get
        End Property
        
        Friend ReadOnly Property VLRDSPPMSColumn As DataColumn
            Get
                Return Me.columnVLRDSPPMS
            End Get
        End Property
        
        Friend ReadOnly Property FLGSITNGCDUPColumn As DataColumn
            Get
                Return Me.columnFLGSITNGCDUP
            End Get
        End Property
        
        Friend ReadOnly Property DESFRMDSCBNFColumn As DataColumn
            Get
                Return Me.columnDESFRMDSCBNF
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As T0118066PesquisaRow
            Get
                Return CType(Me.Rows(index),T0118066PesquisaRow)
            End Get
        End Property
        
        Public Event T0118066PesquisaRowChanged As T0118066PesquisaRowChangeEventHandler
        
        Public Event T0118066PesquisaRowChanging As T0118066PesquisaRowChangeEventHandler
        
        Public Event T0118066PesquisaRowDeleted As T0118066PesquisaRowChangeEventHandler
        
        Public Event T0118066PesquisaRowDeleting As T0118066PesquisaRowChangeEventHandler
        
        Public Overloads Sub AddT0118066PesquisaRow(ByVal row As T0118066PesquisaRow)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function AddT0118066PesquisaRow( _
                    ByVal CODPMS As Decimal,  _
                    ByVal DATNGCPMS As Date,  _
                    ByVal DATPRVRCBPMS As Date,  _
                    ByVal DESDSNDSCBNF As String,  _
                    ByVal VLRNGCPMS As Decimal,  _
                    ByVal VLRPGOPMS As Decimal,  _
                    ByVal CODEMP As Decimal,  _
                    ByVal CODFILEMP As Decimal,  _
                    ByVal TIPDSNDSCBNF As Decimal,  _
                    ByVal TIPFRMDSCBNF As Decimal,  _
                    ByVal CODFRN As Decimal,  _
                    ByVal NUMPEDCNCACOCMC As Decimal,  _
                    ByVal VLRSLDPMSFRN As Decimal,  _
                    ByVal VLRDSPPMS As Decimal,  _
                    ByVal FLGSITNGCDUP As String,  _
                    ByVal DESFRMDSCBNF As String) As T0118066PesquisaRow
            Dim rowT0118066PesquisaRow As T0118066PesquisaRow = CType(Me.NewRow,T0118066PesquisaRow)
            rowT0118066PesquisaRow.ItemArray = New Object() {CODPMS, DATNGCPMS, DATPRVRCBPMS, DESDSNDSCBNF, VLRNGCPMS, VLRPGOPMS, CODEMP, CODFILEMP, TIPDSNDSCBNF, TIPFRMDSCBNF, CODFRN, NUMPEDCNCACOCMC, VLRSLDPMSFRN, VLRDSPPMS, FLGSITNGCDUP, DESFRMDSCBNF}
            Me.Rows.Add(rowT0118066PesquisaRow)
            Return rowT0118066PesquisaRow
        End Function
        
        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As DataTable
            Dim cln As T0118066PesquisaDataTable = CType(MyBase.Clone,T0118066PesquisaDataTable)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function CreateInstance() As DataTable
            Return New T0118066PesquisaDataTable
        End Function
        
        Friend Sub InitVars()
            Me.columnCODPMS = Me.Columns("CODPMS")
            Me.columnDATNGCPMS = Me.Columns("DATNGCPMS")
            Me.columnDATPRVRCBPMS = Me.Columns("DATPRVRCBPMS")
            Me.columnDESDSNDSCBNF = Me.Columns("DESDSNDSCBNF")
            Me.columnVLRNGCPMS = Me.Columns("VLRNGCPMS")
            Me.columnVLRPGOPMS = Me.Columns("VLRPGOPMS")
            Me.columnCODEMP = Me.Columns("CODEMP")
            Me.columnCODFILEMP = Me.Columns("CODFILEMP")
            Me.columnTIPDSNDSCBNF = Me.Columns("TIPDSNDSCBNF")
            Me.columnTIPFRMDSCBNF = Me.Columns("TIPFRMDSCBNF")
            Me.columnCODFRN = Me.Columns("CODFRN")
            Me.columnNUMPEDCNCACOCMC = Me.Columns("NUMPEDCNCACOCMC")
            Me.columnVLRSLDPMSFRN = Me.Columns("VLRSLDPMSFRN")
            Me.columnVLRDSPPMS = Me.Columns("VLRDSPPMS")
            Me.columnFLGSITNGCDUP = Me.Columns("FLGSITNGCDUP")
            Me.columnDESFRMDSCBNF = Me.Columns("DESFRMDSCBNF")
        End Sub
        
        Private Sub InitClass()
            Me.columnCODPMS = New DataColumn("CODPMS", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCODPMS)
            Me.columnDATNGCPMS = New DataColumn("DATNGCPMS", GetType(System.DateTime), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnDATNGCPMS)
            Me.columnDATPRVRCBPMS = New DataColumn("DATPRVRCBPMS", GetType(System.DateTime), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnDATPRVRCBPMS)
            Me.columnDESDSNDSCBNF = New DataColumn("DESDSNDSCBNF", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnDESDSNDSCBNF)
            Me.columnVLRNGCPMS = New DataColumn("VLRNGCPMS", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnVLRNGCPMS)
            Me.columnVLRPGOPMS = New DataColumn("VLRPGOPMS", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnVLRPGOPMS)
            Me.columnCODEMP = New DataColumn("CODEMP", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCODEMP)
            Me.columnCODFILEMP = New DataColumn("CODFILEMP", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCODFILEMP)
            Me.columnTIPDSNDSCBNF = New DataColumn("TIPDSNDSCBNF", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnTIPDSNDSCBNF)
            Me.columnTIPFRMDSCBNF = New DataColumn("TIPFRMDSCBNF", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnTIPFRMDSCBNF)
            Me.columnCODFRN = New DataColumn("CODFRN", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCODFRN)
            Me.columnNUMPEDCNCACOCMC = New DataColumn("NUMPEDCNCACOCMC", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnNUMPEDCNCACOCMC)
            Me.columnVLRSLDPMSFRN = New DataColumn("VLRSLDPMSFRN", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnVLRSLDPMSFRN)
            Me.columnVLRDSPPMS = New DataColumn("VLRDSPPMS", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnVLRDSPPMS)
            Me.columnFLGSITNGCDUP = New DataColumn("FLGSITNGCDUP", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnFLGSITNGCDUP)
            Me.columnDESFRMDSCBNF = New DataColumn("DESFRMDSCBNF", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnDESFRMDSCBNF)
            Me.columnCODPMS.AllowDBNull = false
            Me.columnDATNGCPMS.AllowDBNull = false
            Me.columnDATPRVRCBPMS.AllowDBNull = false
            Me.columnDESDSNDSCBNF.AllowDBNull = false
            Me.columnVLRNGCPMS.AllowDBNull = false
            Me.columnVLRPGOPMS.AllowDBNull = false
            Me.columnFLGSITNGCDUP.AllowDBNull = false
        End Sub
        
        Public Function NewT0118066PesquisaRow() As T0118066PesquisaRow
            Return CType(Me.NewRow,T0118066PesquisaRow)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New T0118066PesquisaRow(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(T0118066PesquisaRow)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.T0118066PesquisaRowChangedEvent) Is Nothing) Then
                RaiseEvent T0118066PesquisaRowChanged(Me, New T0118066PesquisaRowChangeEvent(CType(e.Row,T0118066PesquisaRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.T0118066PesquisaRowChangingEvent) Is Nothing) Then
                RaiseEvent T0118066PesquisaRowChanging(Me, New T0118066PesquisaRowChangeEvent(CType(e.Row,T0118066PesquisaRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.T0118066PesquisaRowDeletedEvent) Is Nothing) Then
                RaiseEvent T0118066PesquisaRowDeleted(Me, New T0118066PesquisaRowChangeEvent(CType(e.Row,T0118066PesquisaRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.T0118066PesquisaRowDeletingEvent) Is Nothing) Then
                RaiseEvent T0118066PesquisaRowDeleting(Me, New T0118066PesquisaRowChangeEvent(CType(e.Row,T0118066PesquisaRow), e.Action))
            End If
        End Sub
        
        Public Sub RemoveT0118066PesquisaRow(ByVal row As T0118066PesquisaRow)
            Me.Rows.Remove(row)
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class T0118066PesquisaRow
        Inherits DataRow
        
        Private tableT0118066Pesquisa As T0118066PesquisaDataTable
        
        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tableT0118066Pesquisa = CType(Me.Table,T0118066PesquisaDataTable)
        End Sub
        
        Public Property CODPMS As Decimal
            Get
                Return CType(Me(Me.tableT0118066Pesquisa.CODPMSColumn),Decimal)
            End Get
            Set
                Me(Me.tableT0118066Pesquisa.CODPMSColumn) = value
            End Set
        End Property
        
        Public Property DATNGCPMS As Date
            Get
                Return CType(Me(Me.tableT0118066Pesquisa.DATNGCPMSColumn),Date)
            End Get
            Set
                Me(Me.tableT0118066Pesquisa.DATNGCPMSColumn) = value
            End Set
        End Property
        
        Public Property DATPRVRCBPMS As Date
            Get
                Return CType(Me(Me.tableT0118066Pesquisa.DATPRVRCBPMSColumn),Date)
            End Get
            Set
                Me(Me.tableT0118066Pesquisa.DATPRVRCBPMSColumn) = value
            End Set
        End Property
        
        Public Property DESDSNDSCBNF As String
            Get
                Return CType(Me(Me.tableT0118066Pesquisa.DESDSNDSCBNFColumn),String)
            End Get
            Set
                Me(Me.tableT0118066Pesquisa.DESDSNDSCBNFColumn) = value
            End Set
        End Property
        
        Public Property VLRNGCPMS As Decimal
            Get
                Return CType(Me(Me.tableT0118066Pesquisa.VLRNGCPMSColumn),Decimal)
            End Get
            Set
                Me(Me.tableT0118066Pesquisa.VLRNGCPMSColumn) = value
            End Set
        End Property
        
        Public Property VLRPGOPMS As Decimal
            Get
                Return CType(Me(Me.tableT0118066Pesquisa.VLRPGOPMSColumn),Decimal)
            End Get
            Set
                Me(Me.tableT0118066Pesquisa.VLRPGOPMSColumn) = value
            End Set
        End Property
        
        Public Property CODEMP As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableT0118066Pesquisa.CODEMPColumn),Decimal)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableT0118066Pesquisa.CODEMPColumn) = value
            End Set
        End Property
        
        Public Property CODFILEMP As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableT0118066Pesquisa.CODFILEMPColumn),Decimal)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableT0118066Pesquisa.CODFILEMPColumn) = value
            End Set
        End Property
        
        Public Property TIPDSNDSCBNF As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableT0118066Pesquisa.TIPDSNDSCBNFColumn),Decimal)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableT0118066Pesquisa.TIPDSNDSCBNFColumn) = value
            End Set
        End Property
        
        Public Property TIPFRMDSCBNF As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableT0118066Pesquisa.TIPFRMDSCBNFColumn),Decimal)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableT0118066Pesquisa.TIPFRMDSCBNFColumn) = value
            End Set
        End Property
        
        Public Property CODFRN As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableT0118066Pesquisa.CODFRNColumn),Decimal)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableT0118066Pesquisa.CODFRNColumn) = value
            End Set
        End Property
        
        Public Property NUMPEDCNCACOCMC As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableT0118066Pesquisa.NUMPEDCNCACOCMCColumn),Decimal)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableT0118066Pesquisa.NUMPEDCNCACOCMCColumn) = value
            End Set
        End Property
        
        Public Property VLRSLDPMSFRN As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableT0118066Pesquisa.VLRSLDPMSFRNColumn),Decimal)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableT0118066Pesquisa.VLRSLDPMSFRNColumn) = value
            End Set
        End Property
        
        Public Property VLRDSPPMS As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableT0118066Pesquisa.VLRDSPPMSColumn),Decimal)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableT0118066Pesquisa.VLRDSPPMSColumn) = value
            End Set
        End Property
        
        Public Property FLGSITNGCDUP As String
            Get
                Return CType(Me(Me.tableT0118066Pesquisa.FLGSITNGCDUPColumn),String)
            End Get
            Set
                Me(Me.tableT0118066Pesquisa.FLGSITNGCDUPColumn) = value
            End Set
        End Property
        
        Public Property DESFRMDSCBNF As String
            Get
                Try 
                    Return CType(Me(Me.tableT0118066Pesquisa.DESFRMDSCBNFColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableT0118066Pesquisa.DESFRMDSCBNFColumn) = value
            End Set
        End Property
        
        Public Function IsCODEMPNull() As Boolean
            Return Me.IsNull(Me.tableT0118066Pesquisa.CODEMPColumn)
        End Function

        Public Function IsFLGSITNGCDUPNull() As Boolean
            Return Me.IsNull(Me.tableT0118066Pesquisa.FLGSITNGCDUPColumn)
        End Function

        Public Sub SetCODEMPNull()
            Me(Me.tableT0118066Pesquisa.CODEMPColumn) = System.Convert.DBNull
        End Sub

        Public Function IsCODFILEMPNull() As Boolean
            Return Me.IsNull(Me.tableT0118066Pesquisa.CODFILEMPColumn)
        End Function

        Public Sub SetCODFILEMPNull()
            Me(Me.tableT0118066Pesquisa.CODFILEMPColumn) = System.Convert.DBNull
        End Sub

        Public Function IsTIPDSNDSCBNFNull() As Boolean
            Return Me.IsNull(Me.tableT0118066Pesquisa.TIPDSNDSCBNFColumn)
        End Function

        Public Sub SetTIPDSNDSCBNFNull()
            Me(Me.tableT0118066Pesquisa.TIPDSNDSCBNFColumn) = System.Convert.DBNull
        End Sub

        Public Function IsTIPFRMDSCBNFNull() As Boolean
            Return Me.IsNull(Me.tableT0118066Pesquisa.TIPFRMDSCBNFColumn)
        End Function

        Public Sub SetTIPFRMDSCBNFNull()
            Me(Me.tableT0118066Pesquisa.TIPFRMDSCBNFColumn) = System.Convert.DBNull
        End Sub

        Public Function IsCODFRNNull() As Boolean
            Return Me.IsNull(Me.tableT0118066Pesquisa.CODFRNColumn)
        End Function

        Public Sub SetCODFRNNull()
            Me(Me.tableT0118066Pesquisa.CODFRNColumn) = System.Convert.DBNull
        End Sub

        Public Function IsNUMPEDCNCACOCMCNull() As Boolean
            Return Me.IsNull(Me.tableT0118066Pesquisa.NUMPEDCNCACOCMCColumn)
        End Function

        Public Sub SetNUMPEDCNCACOCMCNull()
            Me(Me.tableT0118066Pesquisa.NUMPEDCNCACOCMCColumn) = System.Convert.DBNull
        End Sub

        Public Function IsVLRSLDPMSFRNNull() As Boolean
            Return Me.IsNull(Me.tableT0118066Pesquisa.VLRSLDPMSFRNColumn)
        End Function

        Public Sub SetVLRSLDPMSFRNNull()
            Me(Me.tableT0118066Pesquisa.VLRSLDPMSFRNColumn) = System.Convert.DBNull
        End Sub

        Public Function IsVLRDSPPMSNull() As Boolean
            Return Me.IsNull(Me.tableT0118066Pesquisa.VLRDSPPMSColumn)
        End Function

        Public Sub SetVLRDSPPMSNull()
            Me(Me.tableT0118066Pesquisa.VLRDSPPMSColumn) = System.Convert.DBNull
        End Sub

        Public Function IsDESFRMDSCBNFNull() As Boolean
            Return Me.IsNull(Me.tableT0118066Pesquisa.DESFRMDSCBNFColumn)
        End Function

        Public Sub SetDESFRMDSCBNFNull()
            Me(Me.tableT0118066Pesquisa.DESFRMDSCBNFColumn) = System.Convert.DBNull
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class T0118066PesquisaRowChangeEvent
        Inherits EventArgs
        
        Private eventRow As T0118066PesquisaRow
        
        Private eventAction As DataRowAction
        
        Public Sub New(ByVal row As T0118066PesquisaRow, ByVal action As DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row As T0118066PesquisaRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
