'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Data
Imports System.Runtime.Serialization
Imports System.Xml


<Serializable(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Diagnostics.DebuggerStepThrough(),  _
 System.ComponentModel.ToolboxItem(true)>  _
Public Class DatasetDiretoriaEDivisaoDeCompraDeFornecedor
    Inherits DataSet
    
    Private tableTbDiretoriaEDivisaoDeCompraDeFornecedor As TbDiretoriaEDivisaoDeCompraDeFornecedorDataTable
    
    Public Sub New()
        MyBase.New
        Me.InitClass
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    Protected Sub New(ByVal info As SerializationInfo, ByVal context As StreamingContext)
        MyBase.New
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(System.String)),String)
        If (Not (strSchema) Is Nothing) Then
            Dim ds As DataSet = New DataSet
            ds.ReadXmlSchema(New XmlTextReader(New System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("TbDiretoriaEDivisaoDeCompraDeFornecedor")) Is Nothing) Then
                Me.Tables.Add(New TbDiretoriaEDivisaoDeCompraDeFornecedorDataTable(ds.Tables("TbDiretoriaEDivisaoDeCompraDeFornecedor")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.InitClass
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property TbDiretoriaEDivisaoDeCompraDeFornecedor As TbDiretoriaEDivisaoDeCompraDeFornecedorDataTable
        Get
            Return Me.tableTbDiretoriaEDivisaoDeCompraDeFornecedor
        End Get
    End Property
    
    Public Overrides Function Clone() As DataSet
        Dim cln As DatasetDiretoriaEDivisaoDeCompraDeFornecedor = CType(MyBase.Clone,DatasetDiretoriaEDivisaoDeCompraDeFornecedor)
        cln.InitVars
        Return cln
    End Function
    
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As XmlReader)
        Me.Reset
        Dim ds As DataSet = New DataSet
        ds.ReadXml(reader)
        If (Not (ds.Tables("TbDiretoriaEDivisaoDeCompraDeFornecedor")) Is Nothing) Then
            Me.Tables.Add(New TbDiretoriaEDivisaoDeCompraDeFornecedorDataTable(ds.Tables("TbDiretoriaEDivisaoDeCompraDeFornecedor")))
        End If
        Me.DataSetName = ds.DataSetName
        Me.Prefix = ds.Prefix
        Me.Namespace = ds.Namespace
        Me.Locale = ds.Locale
        Me.CaseSensitive = ds.CaseSensitive
        Me.EnforceConstraints = ds.EnforceConstraints
        Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
        Me.InitVars
    End Sub
    
    Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
        Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
        Me.WriteXmlSchema(New XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return System.Xml.Schema.XmlSchema.Read(New XmlTextReader(stream), Nothing)
    End Function
    
    Friend Sub InitVars()
        Me.tableTbDiretoriaEDivisaoDeCompraDeFornecedor = CType(Me.Tables("TbDiretoriaEDivisaoDeCompraDeFornecedor"),TbDiretoriaEDivisaoDeCompraDeFornecedorDataTable)
        If (Not (Me.tableTbDiretoriaEDivisaoDeCompraDeFornecedor) Is Nothing) Then
            Me.tableTbDiretoriaEDivisaoDeCompraDeFornecedor.InitVars
        End If
    End Sub
    
    Private Sub InitClass()
        Me.DataSetName = "DatasetDiretoriaEDivisaoDeCompraDeFornecedor"
        Me.Prefix = ""
        Me.Namespace = "http://tempuri.org/DatasetDiretoriaEDivisaoDeCompraDeFornecedor.xsd"
        Me.Locale = New System.Globalization.CultureInfo("en-US")
        Me.CaseSensitive = false
        Me.EnforceConstraints = true
        Me.tableTbDiretoriaEDivisaoDeCompraDeFornecedor = New TbDiretoriaEDivisaoDeCompraDeFornecedorDataTable
        Me.Tables.Add(Me.tableTbDiretoriaEDivisaoDeCompraDeFornecedor)
    End Sub
    
    Private Function ShouldSerializeTbDiretoriaEDivisaoDeCompraDeFornecedor() As Boolean
        Return false
    End Function
    
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    Public Delegate Sub TbDiretoriaEDivisaoDeCompraDeFornecedorRowChangeEventHandler(ByVal sender As Object, ByVal e As TbDiretoriaEDivisaoDeCompraDeFornecedorRowChangeEvent)
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class TbDiretoriaEDivisaoDeCompraDeFornecedorDataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable
        
        Private columnCodDrtCmp As DataColumn
        
        Private columnCodDivCmp As DataColumn
        
        Private columnDesDivCmp As DataColumn
        
        Private columnCodFrn As DataColumn
        
        Private columnNomFrn As DataColumn
        
        Friend Sub New()
            MyBase.New("TbDiretoriaEDivisaoDeCompraDeFornecedor")
            Me.InitClass
        End Sub
        
        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Friend ReadOnly Property CodDrtCmpColumn As DataColumn
            Get
                Return Me.columnCodDrtCmp
            End Get
        End Property
        
        Friend ReadOnly Property CodDivCmpColumn As DataColumn
            Get
                Return Me.columnCodDivCmp
            End Get
        End Property
        
        Friend ReadOnly Property DesDivCmpColumn As DataColumn
            Get
                Return Me.columnDesDivCmp
            End Get
        End Property
        
        Friend ReadOnly Property CodFrnColumn As DataColumn
            Get
                Return Me.columnCodFrn
            End Get
        End Property
        
        Friend ReadOnly Property NomFrnColumn As DataColumn
            Get
                Return Me.columnNomFrn
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As TbDiretoriaEDivisaoDeCompraDeFornecedorRow
            Get
                Return CType(Me.Rows(index),TbDiretoriaEDivisaoDeCompraDeFornecedorRow)
            End Get
        End Property
        
        Public Event TbDiretoriaEDivisaoDeCompraDeFornecedorRowChanged As TbDiretoriaEDivisaoDeCompraDeFornecedorRowChangeEventHandler
        
        Public Event TbDiretoriaEDivisaoDeCompraDeFornecedorRowChanging As TbDiretoriaEDivisaoDeCompraDeFornecedorRowChangeEventHandler
        
        Public Event TbDiretoriaEDivisaoDeCompraDeFornecedorRowDeleted As TbDiretoriaEDivisaoDeCompraDeFornecedorRowChangeEventHandler
        
        Public Event TbDiretoriaEDivisaoDeCompraDeFornecedorRowDeleting As TbDiretoriaEDivisaoDeCompraDeFornecedorRowChangeEventHandler
        
        Public Overloads Sub AddTbDiretoriaEDivisaoDeCompraDeFornecedorRow(ByVal row As TbDiretoriaEDivisaoDeCompraDeFornecedorRow)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function AddTbDiretoriaEDivisaoDeCompraDeFornecedorRow(ByVal CodDrtCmp As Decimal, ByVal CodDivCmp As Decimal, ByVal DesDivCmp As String, ByVal CodFrn As Decimal, ByVal NomFrn As String) As TbDiretoriaEDivisaoDeCompraDeFornecedorRow
            Dim rowTbDiretoriaEDivisaoDeCompraDeFornecedorRow As TbDiretoriaEDivisaoDeCompraDeFornecedorRow = CType(Me.NewRow,TbDiretoriaEDivisaoDeCompraDeFornecedorRow)
            rowTbDiretoriaEDivisaoDeCompraDeFornecedorRow.ItemArray = New Object() {CodDrtCmp, CodDivCmp, DesDivCmp, CodFrn, NomFrn}
            Me.Rows.Add(rowTbDiretoriaEDivisaoDeCompraDeFornecedorRow)
            Return rowTbDiretoriaEDivisaoDeCompraDeFornecedorRow
        End Function
        
        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As DataTable
            Dim cln As TbDiretoriaEDivisaoDeCompraDeFornecedorDataTable = CType(MyBase.Clone,TbDiretoriaEDivisaoDeCompraDeFornecedorDataTable)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function CreateInstance() As DataTable
            Return New TbDiretoriaEDivisaoDeCompraDeFornecedorDataTable
        End Function
        
        Friend Sub InitVars()
            Me.columnCodDrtCmp = Me.Columns("CodDrtCmp")
            Me.columnCodDivCmp = Me.Columns("CodDivCmp")
            Me.columnDesDivCmp = Me.Columns("DesDivCmp")
            Me.columnCodFrn = Me.Columns("CodFrn")
            Me.columnNomFrn = Me.Columns("NomFrn")
        End Sub
        
        Private Sub InitClass()
            Me.columnCodDrtCmp = New DataColumn("CodDrtCmp", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCodDrtCmp)
            Me.columnCodDivCmp = New DataColumn("CodDivCmp", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCodDivCmp)
            Me.columnDesDivCmp = New DataColumn("DesDivCmp", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnDesDivCmp)
            Me.columnCodFrn = New DataColumn("CodFrn", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCodFrn)
            Me.columnNomFrn = New DataColumn("NomFrn", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnNomFrn)
        End Sub
        
        Public Function NewTbDiretoriaEDivisaoDeCompraDeFornecedorRow() As TbDiretoriaEDivisaoDeCompraDeFornecedorRow
            Return CType(Me.NewRow,TbDiretoriaEDivisaoDeCompraDeFornecedorRow)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New TbDiretoriaEDivisaoDeCompraDeFornecedorRow(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(TbDiretoriaEDivisaoDeCompraDeFornecedorRow)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.TbDiretoriaEDivisaoDeCompraDeFornecedorRowChangedEvent) Is Nothing) Then
                RaiseEvent TbDiretoriaEDivisaoDeCompraDeFornecedorRowChanged(Me, New TbDiretoriaEDivisaoDeCompraDeFornecedorRowChangeEvent(CType(e.Row,TbDiretoriaEDivisaoDeCompraDeFornecedorRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.TbDiretoriaEDivisaoDeCompraDeFornecedorRowChangingEvent) Is Nothing) Then
                RaiseEvent TbDiretoriaEDivisaoDeCompraDeFornecedorRowChanging(Me, New TbDiretoriaEDivisaoDeCompraDeFornecedorRowChangeEvent(CType(e.Row,TbDiretoriaEDivisaoDeCompraDeFornecedorRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.TbDiretoriaEDivisaoDeCompraDeFornecedorRowDeletedEvent) Is Nothing) Then
                RaiseEvent TbDiretoriaEDivisaoDeCompraDeFornecedorRowDeleted(Me, New TbDiretoriaEDivisaoDeCompraDeFornecedorRowChangeEvent(CType(e.Row,TbDiretoriaEDivisaoDeCompraDeFornecedorRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.TbDiretoriaEDivisaoDeCompraDeFornecedorRowDeletingEvent) Is Nothing) Then
                RaiseEvent TbDiretoriaEDivisaoDeCompraDeFornecedorRowDeleting(Me, New TbDiretoriaEDivisaoDeCompraDeFornecedorRowChangeEvent(CType(e.Row,TbDiretoriaEDivisaoDeCompraDeFornecedorRow), e.Action))
            End If
        End Sub
        
        Public Sub RemoveTbDiretoriaEDivisaoDeCompraDeFornecedorRow(ByVal row As TbDiretoriaEDivisaoDeCompraDeFornecedorRow)
            Me.Rows.Remove(row)
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class TbDiretoriaEDivisaoDeCompraDeFornecedorRow
        Inherits DataRow
        
        Private tableTbDiretoriaEDivisaoDeCompraDeFornecedor As TbDiretoriaEDivisaoDeCompraDeFornecedorDataTable
        
        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tableTbDiretoriaEDivisaoDeCompraDeFornecedor = CType(Me.Table,TbDiretoriaEDivisaoDeCompraDeFornecedorDataTable)
        End Sub
        
        Public Property CodDrtCmp As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableTbDiretoriaEDivisaoDeCompraDeFornecedor.CodDrtCmpColumn),Decimal)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableTbDiretoriaEDivisaoDeCompraDeFornecedor.CodDrtCmpColumn) = value
            End Set
        End Property
        
        Public Property CodDivCmp As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableTbDiretoriaEDivisaoDeCompraDeFornecedor.CodDivCmpColumn),Decimal)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableTbDiretoriaEDivisaoDeCompraDeFornecedor.CodDivCmpColumn) = value
            End Set
        End Property
        
        Public Property DesDivCmp As String
            Get
                Try 
                    Return CType(Me(Me.tableTbDiretoriaEDivisaoDeCompraDeFornecedor.DesDivCmpColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableTbDiretoriaEDivisaoDeCompraDeFornecedor.DesDivCmpColumn) = value
            End Set
        End Property
        
        Public Property CodFrn As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableTbDiretoriaEDivisaoDeCompraDeFornecedor.CodFrnColumn),Decimal)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableTbDiretoriaEDivisaoDeCompraDeFornecedor.CodFrnColumn) = value
            End Set
        End Property
        
        Public Property NomFrn As String
            Get
                Try 
                    Return CType(Me(Me.tableTbDiretoriaEDivisaoDeCompraDeFornecedor.NomFrnColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableTbDiretoriaEDivisaoDeCompraDeFornecedor.NomFrnColumn) = value
            End Set
        End Property
        
        Public Function IsCodDrtCmpNull() As Boolean
            Return Me.IsNull(Me.tableTbDiretoriaEDivisaoDeCompraDeFornecedor.CodDrtCmpColumn)
        End Function
        
        Public Sub SetCodDrtCmpNull()
            Me(Me.tableTbDiretoriaEDivisaoDeCompraDeFornecedor.CodDrtCmpColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsCodDivCmpNull() As Boolean
            Return Me.IsNull(Me.tableTbDiretoriaEDivisaoDeCompraDeFornecedor.CodDivCmpColumn)
        End Function
        
        Public Sub SetCodDivCmpNull()
            Me(Me.tableTbDiretoriaEDivisaoDeCompraDeFornecedor.CodDivCmpColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsDesDivCmpNull() As Boolean
            Return Me.IsNull(Me.tableTbDiretoriaEDivisaoDeCompraDeFornecedor.DesDivCmpColumn)
        End Function
        
        Public Sub SetDesDivCmpNull()
            Me(Me.tableTbDiretoriaEDivisaoDeCompraDeFornecedor.DesDivCmpColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsCodFrnNull() As Boolean
            Return Me.IsNull(Me.tableTbDiretoriaEDivisaoDeCompraDeFornecedor.CodFrnColumn)
        End Function
        
        Public Sub SetCodFrnNull()
            Me(Me.tableTbDiretoriaEDivisaoDeCompraDeFornecedor.CodFrnColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsNomFrnNull() As Boolean
            Return Me.IsNull(Me.tableTbDiretoriaEDivisaoDeCompraDeFornecedor.NomFrnColumn)
        End Function
        
        Public Sub SetNomFrnNull()
            Me(Me.tableTbDiretoriaEDivisaoDeCompraDeFornecedor.NomFrnColumn) = System.Convert.DBNull
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class TbDiretoriaEDivisaoDeCompraDeFornecedorRowChangeEvent
        Inherits EventArgs
        
        Private eventRow As TbDiretoriaEDivisaoDeCompraDeFornecedorRow
        
        Private eventAction As DataRowAction
        
        Public Sub New(ByVal row As TbDiretoriaEDivisaoDeCompraDeFornecedorRow, ByVal action As DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row As TbDiretoriaEDivisaoDeCompraDeFornecedorRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
