'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Data
Imports System.Runtime.Serialization
Imports System.Xml


<Serializable(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Diagnostics.DebuggerStepThrough(),  _
 System.ComponentModel.ToolboxItem(true)>  _
Public Class DataSetRelatorioSaldoDisponivelFornecedorCelula
    Inherits DataSet
    
    Private tableTbAnalitico As TbAnaliticoDataTable
    
    Public Sub New()
        MyBase.New
        Me.InitClass
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    Protected Sub New(ByVal info As SerializationInfo, ByVal context As StreamingContext)
        MyBase.New
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(System.String)),String)
        If (Not (strSchema) Is Nothing) Then
            Dim ds As DataSet = New DataSet
            ds.ReadXmlSchema(New XmlTextReader(New System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("TbAnalitico")) Is Nothing) Then
                Me.Tables.Add(New TbAnaliticoDataTable(ds.Tables("TbAnalitico")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.InitClass
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property TbAnalitico As TbAnaliticoDataTable
        Get
            Return Me.tableTbAnalitico
        End Get
    End Property
    
    Public Overrides Function Clone() As DataSet
        Dim cln As DataSetRelatorioSaldoDisponivelFornecedorCelula = CType(MyBase.Clone,DataSetRelatorioSaldoDisponivelFornecedorCelula)
        cln.InitVars
        Return cln
    End Function
    
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As XmlReader)
        Me.Reset
        Dim ds As DataSet = New DataSet
        ds.ReadXml(reader)
        If (Not (ds.Tables("TbAnalitico")) Is Nothing) Then
            Me.Tables.Add(New TbAnaliticoDataTable(ds.Tables("TbAnalitico")))
        End If
        Me.DataSetName = ds.DataSetName
        Me.Prefix = ds.Prefix
        Me.Namespace = ds.Namespace
        Me.Locale = ds.Locale
        Me.CaseSensitive = ds.CaseSensitive
        Me.EnforceConstraints = ds.EnforceConstraints
        Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
        Me.InitVars
    End Sub
    
    Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
        Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
        Me.WriteXmlSchema(New XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return System.Xml.Schema.XmlSchema.Read(New XmlTextReader(stream), Nothing)
    End Function
    
    Friend Sub InitVars()
        Me.tableTbAnalitico = CType(Me.Tables("TbAnalitico"),TbAnaliticoDataTable)
        If (Not (Me.tableTbAnalitico) Is Nothing) Then
            Me.tableTbAnalitico.InitVars
        End If
    End Sub
    
    Private Sub InitClass()
        Me.DataSetName = "DataSetRelatorioSaldoDisponivelFornecedorCelula"
        Me.Prefix = ""
        Me.Namespace = "http://tempuri.org/DataSetRelatorioSaldoDisponivelFornecedorCelula.xsd"
        Me.Locale = New System.Globalization.CultureInfo("en-US")
        Me.CaseSensitive = false
        Me.EnforceConstraints = true
        Me.tableTbAnalitico = New TbAnaliticoDataTable
        Me.Tables.Add(Me.tableTbAnalitico)
    End Sub
    
    Private Function ShouldSerializeTbAnalitico() As Boolean
        Return false
    End Function
    
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    Public Delegate Sub TbAnaliticoRowChangeEventHandler(ByVal sender As Object, ByVal e As TbAnaliticoRowChangeEvent)
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class TbAnaliticoDataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable
        
        Private columnCODFRN As DataColumn
        
        Private columnTIPEMPENHO As DataColumn
        
        Private columnDESEMPENHO As DataColumn
        
        Private columnSALDO As DataColumn
        
        Private columnNOMFRN As DataColumn
        
        Private columnVlrSldRsv As DataColumn
        
        Private columnTIPDSNDSCBNF As DataColumn
        
        Private columnDESDSNDSCBNF As DataColumn
        
        Private columnVlrRcb As DataColumn
        
        Private columnTipAlcVbaFrn As DataColumn
        
        Private columnDesAlcVbaFrn As DataColumn
        
        Private columnPerAlcVbaFrn As DataColumn
        
        Private columnVlrAlcVbaFrn As DataColumn
        
        Private columnVlrRcbAlcVbaFrn As DataColumn
        
        Private columnVlrSldDspAlcVbaFrn As DataColumn
        
        Private columnPmtDdo As DataColumn
        
        Friend Sub New()
            MyBase.New("TbAnalitico")
            Me.InitClass
        End Sub
        
        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Friend ReadOnly Property CODFRNColumn As DataColumn
            Get
                Return Me.columnCODFRN
            End Get
        End Property
        
        Friend ReadOnly Property TIPEMPENHOColumn As DataColumn
            Get
                Return Me.columnTIPEMPENHO
            End Get
        End Property
        
        Friend ReadOnly Property DESEMPENHOColumn As DataColumn
            Get
                Return Me.columnDESEMPENHO
            End Get
        End Property
        
        Friend ReadOnly Property SALDOColumn As DataColumn
            Get
                Return Me.columnSALDO
            End Get
        End Property
        
        Friend ReadOnly Property NOMFRNColumn As DataColumn
            Get
                Return Me.columnNOMFRN
            End Get
        End Property
        
        Friend ReadOnly Property VlrSldRsvColumn As DataColumn
            Get
                Return Me.columnVlrSldRsv
            End Get
        End Property
        
        Friend ReadOnly Property TIPDSNDSCBNFColumn As DataColumn
            Get
                Return Me.columnTIPDSNDSCBNF
            End Get
        End Property
        
        Friend ReadOnly Property DESDSNDSCBNFColumn As DataColumn
            Get
                Return Me.columnDESDSNDSCBNF
            End Get
        End Property
        
        Friend ReadOnly Property VlrRcbColumn As DataColumn
            Get
                Return Me.columnVlrRcb
            End Get
        End Property
        
        Friend ReadOnly Property TipAlcVbaFrnColumn As DataColumn
            Get
                Return Me.columnTipAlcVbaFrn
            End Get
        End Property
        
        Friend ReadOnly Property DesAlcVbaFrnColumn As DataColumn
            Get
                Return Me.columnDesAlcVbaFrn
            End Get
        End Property
        
        Friend ReadOnly Property PerAlcVbaFrnColumn As DataColumn
            Get
                Return Me.columnPerAlcVbaFrn
            End Get
        End Property
        
        Friend ReadOnly Property VlrAlcVbaFrnColumn As DataColumn
            Get
                Return Me.columnVlrAlcVbaFrn
            End Get
        End Property
        
        Friend ReadOnly Property VlrRcbAlcVbaFrnColumn As DataColumn
            Get
                Return Me.columnVlrRcbAlcVbaFrn
            End Get
        End Property
        
        Friend ReadOnly Property VlrSldDspAlcVbaFrnColumn As DataColumn
            Get
                Return Me.columnVlrSldDspAlcVbaFrn
            End Get
        End Property
        
        Friend ReadOnly Property PmtDdoColumn As DataColumn
            Get
                Return Me.columnPmtDdo
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As TbAnaliticoRow
            Get
                Return CType(Me.Rows(index),TbAnaliticoRow)
            End Get
        End Property
        
        Public Event TbAnaliticoRowChanged As TbAnaliticoRowChangeEventHandler
        
        Public Event TbAnaliticoRowChanging As TbAnaliticoRowChangeEventHandler
        
        Public Event TbAnaliticoRowDeleted As TbAnaliticoRowChangeEventHandler
        
        Public Event TbAnaliticoRowDeleting As TbAnaliticoRowChangeEventHandler
        
        Public Overloads Sub AddTbAnaliticoRow(ByVal row As TbAnaliticoRow)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function AddTbAnaliticoRow( _
                    ByVal CODFRN As Long,  _
                    ByVal TIPEMPENHO As Decimal,  _
                    ByVal DESEMPENHO As String,  _
                    ByVal SALDO As Decimal,  _
                    ByVal NOMFRN As String,  _
                    ByVal VlrSldRsv As Decimal,  _
                    ByVal TIPDSNDSCBNF As Decimal,  _
                    ByVal DESDSNDSCBNF As String,  _
                    ByVal VlrRcb As Decimal,  _
                    ByVal TipAlcVbaFrn As Decimal,  _
                    ByVal DesAlcVbaFrn As String,  _
                    ByVal PerAlcVbaFrn As Decimal,  _
                    ByVal VlrAlcVbaFrn As Decimal,  _
                    ByVal VlrRcbAlcVbaFrn As Decimal,  _
                    ByVal VlrSldDspAlcVbaFrn As Decimal,  _
                    ByVal PmtDdo As String) As TbAnaliticoRow
            Dim rowTbAnaliticoRow As TbAnaliticoRow = CType(Me.NewRow,TbAnaliticoRow)
            rowTbAnaliticoRow.ItemArray = New Object() {CODFRN, TIPEMPENHO, DESEMPENHO, SALDO, NOMFRN, VlrSldRsv, TIPDSNDSCBNF, DESDSNDSCBNF, VlrRcb, TipAlcVbaFrn, DesAlcVbaFrn, PerAlcVbaFrn, VlrAlcVbaFrn, VlrRcbAlcVbaFrn, VlrSldDspAlcVbaFrn, PmtDdo}
            Me.Rows.Add(rowTbAnaliticoRow)
            Return rowTbAnaliticoRow
        End Function
        
        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As DataTable
            Dim cln As TbAnaliticoDataTable = CType(MyBase.Clone,TbAnaliticoDataTable)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function CreateInstance() As DataTable
            Return New TbAnaliticoDataTable
        End Function
        
        Friend Sub InitVars()
            Me.columnCODFRN = Me.Columns("CODFRN")
            Me.columnTIPEMPENHO = Me.Columns("TIPEMPENHO")
            Me.columnDESEMPENHO = Me.Columns("DESEMPENHO")
            Me.columnSALDO = Me.Columns("SALDO")
            Me.columnNOMFRN = Me.Columns("NOMFRN")
            Me.columnVlrSldRsv = Me.Columns("VlrSldRsv")
            Me.columnTIPDSNDSCBNF = Me.Columns("TIPDSNDSCBNF")
            Me.columnDESDSNDSCBNF = Me.Columns("DESDSNDSCBNF")
            Me.columnVlrRcb = Me.Columns("VlrRcb")
            Me.columnTipAlcVbaFrn = Me.Columns("TipAlcVbaFrn")
            Me.columnDesAlcVbaFrn = Me.Columns("DesAlcVbaFrn")
            Me.columnPerAlcVbaFrn = Me.Columns("PerAlcVbaFrn")
            Me.columnVlrAlcVbaFrn = Me.Columns("VlrAlcVbaFrn")
            Me.columnVlrRcbAlcVbaFrn = Me.Columns("VlrRcbAlcVbaFrn")
            Me.columnVlrSldDspAlcVbaFrn = Me.Columns("VlrSldDspAlcVbaFrn")
            Me.columnPmtDdo = Me.Columns("PmtDdo")
        End Sub
        
        Private Sub InitClass()
            Me.columnCODFRN = New DataColumn("CODFRN", GetType(System.Int64), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCODFRN)
            Me.columnTIPEMPENHO = New DataColumn("TIPEMPENHO", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnTIPEMPENHO)
            Me.columnDESEMPENHO = New DataColumn("DESEMPENHO", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnDESEMPENHO)
            Me.columnSALDO = New DataColumn("SALDO", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnSALDO)
            Me.columnNOMFRN = New DataColumn("NOMFRN", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnNOMFRN)
            Me.columnVlrSldRsv = New DataColumn("VlrSldRsv", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnVlrSldRsv)
            Me.columnTIPDSNDSCBNF = New DataColumn("TIPDSNDSCBNF", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnTIPDSNDSCBNF)
            Me.columnDESDSNDSCBNF = New DataColumn("DESDSNDSCBNF", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnDESDSNDSCBNF)
            Me.columnVlrRcb = New DataColumn("VlrRcb", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnVlrRcb)
            Me.columnTipAlcVbaFrn = New DataColumn("TipAlcVbaFrn", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnTipAlcVbaFrn)
            Me.columnDesAlcVbaFrn = New DataColumn("DesAlcVbaFrn", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnDesAlcVbaFrn)
            Me.columnPerAlcVbaFrn = New DataColumn("PerAlcVbaFrn", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnPerAlcVbaFrn)
            Me.columnVlrAlcVbaFrn = New DataColumn("VlrAlcVbaFrn", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnVlrAlcVbaFrn)
            Me.columnVlrRcbAlcVbaFrn = New DataColumn("VlrRcbAlcVbaFrn", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnVlrRcbAlcVbaFrn)
            Me.columnVlrSldDspAlcVbaFrn = New DataColumn("VlrSldDspAlcVbaFrn", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnVlrSldDspAlcVbaFrn)
            Me.columnPmtDdo = New DataColumn("PmtDdo", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnPmtDdo)
        End Sub
        
        Public Function NewTbAnaliticoRow() As TbAnaliticoRow
            Return CType(Me.NewRow,TbAnaliticoRow)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New TbAnaliticoRow(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(TbAnaliticoRow)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.TbAnaliticoRowChangedEvent) Is Nothing) Then
                RaiseEvent TbAnaliticoRowChanged(Me, New TbAnaliticoRowChangeEvent(CType(e.Row,TbAnaliticoRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.TbAnaliticoRowChangingEvent) Is Nothing) Then
                RaiseEvent TbAnaliticoRowChanging(Me, New TbAnaliticoRowChangeEvent(CType(e.Row,TbAnaliticoRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.TbAnaliticoRowDeletedEvent) Is Nothing) Then
                RaiseEvent TbAnaliticoRowDeleted(Me, New TbAnaliticoRowChangeEvent(CType(e.Row,TbAnaliticoRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.TbAnaliticoRowDeletingEvent) Is Nothing) Then
                RaiseEvent TbAnaliticoRowDeleting(Me, New TbAnaliticoRowChangeEvent(CType(e.Row,TbAnaliticoRow), e.Action))
            End If
        End Sub
        
        Public Sub RemoveTbAnaliticoRow(ByVal row As TbAnaliticoRow)
            Me.Rows.Remove(row)
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class TbAnaliticoRow
        Inherits DataRow
        
        Private tableTbAnalitico As TbAnaliticoDataTable
        
        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tableTbAnalitico = CType(Me.Table,TbAnaliticoDataTable)
        End Sub
        
        Public Property CODFRN As Long
            Get
                Try 
                    Return CType(Me(Me.tableTbAnalitico.CODFRNColumn),Long)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableTbAnalitico.CODFRNColumn) = value
            End Set
        End Property
        
        Public Property TIPEMPENHO As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableTbAnalitico.TIPEMPENHOColumn),Decimal)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableTbAnalitico.TIPEMPENHOColumn) = value
            End Set
        End Property
        
        Public Property DESEMPENHO As String
            Get
                Try 
                    Return CType(Me(Me.tableTbAnalitico.DESEMPENHOColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableTbAnalitico.DESEMPENHOColumn) = value
            End Set
        End Property
        
        Public Property SALDO As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableTbAnalitico.SALDOColumn),Decimal)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableTbAnalitico.SALDOColumn) = value
            End Set
        End Property
        
        Public Property NOMFRN As String
            Get
                Try 
                    Return CType(Me(Me.tableTbAnalitico.NOMFRNColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableTbAnalitico.NOMFRNColumn) = value
            End Set
        End Property
        
        Public Property VlrSldRsv As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableTbAnalitico.VlrSldRsvColumn),Decimal)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableTbAnalitico.VlrSldRsvColumn) = value
            End Set
        End Property
        
        Public Property TIPDSNDSCBNF As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableTbAnalitico.TIPDSNDSCBNFColumn),Decimal)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableTbAnalitico.TIPDSNDSCBNFColumn) = value
            End Set
        End Property
        
        Public Property DESDSNDSCBNF As String
            Get
                Try 
                    Return CType(Me(Me.tableTbAnalitico.DESDSNDSCBNFColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableTbAnalitico.DESDSNDSCBNFColumn) = value
            End Set
        End Property
        
        Public Property VlrRcb As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableTbAnalitico.VlrRcbColumn),Decimal)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableTbAnalitico.VlrRcbColumn) = value
            End Set
        End Property
        
        Public Property TipAlcVbaFrn As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableTbAnalitico.TipAlcVbaFrnColumn),Decimal)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableTbAnalitico.TipAlcVbaFrnColumn) = value
            End Set
        End Property
        
        Public Property DesAlcVbaFrn As String
            Get
                Try 
                    Return CType(Me(Me.tableTbAnalitico.DesAlcVbaFrnColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableTbAnalitico.DesAlcVbaFrnColumn) = value
            End Set
        End Property
        
        Public Property PerAlcVbaFrn As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableTbAnalitico.PerAlcVbaFrnColumn),Decimal)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableTbAnalitico.PerAlcVbaFrnColumn) = value
            End Set
        End Property
        
        Public Property VlrAlcVbaFrn As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableTbAnalitico.VlrAlcVbaFrnColumn),Decimal)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableTbAnalitico.VlrAlcVbaFrnColumn) = value
            End Set
        End Property
        
        Public Property VlrRcbAlcVbaFrn As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableTbAnalitico.VlrRcbAlcVbaFrnColumn),Decimal)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableTbAnalitico.VlrRcbAlcVbaFrnColumn) = value
            End Set
        End Property
        
        Public Property VlrSldDspAlcVbaFrn As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableTbAnalitico.VlrSldDspAlcVbaFrnColumn),Decimal)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableTbAnalitico.VlrSldDspAlcVbaFrnColumn) = value
            End Set
        End Property
        
        Public Property PmtDdo As String
            Get
                Try 
                    Return CType(Me(Me.tableTbAnalitico.PmtDdoColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableTbAnalitico.PmtDdoColumn) = value
            End Set
        End Property
        
        Public Function IsCODFRNNull() As Boolean
            Return Me.IsNull(Me.tableTbAnalitico.CODFRNColumn)
        End Function
        
        Public Sub SetCODFRNNull()
            Me(Me.tableTbAnalitico.CODFRNColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsTIPEMPENHONull() As Boolean
            Return Me.IsNull(Me.tableTbAnalitico.TIPEMPENHOColumn)
        End Function
        
        Public Sub SetTIPEMPENHONull()
            Me(Me.tableTbAnalitico.TIPEMPENHOColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsDESEMPENHONull() As Boolean
            Return Me.IsNull(Me.tableTbAnalitico.DESEMPENHOColumn)
        End Function
        
        Public Sub SetDESEMPENHONull()
            Me(Me.tableTbAnalitico.DESEMPENHOColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsSALDONull() As Boolean
            Return Me.IsNull(Me.tableTbAnalitico.SALDOColumn)
        End Function
        
        Public Sub SetSALDONull()
            Me(Me.tableTbAnalitico.SALDOColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsNOMFRNNull() As Boolean
            Return Me.IsNull(Me.tableTbAnalitico.NOMFRNColumn)
        End Function
        
        Public Sub SetNOMFRNNull()
            Me(Me.tableTbAnalitico.NOMFRNColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsVlrSldRsvNull() As Boolean
            Return Me.IsNull(Me.tableTbAnalitico.VlrSldRsvColumn)
        End Function
        
        Public Sub SetVlrSldRsvNull()
            Me(Me.tableTbAnalitico.VlrSldRsvColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsTIPDSNDSCBNFNull() As Boolean
            Return Me.IsNull(Me.tableTbAnalitico.TIPDSNDSCBNFColumn)
        End Function
        
        Public Sub SetTIPDSNDSCBNFNull()
            Me(Me.tableTbAnalitico.TIPDSNDSCBNFColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsDESDSNDSCBNFNull() As Boolean
            Return Me.IsNull(Me.tableTbAnalitico.DESDSNDSCBNFColumn)
        End Function
        
        Public Sub SetDESDSNDSCBNFNull()
            Me(Me.tableTbAnalitico.DESDSNDSCBNFColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsVlrRcbNull() As Boolean
            Return Me.IsNull(Me.tableTbAnalitico.VlrRcbColumn)
        End Function
        
        Public Sub SetVlrRcbNull()
            Me(Me.tableTbAnalitico.VlrRcbColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsTipAlcVbaFrnNull() As Boolean
            Return Me.IsNull(Me.tableTbAnalitico.TipAlcVbaFrnColumn)
        End Function
        
        Public Sub SetTipAlcVbaFrnNull()
            Me(Me.tableTbAnalitico.TipAlcVbaFrnColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsDesAlcVbaFrnNull() As Boolean
            Return Me.IsNull(Me.tableTbAnalitico.DesAlcVbaFrnColumn)
        End Function
        
        Public Sub SetDesAlcVbaFrnNull()
            Me(Me.tableTbAnalitico.DesAlcVbaFrnColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsPerAlcVbaFrnNull() As Boolean
            Return Me.IsNull(Me.tableTbAnalitico.PerAlcVbaFrnColumn)
        End Function
        
        Public Sub SetPerAlcVbaFrnNull()
            Me(Me.tableTbAnalitico.PerAlcVbaFrnColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsVlrAlcVbaFrnNull() As Boolean
            Return Me.IsNull(Me.tableTbAnalitico.VlrAlcVbaFrnColumn)
        End Function
        
        Public Sub SetVlrAlcVbaFrnNull()
            Me(Me.tableTbAnalitico.VlrAlcVbaFrnColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsVlrRcbAlcVbaFrnNull() As Boolean
            Return Me.IsNull(Me.tableTbAnalitico.VlrRcbAlcVbaFrnColumn)
        End Function
        
        Public Sub SetVlrRcbAlcVbaFrnNull()
            Me(Me.tableTbAnalitico.VlrRcbAlcVbaFrnColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsVlrSldDspAlcVbaFrnNull() As Boolean
            Return Me.IsNull(Me.tableTbAnalitico.VlrSldDspAlcVbaFrnColumn)
        End Function
        
        Public Sub SetVlrSldDspAlcVbaFrnNull()
            Me(Me.tableTbAnalitico.VlrSldDspAlcVbaFrnColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsPmtDdoNull() As Boolean
            Return Me.IsNull(Me.tableTbAnalitico.PmtDdoColumn)
        End Function
        
        Public Sub SetPmtDdoNull()
            Me(Me.tableTbAnalitico.PmtDdoColumn) = System.Convert.DBNull
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class TbAnaliticoRowChangeEvent
        Inherits EventArgs
        
        Private eventRow As TbAnaliticoRow
        
        Private eventAction As DataRowAction
        
        Public Sub New(ByVal row As TbAnaliticoRow, ByVal action As DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row As TbAnaliticoRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
