'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2032
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Data
Imports System.Runtime.Serialization
Imports System.Xml


<Serializable(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Diagnostics.DebuggerStepThrough(),  _
 System.ComponentModel.ToolboxItem(true)>  _
Public Class DatasetParametroContabilContaCorrenteFornecedor
    Inherits DataSet
    
    Private tableT0123094 As T0123094DataTable
    
    Public Sub New()
        MyBase.New
        Me.InitClass
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    Protected Sub New(ByVal info As SerializationInfo, ByVal context As StreamingContext)
        MyBase.New
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(System.String)),String)
        If (Not (strSchema) Is Nothing) Then
            Dim ds As DataSet = New DataSet
            ds.ReadXmlSchema(New XmlTextReader(New System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("T0123094")) Is Nothing) Then
                Me.Tables.Add(New T0123094DataTable(ds.Tables("T0123094")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.InitClass
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property T0123094 As T0123094DataTable
        Get
            Return Me.tableT0123094
        End Get
    End Property
    
    Public Overrides Function Clone() As DataSet
        Dim cln As DatasetParametroContabilContaCorrenteFornecedor = CType(MyBase.Clone,DatasetParametroContabilContaCorrenteFornecedor)
        cln.InitVars
        Return cln
    End Function
    
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As XmlReader)
        Me.Reset
        Dim ds As DataSet = New DataSet
        ds.ReadXml(reader)
        If (Not (ds.Tables("T0123094")) Is Nothing) Then
            Me.Tables.Add(New T0123094DataTable(ds.Tables("T0123094")))
        End If
        Me.DataSetName = ds.DataSetName
        Me.Prefix = ds.Prefix
        Me.Namespace = ds.Namespace
        Me.Locale = ds.Locale
        Me.CaseSensitive = ds.CaseSensitive
        Me.EnforceConstraints = ds.EnforceConstraints
        Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
        Me.InitVars
    End Sub
    
    Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
        Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
        Me.WriteXmlSchema(New XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return System.Xml.Schema.XmlSchema.Read(New XmlTextReader(stream), Nothing)
    End Function
    
    Friend Sub InitVars()
        Me.tableT0123094 = CType(Me.Tables("T0123094"),T0123094DataTable)
        If (Not (Me.tableT0123094) Is Nothing) Then
            Me.tableT0123094.InitVars
        End If
    End Sub
    
    Private Sub InitClass()
        Me.DataSetName = "DatasetParametroContabilContaCorrenteFornecedor"
        Me.Prefix = ""
        Me.Namespace = "http://tempuri.org/DatasetParametroContabilContaCorrenteFornecedor.xsd"
        Me.Locale = New System.Globalization.CultureInfo("en-US")
        Me.CaseSensitive = false
        Me.EnforceConstraints = true
        Me.tableT0123094 = New T0123094DataTable
        Me.Tables.Add(Me.tableT0123094)
    End Sub
    
    Private Function ShouldSerializeT0123094() As Boolean
        Return false
    End Function
    
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    Public Delegate Sub T0123094RowChangeEventHandler(ByVal sender As Object, ByVal e As T0123094RowChangeEvent)
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class T0123094DataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable
        
        Private columnCODTIPLMT As DataColumn
        
        Private columnCODFILEMP As DataColumn
        
        Private columnCODCNTDEB As DataColumn
        
        Private columnCODCENCSTDEB As DataColumn
        
        Private columnCODCNTCRD As DataColumn
        
        Private columnCODCENCSTCRD As DataColumn
        
        Private columnCODHSTPAD As DataColumn
        
        Private columnCODEVTCTB As DataColumn
        
        Private columnCODFTOCTB As DataColumn
        
        Private columnCODEVTCTBNGCDVL As DataColumn
        
        Private columnCODFTOCTBNGCDVL As DataColumn
        
        Private columnCODEVTCTBFRTDVL As DataColumn
        
        Private columnCODFTOCTBFRTDVL As DataColumn
        
        Friend Sub New()
            MyBase.New("T0123094")
            Me.InitClass
        End Sub
        
        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Friend ReadOnly Property CODTIPLMTColumn As DataColumn
            Get
                Return Me.columnCODTIPLMT
            End Get
        End Property
        
        Friend ReadOnly Property CODFILEMPColumn As DataColumn
            Get
                Return Me.columnCODFILEMP
            End Get
        End Property
        
        Friend ReadOnly Property CODCNTDEBColumn As DataColumn
            Get
                Return Me.columnCODCNTDEB
            End Get
        End Property
        
        Friend ReadOnly Property CODCENCSTDEBColumn As DataColumn
            Get
                Return Me.columnCODCENCSTDEB
            End Get
        End Property
        
        Friend ReadOnly Property CODCNTCRDColumn As DataColumn
            Get
                Return Me.columnCODCNTCRD
            End Get
        End Property
        
        Friend ReadOnly Property CODCENCSTCRDColumn As DataColumn
            Get
                Return Me.columnCODCENCSTCRD
            End Get
        End Property
        
        Friend ReadOnly Property CODHSTPADColumn As DataColumn
            Get
                Return Me.columnCODHSTPAD
            End Get
        End Property
        
        Friend ReadOnly Property CODEVTCTBColumn As DataColumn
            Get
                Return Me.columnCODEVTCTB
            End Get
        End Property
        
        Friend ReadOnly Property CODFTOCTBColumn As DataColumn
            Get
                Return Me.columnCODFTOCTB
            End Get
        End Property
        
        Friend ReadOnly Property CODEVTCTBNGCDVLColumn As DataColumn
            Get
                Return Me.columnCODEVTCTBNGCDVL
            End Get
        End Property
        
        Friend ReadOnly Property CODFTOCTBNGCDVLColumn As DataColumn
            Get
                Return Me.columnCODFTOCTBNGCDVL
            End Get
        End Property
        
        Friend ReadOnly Property CODEVTCTBFRTDVLColumn As DataColumn
            Get
                Return Me.columnCODEVTCTBFRTDVL
            End Get
        End Property
        
        Friend ReadOnly Property CODFTOCTBFRTDVLColumn As DataColumn
            Get
                Return Me.columnCODFTOCTBFRTDVL
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As T0123094Row
            Get
                Return CType(Me.Rows(index),T0123094Row)
            End Get
        End Property
        
        Public Event T0123094RowChanged As T0123094RowChangeEventHandler
        
        Public Event T0123094RowChanging As T0123094RowChangeEventHandler
        
        Public Event T0123094RowDeleted As T0123094RowChangeEventHandler
        
        Public Event T0123094RowDeleting As T0123094RowChangeEventHandler
        
        Public Overloads Sub AddT0123094Row(ByVal row As T0123094Row)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function AddT0123094Row(ByVal CODTIPLMT As Decimal, ByVal CODFILEMP As Decimal, ByVal CODCNTDEB As String, ByVal CODCENCSTDEB As String, ByVal CODCNTCRD As String, ByVal CODCENCSTCRD As String, ByVal CODHSTPAD As String, ByVal CODEVTCTB As Decimal, ByVal CODFTOCTB As Decimal, ByVal CODEVTCTBNGCDVL As Decimal, ByVal CODFTOCTBNGCDVL As Decimal, ByVal CODEVTCTBFRTDVL As Decimal, ByVal CODFTOCTBFRTDVL As Decimal) As T0123094Row
            Dim rowT0123094Row As T0123094Row = CType(Me.NewRow,T0123094Row)
            rowT0123094Row.ItemArray = New Object() {CODTIPLMT, CODFILEMP, CODCNTDEB, CODCENCSTDEB, CODCNTCRD, CODCENCSTCRD, CODHSTPAD, CODEVTCTB, CODFTOCTB, CODEVTCTBNGCDVL, CODFTOCTBNGCDVL, CODEVTCTBFRTDVL, CODFTOCTBFRTDVL}
            Me.Rows.Add(rowT0123094Row)
            Return rowT0123094Row
        End Function
        
        Public Function FindByCODTIPLMTCODFILEMP(ByVal CODTIPLMT As Decimal, ByVal CODFILEMP As Decimal) As T0123094Row
            Return CType(Me.Rows.Find(New Object() {CODTIPLMT, CODFILEMP}),T0123094Row)
        End Function
        
        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As DataTable
            Dim cln As T0123094DataTable = CType(MyBase.Clone,T0123094DataTable)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function CreateInstance() As DataTable
            Return New T0123094DataTable
        End Function
        
        Friend Sub InitVars()
            Me.columnCODTIPLMT = Me.Columns("CODTIPLMT")
            Me.columnCODFILEMP = Me.Columns("CODFILEMP")
            Me.columnCODCNTDEB = Me.Columns("CODCNTDEB")
            Me.columnCODCENCSTDEB = Me.Columns("CODCENCSTDEB")
            Me.columnCODCNTCRD = Me.Columns("CODCNTCRD")
            Me.columnCODCENCSTCRD = Me.Columns("CODCENCSTCRD")
            Me.columnCODHSTPAD = Me.Columns("CODHSTPAD")
            Me.columnCODEVTCTB = Me.Columns("CODEVTCTB")
            Me.columnCODFTOCTB = Me.Columns("CODFTOCTB")
            Me.columnCODEVTCTBNGCDVL = Me.Columns("CODEVTCTBNGCDVL")
            Me.columnCODFTOCTBNGCDVL = Me.Columns("CODFTOCTBNGCDVL")
            Me.columnCODEVTCTBFRTDVL = Me.Columns("CODEVTCTBFRTDVL")
            Me.columnCODFTOCTBFRTDVL = Me.Columns("CODFTOCTBFRTDVL")
        End Sub
        
        Private Sub InitClass()
            Me.columnCODTIPLMT = New DataColumn("CODTIPLMT", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCODTIPLMT)
            Me.columnCODFILEMP = New DataColumn("CODFILEMP", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCODFILEMP)
            Me.columnCODCNTDEB = New DataColumn("CODCNTDEB", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCODCNTDEB)
            Me.columnCODCENCSTDEB = New DataColumn("CODCENCSTDEB", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCODCENCSTDEB)
            Me.columnCODCNTCRD = New DataColumn("CODCNTCRD", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCODCNTCRD)
            Me.columnCODCENCSTCRD = New DataColumn("CODCENCSTCRD", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCODCENCSTCRD)
            Me.columnCODHSTPAD = New DataColumn("CODHSTPAD", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCODHSTPAD)
            Me.columnCODEVTCTB = New DataColumn("CODEVTCTB", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCODEVTCTB)
            Me.columnCODFTOCTB = New DataColumn("CODFTOCTB", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCODFTOCTB)
            Me.columnCODEVTCTBNGCDVL = New DataColumn("CODEVTCTBNGCDVL", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCODEVTCTBNGCDVL)
            Me.columnCODFTOCTBNGCDVL = New DataColumn("CODFTOCTBNGCDVL", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCODFTOCTBNGCDVL)
            Me.columnCODEVTCTBFRTDVL = New DataColumn("CODEVTCTBFRTDVL", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCODEVTCTBFRTDVL)
            Me.columnCODFTOCTBFRTDVL = New DataColumn("CODFTOCTBFRTDVL", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCODFTOCTBFRTDVL)
            Me.Constraints.Add(New UniqueConstraint("DatasetParametroContabilContaCorrenteFornecedorKey1", New DataColumn() {Me.columnCODTIPLMT, Me.columnCODFILEMP}, true))
            Me.columnCODTIPLMT.AllowDBNull = false
            Me.columnCODFILEMP.AllowDBNull = false
            Me.columnCODCNTDEB.AllowDBNull = false
            Me.columnCODCENCSTDEB.AllowDBNull = false
            Me.columnCODCNTCRD.AllowDBNull = false
            Me.columnCODCENCSTCRD.AllowDBNull = false
            Me.columnCODHSTPAD.AllowDBNull = false
        End Sub
        
        Public Function NewT0123094Row() As T0123094Row
            Return CType(Me.NewRow,T0123094Row)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New T0123094Row(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(T0123094Row)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.T0123094RowChangedEvent) Is Nothing) Then
                RaiseEvent T0123094RowChanged(Me, New T0123094RowChangeEvent(CType(e.Row,T0123094Row), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.T0123094RowChangingEvent) Is Nothing) Then
                RaiseEvent T0123094RowChanging(Me, New T0123094RowChangeEvent(CType(e.Row,T0123094Row), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.T0123094RowDeletedEvent) Is Nothing) Then
                RaiseEvent T0123094RowDeleted(Me, New T0123094RowChangeEvent(CType(e.Row,T0123094Row), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.T0123094RowDeletingEvent) Is Nothing) Then
                RaiseEvent T0123094RowDeleting(Me, New T0123094RowChangeEvent(CType(e.Row,T0123094Row), e.Action))
            End If
        End Sub
        
        Public Sub RemoveT0123094Row(ByVal row As T0123094Row)
            Me.Rows.Remove(row)
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class T0123094Row
        Inherits DataRow
        
        Private tableT0123094 As T0123094DataTable
        
        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tableT0123094 = CType(Me.Table,T0123094DataTable)
        End Sub
        
        Public Property CODTIPLMT As Decimal
            Get
                Return CType(Me(Me.tableT0123094.CODTIPLMTColumn),Decimal)
            End Get
            Set
                Me(Me.tableT0123094.CODTIPLMTColumn) = value
            End Set
        End Property
        
        Public Property CODFILEMP As Decimal
            Get
                Return CType(Me(Me.tableT0123094.CODFILEMPColumn),Decimal)
            End Get
            Set
                Me(Me.tableT0123094.CODFILEMPColumn) = value
            End Set
        End Property
        
        Public Property CODCNTDEB As String
            Get
                Return CType(Me(Me.tableT0123094.CODCNTDEBColumn),String)
            End Get
            Set
                Me(Me.tableT0123094.CODCNTDEBColumn) = value
            End Set
        End Property
        
        Public Property CODCENCSTDEB As String
            Get
                Return CType(Me(Me.tableT0123094.CODCENCSTDEBColumn),String)
            End Get
            Set
                Me(Me.tableT0123094.CODCENCSTDEBColumn) = value
            End Set
        End Property
        
        Public Property CODCNTCRD As String
            Get
                Return CType(Me(Me.tableT0123094.CODCNTCRDColumn),String)
            End Get
            Set
                Me(Me.tableT0123094.CODCNTCRDColumn) = value
            End Set
        End Property
        
        Public Property CODCENCSTCRD As String
            Get
                Return CType(Me(Me.tableT0123094.CODCENCSTCRDColumn),String)
            End Get
            Set
                Me(Me.tableT0123094.CODCENCSTCRDColumn) = value
            End Set
        End Property
        
        Public Property CODHSTPAD As String
            Get
                Return CType(Me(Me.tableT0123094.CODHSTPADColumn),String)
            End Get
            Set
                Me(Me.tableT0123094.CODHSTPADColumn) = value
            End Set
        End Property
        
        Public Property CODEVTCTB As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableT0123094.CODEVTCTBColumn),Decimal)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableT0123094.CODEVTCTBColumn) = value
            End Set
        End Property
        
        Public Property CODFTOCTB As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableT0123094.CODFTOCTBColumn),Decimal)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableT0123094.CODFTOCTBColumn) = value
            End Set
        End Property
        
        Public Property CODEVTCTBNGCDVL As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableT0123094.CODEVTCTBNGCDVLColumn),Decimal)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableT0123094.CODEVTCTBNGCDVLColumn) = value
            End Set
        End Property
        
        Public Property CODFTOCTBNGCDVL As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableT0123094.CODFTOCTBNGCDVLColumn),Decimal)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableT0123094.CODFTOCTBNGCDVLColumn) = value
            End Set
        End Property
        
        Public Property CODEVTCTBFRTDVL As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableT0123094.CODEVTCTBFRTDVLColumn),Decimal)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableT0123094.CODEVTCTBFRTDVLColumn) = value
            End Set
        End Property
        
        Public Property CODFTOCTBFRTDVL As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableT0123094.CODFTOCTBFRTDVLColumn),Decimal)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableT0123094.CODFTOCTBFRTDVLColumn) = value
            End Set
        End Property
        
        Public Function IsCODEVTCTBNull() As Boolean
            Return Me.IsNull(Me.tableT0123094.CODEVTCTBColumn)
        End Function
        
        Public Sub SetCODEVTCTBNull()
            Me(Me.tableT0123094.CODEVTCTBColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsCODFTOCTBNull() As Boolean
            Return Me.IsNull(Me.tableT0123094.CODFTOCTBColumn)
        End Function
        
        Public Sub SetCODFTOCTBNull()
            Me(Me.tableT0123094.CODFTOCTBColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsCODEVTCTBNGCDVLNull() As Boolean
            Return Me.IsNull(Me.tableT0123094.CODEVTCTBNGCDVLColumn)
        End Function
        
        Public Sub SetCODEVTCTBNGCDVLNull()
            Me(Me.tableT0123094.CODEVTCTBNGCDVLColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsCODFTOCTBNGCDVLNull() As Boolean
            Return Me.IsNull(Me.tableT0123094.CODFTOCTBNGCDVLColumn)
        End Function
        
        Public Sub SetCODFTOCTBNGCDVLNull()
            Me(Me.tableT0123094.CODFTOCTBNGCDVLColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsCODEVTCTBFRTDVLNull() As Boolean
            Return Me.IsNull(Me.tableT0123094.CODEVTCTBFRTDVLColumn)
        End Function
        
        Public Sub SetCODEVTCTBFRTDVLNull()
            Me(Me.tableT0123094.CODEVTCTBFRTDVLColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsCODFTOCTBFRTDVLNull() As Boolean
            Return Me.IsNull(Me.tableT0123094.CODFTOCTBFRTDVLColumn)
        End Function
        
        Public Sub SetCODFTOCTBFRTDVLNull()
            Me(Me.tableT0123094.CODFTOCTBFRTDVLColumn) = System.Convert.DBNull
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class T0123094RowChangeEvent
        Inherits EventArgs
        
        Private eventRow As T0123094Row
        
        Private eventAction As DataRowAction
        
        Public Sub New(ByVal row As T0123094Row, ByVal action As DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row As T0123094Row
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
