'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2407
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Data
Imports System.Runtime.Serialization
Imports System.Xml


<Serializable(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Diagnostics.DebuggerStepThrough(),  _
 System.ComponentModel.ToolboxItem(true)>  _
Public Class DatasetFluxoAprovacao
    Inherits DataSet
    
    Private tableT0161591 As T0161591DataTable
    
    Private tableFuncionario As FuncionarioDataTable
    
    Public Sub New()
        MyBase.New
        Me.InitClass
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    Protected Sub New(ByVal info As SerializationInfo, ByVal context As StreamingContext)
        MyBase.New
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(System.String)),String)
        If (Not (strSchema) Is Nothing) Then
            Dim ds As DataSet = New DataSet
            ds.ReadXmlSchema(New XmlTextReader(New System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("T0161591")) Is Nothing) Then
                Me.Tables.Add(New T0161591DataTable(ds.Tables("T0161591")))
            End If
            If (Not (ds.Tables("Funcionario")) Is Nothing) Then
                Me.Tables.Add(New FuncionarioDataTable(ds.Tables("Funcionario")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.InitClass
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property T0161591 As T0161591DataTable
        Get
            Return Me.tableT0161591
        End Get
    End Property
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property Funcionario As FuncionarioDataTable
        Get
            Return Me.tableFuncionario
        End Get
    End Property
    
    Public Overrides Function Clone() As DataSet
        Dim cln As DatasetFluxoAprovacao = CType(MyBase.Clone,DatasetFluxoAprovacao)
        cln.InitVars
        Return cln
    End Function
    
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As XmlReader)
        Me.Reset
        Dim ds As DataSet = New DataSet
        ds.ReadXml(reader)
        If (Not (ds.Tables("T0161591")) Is Nothing) Then
            Me.Tables.Add(New T0161591DataTable(ds.Tables("T0161591")))
        End If
        If (Not (ds.Tables("Funcionario")) Is Nothing) Then
            Me.Tables.Add(New FuncionarioDataTable(ds.Tables("Funcionario")))
        End If
        Me.DataSetName = ds.DataSetName
        Me.Prefix = ds.Prefix
        Me.Namespace = ds.Namespace
        Me.Locale = ds.Locale
        Me.CaseSensitive = ds.CaseSensitive
        Me.EnforceConstraints = ds.EnforceConstraints
        Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
        Me.InitVars
    End Sub
    
    Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
        Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
        Me.WriteXmlSchema(New XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return System.Xml.Schema.XmlSchema.Read(New XmlTextReader(stream), Nothing)
    End Function
    
    Friend Sub InitVars()
        Me.tableT0161591 = CType(Me.Tables("T0161591"),T0161591DataTable)
        If (Not (Me.tableT0161591) Is Nothing) Then
            Me.tableT0161591.InitVars
        End If
        Me.tableFuncionario = CType(Me.Tables("Funcionario"),FuncionarioDataTable)
        If (Not (Me.tableFuncionario) Is Nothing) Then
            Me.tableFuncionario.InitVars
        End If
    End Sub
    
    Private Sub InitClass()
        Me.DataSetName = "DatasetFluxoAprovacao"
        Me.Prefix = ""
        Me.Namespace = "http://tempuri.org/DatasetFluxoAprovacao.xsd"
        Me.Locale = New System.Globalization.CultureInfo("en-US")
        Me.CaseSensitive = false
        Me.EnforceConstraints = true
        Me.tableT0161591 = New T0161591DataTable
        Me.Tables.Add(Me.tableT0161591)
        Me.tableFuncionario = New FuncionarioDataTable
        Me.Tables.Add(Me.tableFuncionario)
    End Sub
    
    Private Function ShouldSerializeT0161591() As Boolean
        Return false
    End Function
    
    Private Function ShouldSerializeFuncionario() As Boolean
        Return false
    End Function
    
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    Public Delegate Sub T0161591RowChangeEventHandler(ByVal sender As Object, ByVal e As T0161591RowChangeEvent)
    
    Public Delegate Sub FuncionarioRowChangeEventHandler(ByVal sender As Object, ByVal e As FuncionarioRowChangeEvent)
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class T0161591DataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable
        
        Private columnCODSISINF As DataColumn
        
        Private columnNUMFLUAPV As DataColumn
        
        Private columnNUMSEQFLUAPV As DataColumn
        
        Private columnDATHRAFLUAPV As DataColumn
        
        Private columnNUMSEQNIVAPV As DataColumn
        
        Private columnCODEDEAPV As DataColumn
        
        Private columnTIPSTAFLUAPV As DataColumn
        
        Private columnDATHRAAPVFLU As DataColumn
        
        Private columnDESOBSAPV As DataColumn
        
        Private columnDESMTVAPVFLUACOCMC As DataColumn
        
        Private columnNUMSEQFLUAPVPEDOPN As DataColumn
        
        Private columnCODEDEARZ As DataColumn
        
        Friend Sub New()
            MyBase.New("T0161591")
            Me.InitClass
        End Sub
        
        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Friend ReadOnly Property CODSISINFColumn As DataColumn
            Get
                Return Me.columnCODSISINF
            End Get
        End Property
        
        Friend ReadOnly Property NUMFLUAPVColumn As DataColumn
            Get
                Return Me.columnNUMFLUAPV
            End Get
        End Property
        
        Friend ReadOnly Property NUMSEQFLUAPVColumn As DataColumn
            Get
                Return Me.columnNUMSEQFLUAPV
            End Get
        End Property
        
        Friend ReadOnly Property DATHRAFLUAPVColumn As DataColumn
            Get
                Return Me.columnDATHRAFLUAPV
            End Get
        End Property
        
        Friend ReadOnly Property NUMSEQNIVAPVColumn As DataColumn
            Get
                Return Me.columnNUMSEQNIVAPV
            End Get
        End Property
        
        Friend ReadOnly Property CODEDEAPVColumn As DataColumn
            Get
                Return Me.columnCODEDEAPV
            End Get
        End Property
        
        Friend ReadOnly Property TIPSTAFLUAPVColumn As DataColumn
            Get
                Return Me.columnTIPSTAFLUAPV
            End Get
        End Property
        
        Friend ReadOnly Property DATHRAAPVFLUColumn As DataColumn
            Get
                Return Me.columnDATHRAAPVFLU
            End Get
        End Property
        
        Friend ReadOnly Property DESOBSAPVColumn As DataColumn
            Get
                Return Me.columnDESOBSAPV
            End Get
        End Property
        
        Friend ReadOnly Property DESMTVAPVFLUACOCMCColumn As DataColumn
            Get
                Return Me.columnDESMTVAPVFLUACOCMC
            End Get
        End Property
        
        Friend ReadOnly Property NUMSEQFLUAPVPEDOPNColumn As DataColumn
            Get
                Return Me.columnNUMSEQFLUAPVPEDOPN
            End Get
        End Property
        
        Friend ReadOnly Property CODEDEARZColumn As DataColumn
            Get
                Return Me.columnCODEDEARZ
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As T0161591Row
            Get
                Return CType(Me.Rows(index),T0161591Row)
            End Get
        End Property
        
        Public Event T0161591RowChanged As T0161591RowChangeEventHandler
        
        Public Event T0161591RowChanging As T0161591RowChangeEventHandler
        
        Public Event T0161591RowDeleted As T0161591RowChangeEventHandler
        
        Public Event T0161591RowDeleting As T0161591RowChangeEventHandler
        
        Public Overloads Sub AddT0161591Row(ByVal row As T0161591Row)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function AddT0161591Row(ByVal CODSISINF As Decimal, ByVal NUMFLUAPV As Decimal, ByVal NUMSEQFLUAPV As Decimal, ByVal DATHRAFLUAPV As Date, ByVal NUMSEQNIVAPV As Decimal, ByVal CODEDEAPV As Decimal, ByVal TIPSTAFLUAPV As String, ByVal DATHRAAPVFLU As Date, ByVal DESOBSAPV As String, ByVal DESMTVAPVFLUACOCMC As String, ByVal NUMSEQFLUAPVPEDOPN As Decimal, ByVal CODEDEARZ As Decimal) As T0161591Row
            Dim rowT0161591Row As T0161591Row = CType(Me.NewRow,T0161591Row)
            rowT0161591Row.ItemArray = New Object() {CODSISINF, NUMFLUAPV, NUMSEQFLUAPV, DATHRAFLUAPV, NUMSEQNIVAPV, CODEDEAPV, TIPSTAFLUAPV, DATHRAAPVFLU, DESOBSAPV, DESMTVAPVFLUACOCMC, NUMSEQFLUAPVPEDOPN, CODEDEARZ}
            Me.Rows.Add(rowT0161591Row)
            Return rowT0161591Row
        End Function
        
        Public Function FindByCODSISINFNUMFLUAPVNUMSEQFLUAPV(ByVal CODSISINF As Decimal, ByVal NUMFLUAPV As Decimal, ByVal NUMSEQFLUAPV As Decimal) As T0161591Row
            Return CType(Me.Rows.Find(New Object() {CODSISINF, NUMFLUAPV, NUMSEQFLUAPV}),T0161591Row)
        End Function
        
        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As DataTable
            Dim cln As T0161591DataTable = CType(MyBase.Clone,T0161591DataTable)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function CreateInstance() As DataTable
            Return New T0161591DataTable
        End Function
        
        Friend Sub InitVars()
            Me.columnCODSISINF = Me.Columns("CODSISINF")
            Me.columnNUMFLUAPV = Me.Columns("NUMFLUAPV")
            Me.columnNUMSEQFLUAPV = Me.Columns("NUMSEQFLUAPV")
            Me.columnDATHRAFLUAPV = Me.Columns("DATHRAFLUAPV")
            Me.columnNUMSEQNIVAPV = Me.Columns("NUMSEQNIVAPV")
            Me.columnCODEDEAPV = Me.Columns("CODEDEAPV")
            Me.columnTIPSTAFLUAPV = Me.Columns("TIPSTAFLUAPV")
            Me.columnDATHRAAPVFLU = Me.Columns("DATHRAAPVFLU")
            Me.columnDESOBSAPV = Me.Columns("DESOBSAPV")
            Me.columnDESMTVAPVFLUACOCMC = Me.Columns("DESMTVAPVFLUACOCMC")
            Me.columnNUMSEQFLUAPVPEDOPN = Me.Columns("NUMSEQFLUAPVPEDOPN")
            Me.columnCODEDEARZ = Me.Columns("CODEDEARZ")
        End Sub
        
        Private Sub InitClass()
            Me.columnCODSISINF = New DataColumn("CODSISINF", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCODSISINF)
            Me.columnNUMFLUAPV = New DataColumn("NUMFLUAPV", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnNUMFLUAPV)
            Me.columnNUMSEQFLUAPV = New DataColumn("NUMSEQFLUAPV", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnNUMSEQFLUAPV)
            Me.columnDATHRAFLUAPV = New DataColumn("DATHRAFLUAPV", GetType(System.DateTime), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnDATHRAFLUAPV)
            Me.columnNUMSEQNIVAPV = New DataColumn("NUMSEQNIVAPV", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnNUMSEQNIVAPV)
            Me.columnCODEDEAPV = New DataColumn("CODEDEAPV", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCODEDEAPV)
            Me.columnTIPSTAFLUAPV = New DataColumn("TIPSTAFLUAPV", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnTIPSTAFLUAPV)
            Me.columnDATHRAAPVFLU = New DataColumn("DATHRAAPVFLU", GetType(System.DateTime), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnDATHRAAPVFLU)
            Me.columnDESOBSAPV = New DataColumn("DESOBSAPV", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnDESOBSAPV)
            Me.columnDESMTVAPVFLUACOCMC = New DataColumn("DESMTVAPVFLUACOCMC", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnDESMTVAPVFLUACOCMC)
            Me.columnNUMSEQFLUAPVPEDOPN = New DataColumn("NUMSEQFLUAPVPEDOPN", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnNUMSEQFLUAPVPEDOPN)
            Me.columnCODEDEARZ = New DataColumn("CODEDEARZ", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCODEDEARZ)
            Me.Constraints.Add(New UniqueConstraint("DatasetFluxoAprovacaoKey1", New DataColumn() {Me.columnCODSISINF, Me.columnNUMFLUAPV, Me.columnNUMSEQFLUAPV}, true))
            Me.columnCODSISINF.AllowDBNull = false
            Me.columnNUMFLUAPV.AllowDBNull = false
            Me.columnNUMSEQFLUAPV.AllowDBNull = false
            Me.columnDATHRAFLUAPV.AllowDBNull = false
            Me.columnNUMSEQNIVAPV.AllowDBNull = false
            Me.columnCODEDEAPV.AllowDBNull = false
            Me.columnDESMTVAPVFLUACOCMC.AllowDBNull = false
            Me.columnNUMSEQFLUAPVPEDOPN.AllowDBNull = false
            Me.columnCODEDEARZ.AllowDBNull = false
        End Sub
        
        Public Function NewT0161591Row() As T0161591Row
            Return CType(Me.NewRow,T0161591Row)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New T0161591Row(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(T0161591Row)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.T0161591RowChangedEvent) Is Nothing) Then
                RaiseEvent T0161591RowChanged(Me, New T0161591RowChangeEvent(CType(e.Row,T0161591Row), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.T0161591RowChangingEvent) Is Nothing) Then
                RaiseEvent T0161591RowChanging(Me, New T0161591RowChangeEvent(CType(e.Row,T0161591Row), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.T0161591RowDeletedEvent) Is Nothing) Then
                RaiseEvent T0161591RowDeleted(Me, New T0161591RowChangeEvent(CType(e.Row,T0161591Row), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.T0161591RowDeletingEvent) Is Nothing) Then
                RaiseEvent T0161591RowDeleting(Me, New T0161591RowChangeEvent(CType(e.Row,T0161591Row), e.Action))
            End If
        End Sub
        
        Public Sub RemoveT0161591Row(ByVal row As T0161591Row)
            Me.Rows.Remove(row)
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class T0161591Row
        Inherits DataRow
        
        Private tableT0161591 As T0161591DataTable
        
        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tableT0161591 = CType(Me.Table,T0161591DataTable)
        End Sub
        
        Public Property CODSISINF As Decimal
            Get
                Return CType(Me(Me.tableT0161591.CODSISINFColumn),Decimal)
            End Get
            Set
                Me(Me.tableT0161591.CODSISINFColumn) = value
            End Set
        End Property
        
        Public Property NUMFLUAPV As Decimal
            Get
                Return CType(Me(Me.tableT0161591.NUMFLUAPVColumn),Decimal)
            End Get
            Set
                Me(Me.tableT0161591.NUMFLUAPVColumn) = value
            End Set
        End Property
        
        Public Property NUMSEQFLUAPV As Decimal
            Get
                Return CType(Me(Me.tableT0161591.NUMSEQFLUAPVColumn),Decimal)
            End Get
            Set
                Me(Me.tableT0161591.NUMSEQFLUAPVColumn) = value
            End Set
        End Property
        
        Public Property DATHRAFLUAPV As Date
            Get
                Return CType(Me(Me.tableT0161591.DATHRAFLUAPVColumn),Date)
            End Get
            Set
                Me(Me.tableT0161591.DATHRAFLUAPVColumn) = value
            End Set
        End Property
        
        Public Property NUMSEQNIVAPV As Decimal
            Get
                Return CType(Me(Me.tableT0161591.NUMSEQNIVAPVColumn),Decimal)
            End Get
            Set
                Me(Me.tableT0161591.NUMSEQNIVAPVColumn) = value
            End Set
        End Property
        
        Public Property CODEDEAPV As Decimal
            Get
                Return CType(Me(Me.tableT0161591.CODEDEAPVColumn),Decimal)
            End Get
            Set
                Me(Me.tableT0161591.CODEDEAPVColumn) = value
            End Set
        End Property
        
        Public Property TIPSTAFLUAPV As String
            Get
                Try 
                    Return CType(Me(Me.tableT0161591.TIPSTAFLUAPVColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableT0161591.TIPSTAFLUAPVColumn) = value
            End Set
        End Property
        
        Public Property DATHRAAPVFLU As Date
            Get
                Try 
                    Return CType(Me(Me.tableT0161591.DATHRAAPVFLUColumn),Date)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableT0161591.DATHRAAPVFLUColumn) = value
            End Set
        End Property
        
        Public Property DESOBSAPV As String
            Get
                Try 
                    Return CType(Me(Me.tableT0161591.DESOBSAPVColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableT0161591.DESOBSAPVColumn) = value
            End Set
        End Property
        
        Public Property DESMTVAPVFLUACOCMC As String
            Get
                Return CType(Me(Me.tableT0161591.DESMTVAPVFLUACOCMCColumn),String)
            End Get
            Set
                Me(Me.tableT0161591.DESMTVAPVFLUACOCMCColumn) = value
            End Set
        End Property
        
        Public Property NUMSEQFLUAPVPEDOPN As Decimal
            Get
                Return CType(Me(Me.tableT0161591.NUMSEQFLUAPVPEDOPNColumn),Decimal)
            End Get
            Set
                Me(Me.tableT0161591.NUMSEQFLUAPVPEDOPNColumn) = value
            End Set
        End Property
        
        Public Property CODEDEARZ As Decimal
            Get
                Return CType(Me(Me.tableT0161591.CODEDEARZColumn),Decimal)
            End Get
            Set
                Me(Me.tableT0161591.CODEDEARZColumn) = value
            End Set
        End Property
        
        Public Function IsTIPSTAFLUAPVNull() As Boolean
            Return Me.IsNull(Me.tableT0161591.TIPSTAFLUAPVColumn)
        End Function
        
        Public Sub SetTIPSTAFLUAPVNull()
            Me(Me.tableT0161591.TIPSTAFLUAPVColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsDATHRAAPVFLUNull() As Boolean
            Return Me.IsNull(Me.tableT0161591.DATHRAAPVFLUColumn)
        End Function
        
        Public Sub SetDATHRAAPVFLUNull()
            Me(Me.tableT0161591.DATHRAAPVFLUColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsDESOBSAPVNull() As Boolean
            Return Me.IsNull(Me.tableT0161591.DESOBSAPVColumn)
        End Function
        
        Public Sub SetDESOBSAPVNull()
            Me(Me.tableT0161591.DESOBSAPVColumn) = System.Convert.DBNull
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class T0161591RowChangeEvent
        Inherits EventArgs
        
        Private eventRow As T0161591Row
        
        Private eventAction As DataRowAction
        
        Public Sub New(ByVal row As T0161591Row, ByVal action As DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row As T0161591Row
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class FuncionarioDataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable
        
        Private columnCODFNC As DataColumn
        
        Private columnNOMUSRRCF As DataColumn
        
        Friend Sub New()
            MyBase.New("Funcionario")
            Me.InitClass
        End Sub
        
        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Friend ReadOnly Property CODFNCColumn As DataColumn
            Get
                Return Me.columnCODFNC
            End Get
        End Property
        
        Friend ReadOnly Property NOMUSRRCFColumn As DataColumn
            Get
                Return Me.columnNOMUSRRCF
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As FuncionarioRow
            Get
                Return CType(Me.Rows(index),FuncionarioRow)
            End Get
        End Property
        
        Public Event FuncionarioRowChanged As FuncionarioRowChangeEventHandler
        
        Public Event FuncionarioRowChanging As FuncionarioRowChangeEventHandler
        
        Public Event FuncionarioRowDeleted As FuncionarioRowChangeEventHandler
        
        Public Event FuncionarioRowDeleting As FuncionarioRowChangeEventHandler
        
        Public Overloads Sub AddFuncionarioRow(ByVal row As FuncionarioRow)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function AddFuncionarioRow(ByVal CODFNC As Decimal, ByVal NOMUSRRCF As String) As FuncionarioRow
            Dim rowFuncionarioRow As FuncionarioRow = CType(Me.NewRow,FuncionarioRow)
            rowFuncionarioRow.ItemArray = New Object() {CODFNC, NOMUSRRCF}
            Me.Rows.Add(rowFuncionarioRow)
            Return rowFuncionarioRow
        End Function
        
        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As DataTable
            Dim cln As FuncionarioDataTable = CType(MyBase.Clone,FuncionarioDataTable)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function CreateInstance() As DataTable
            Return New FuncionarioDataTable
        End Function
        
        Friend Sub InitVars()
            Me.columnCODFNC = Me.Columns("CODFNC")
            Me.columnNOMUSRRCF = Me.Columns("NOMUSRRCF")
        End Sub
        
        Private Sub InitClass()
            Me.columnCODFNC = New DataColumn("CODFNC", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCODFNC)
            Me.columnNOMUSRRCF = New DataColumn("NOMUSRRCF", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnNOMUSRRCF)
        End Sub
        
        Public Function NewFuncionarioRow() As FuncionarioRow
            Return CType(Me.NewRow,FuncionarioRow)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New FuncionarioRow(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(FuncionarioRow)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.FuncionarioRowChangedEvent) Is Nothing) Then
                RaiseEvent FuncionarioRowChanged(Me, New FuncionarioRowChangeEvent(CType(e.Row,FuncionarioRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.FuncionarioRowChangingEvent) Is Nothing) Then
                RaiseEvent FuncionarioRowChanging(Me, New FuncionarioRowChangeEvent(CType(e.Row,FuncionarioRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.FuncionarioRowDeletedEvent) Is Nothing) Then
                RaiseEvent FuncionarioRowDeleted(Me, New FuncionarioRowChangeEvent(CType(e.Row,FuncionarioRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.FuncionarioRowDeletingEvent) Is Nothing) Then
                RaiseEvent FuncionarioRowDeleting(Me, New FuncionarioRowChangeEvent(CType(e.Row,FuncionarioRow), e.Action))
            End If
        End Sub
        
        Public Sub RemoveFuncionarioRow(ByVal row As FuncionarioRow)
            Me.Rows.Remove(row)
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class FuncionarioRow
        Inherits DataRow
        
        Private tableFuncionario As FuncionarioDataTable
        
        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tableFuncionario = CType(Me.Table,FuncionarioDataTable)
        End Sub
        
        Public Property CODFNC As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableFuncionario.CODFNCColumn),Decimal)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableFuncionario.CODFNCColumn) = value
            End Set
        End Property
        
        Public Property NOMUSRRCF As String
            Get
                Try 
                    Return CType(Me(Me.tableFuncionario.NOMUSRRCFColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableFuncionario.NOMUSRRCFColumn) = value
            End Set
        End Property
        
        Public Function IsCODFNCNull() As Boolean
            Return Me.IsNull(Me.tableFuncionario.CODFNCColumn)
        End Function
        
        Public Sub SetCODFNCNull()
            Me(Me.tableFuncionario.CODFNCColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsNOMUSRRCFNull() As Boolean
            Return Me.IsNull(Me.tableFuncionario.NOMUSRRCFColumn)
        End Function
        
        Public Sub SetNOMUSRRCFNull()
            Me(Me.tableFuncionario.NOMUSRRCFColumn) = System.Convert.DBNull
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class FuncionarioRowChangeEvent
        Inherits EventArgs
        
        Private eventRow As FuncionarioRow
        
        Private eventAction As DataRowAction
        
        Public Sub New(ByVal row As FuncionarioRow, ByVal action As DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row As FuncionarioRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
