'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2407
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Data
Imports System.Runtime.Serialization
Imports System.Xml


<Serializable(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Diagnostics.DebuggerStepThrough(),  _
 System.ComponentModel.ToolboxItem(true)>  _
Public Class DatasetFuncionario
    Inherits DataSet
    
    Private tableT0100361 As T0100361DataTable
    
    Public Sub New()
        MyBase.New
        Me.InitClass
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    Protected Sub New(ByVal info As SerializationInfo, ByVal context As StreamingContext)
        MyBase.New
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(System.String)),String)
        If (Not (strSchema) Is Nothing) Then
            Dim ds As DataSet = New DataSet
            ds.ReadXmlSchema(New XmlTextReader(New System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("T0100361")) Is Nothing) Then
                Me.Tables.Add(New T0100361DataTable(ds.Tables("T0100361")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.InitClass
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property T0100361 As T0100361DataTable
        Get
            Return Me.tableT0100361
        End Get
    End Property
    
    Public Overrides Function Clone() As DataSet
        Dim cln As DatasetFuncionario = CType(MyBase.Clone,DatasetFuncionario)
        cln.InitVars
        Return cln
    End Function
    
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As XmlReader)
        Me.Reset
        Dim ds As DataSet = New DataSet
        ds.ReadXml(reader)
        If (Not (ds.Tables("T0100361")) Is Nothing) Then
            Me.Tables.Add(New T0100361DataTable(ds.Tables("T0100361")))
        End If
        Me.DataSetName = ds.DataSetName
        Me.Prefix = ds.Prefix
        Me.Namespace = ds.Namespace
        Me.Locale = ds.Locale
        Me.CaseSensitive = ds.CaseSensitive
        Me.EnforceConstraints = ds.EnforceConstraints
        Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
        Me.InitVars
    End Sub
    
    Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
        Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
        Me.WriteXmlSchema(New XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return System.Xml.Schema.XmlSchema.Read(New XmlTextReader(stream), Nothing)
    End Function
    
    Friend Sub InitVars()
        Me.tableT0100361 = CType(Me.Tables("T0100361"),T0100361DataTable)
        If (Not (Me.tableT0100361) Is Nothing) Then
            Me.tableT0100361.InitVars
        End If
    End Sub
    
    Private Sub InitClass()
        Me.DataSetName = "DatasetFuncionario"
        Me.Prefix = ""
        Me.Namespace = "http://tempuri.org/DatasetFuncionario.xsd"
        Me.Locale = New System.Globalization.CultureInfo("en-US")
        Me.CaseSensitive = false
        Me.EnforceConstraints = true
        Me.tableT0100361 = New T0100361DataTable
        Me.Tables.Add(Me.tableT0100361)
    End Sub
    
    Private Function ShouldSerializeT0100361() As Boolean
        Return false
    End Function
    
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    Public Delegate Sub T0100361RowChangeEventHandler(ByVal sender As Object, ByVal e As T0100361RowChangeEvent)
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class T0100361DataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable
        
        Private columnCODFNC As DataColumn
        
        Private columnNOMFNC As DataColumn
        
        Private columnCODDPT As DataColumn
        
        Private columnCODSEC As DataColumn
        
        Private columnCODEMP As DataColumn
        
        Private columnDATADSFNC As DataColumn
        
        Private columnDATDEMFNC As DataColumn
        
        Private columnENDFNC As DataColumn
        
        Private columnCODCID As DataColumn
        
        Private columnCODBAIFNC As DataColumn
        
        Private columnCODCEPFNC As DataColumn
        
        Private columnNUMTLFFNC As DataColumn
        
        Private columnCODFILFNC As DataColumn
        
        Private columnCODSEXFNC As DataColumn
        
        Private columnCODDRT As DataColumn
        
        Private columnCODDIV As DataColumn
        
        Private columnCODCENCST As DataColumn
        
        Private columnCODGRPPGTFNC As DataColumn
        
        Private columnCODSETFNC As DataColumn
        
        Private columnNUMCNTCRRFNC As DataColumn
        
        Private columnCODAGEBCOFNC As DataColumn
        
        Private columnCODBCOFNC As DataColumn
        
        Private columnCODCGRFNC As DataColumn
        
        Private columnNUMCPFFNC As DataColumn
        
        Private columnCODSNDFNC As DataColumn
        
        Private columnDATNSC As DataColumn
        
        Private columnCODUNDNGC As DataColumn
        
        Private columnCODFILEMP As DataColumn
        
        Private columnCODUNDREG As DataColumn
        
        Private columnCODSGMMCDCTB As DataColumn
        
        Private columnNUMRMLTLF As DataColumn
        
        Private columnDESPSWFNCPAD As DataColumn
        
        Private columnDESPSWCDF As DataColumn
        
        Private columnDESENDCREETNFNC As DataColumn
        
        Private columnCODNIVFNC As DataColumn
        
        Private columnINDTRBFNC As DataColumn
        
        Private columnNUMCARCCP As DataColumn
        
        Private columnNUMCARRLP As DataColumn
        
        Private columnDATVLDCARCCP As DataColumn
        
        Private columnDATVLDCARRLP As DataColumn
        
        Private columnDATPRVDEMFNC As DataColumn
        
        Private columnNUMCPF As DataColumn
        
        Private columnDATALTCADFNC As DataColumn
        
        Private columnTIPFNC As DataColumn
        
        Friend Sub New()
            MyBase.New("T0100361")
            Me.InitClass
        End Sub
        
        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Friend ReadOnly Property CODFNCColumn As DataColumn
            Get
                Return Me.columnCODFNC
            End Get
        End Property
        
        Friend ReadOnly Property NOMFNCColumn As DataColumn
            Get
                Return Me.columnNOMFNC
            End Get
        End Property
        
        Friend ReadOnly Property CODDPTColumn As DataColumn
            Get
                Return Me.columnCODDPT
            End Get
        End Property
        
        Friend ReadOnly Property CODSECColumn As DataColumn
            Get
                Return Me.columnCODSEC
            End Get
        End Property
        
        Friend ReadOnly Property CODEMPColumn As DataColumn
            Get
                Return Me.columnCODEMP
            End Get
        End Property
        
        Friend ReadOnly Property DATADSFNCColumn As DataColumn
            Get
                Return Me.columnDATADSFNC
            End Get
        End Property
        
        Friend ReadOnly Property DATDEMFNCColumn As DataColumn
            Get
                Return Me.columnDATDEMFNC
            End Get
        End Property
        
        Friend ReadOnly Property ENDFNCColumn As DataColumn
            Get
                Return Me.columnENDFNC
            End Get
        End Property
        
        Friend ReadOnly Property CODCIDColumn As DataColumn
            Get
                Return Me.columnCODCID
            End Get
        End Property
        
        Friend ReadOnly Property CODBAIFNCColumn As DataColumn
            Get
                Return Me.columnCODBAIFNC
            End Get
        End Property
        
        Friend ReadOnly Property CODCEPFNCColumn As DataColumn
            Get
                Return Me.columnCODCEPFNC
            End Get
        End Property
        
        Friend ReadOnly Property NUMTLFFNCColumn As DataColumn
            Get
                Return Me.columnNUMTLFFNC
            End Get
        End Property
        
        Friend ReadOnly Property CODFILFNCColumn As DataColumn
            Get
                Return Me.columnCODFILFNC
            End Get
        End Property
        
        Friend ReadOnly Property CODSEXFNCColumn As DataColumn
            Get
                Return Me.columnCODSEXFNC
            End Get
        End Property
        
        Friend ReadOnly Property CODDRTColumn As DataColumn
            Get
                Return Me.columnCODDRT
            End Get
        End Property
        
        Friend ReadOnly Property CODDIVColumn As DataColumn
            Get
                Return Me.columnCODDIV
            End Get
        End Property
        
        Friend ReadOnly Property CODCENCSTColumn As DataColumn
            Get
                Return Me.columnCODCENCST
            End Get
        End Property
        
        Friend ReadOnly Property CODGRPPGTFNCColumn As DataColumn
            Get
                Return Me.columnCODGRPPGTFNC
            End Get
        End Property
        
        Friend ReadOnly Property CODSETFNCColumn As DataColumn
            Get
                Return Me.columnCODSETFNC
            End Get
        End Property
        
        Friend ReadOnly Property NUMCNTCRRFNCColumn As DataColumn
            Get
                Return Me.columnNUMCNTCRRFNC
            End Get
        End Property
        
        Friend ReadOnly Property CODAGEBCOFNCColumn As DataColumn
            Get
                Return Me.columnCODAGEBCOFNC
            End Get
        End Property
        
        Friend ReadOnly Property CODBCOFNCColumn As DataColumn
            Get
                Return Me.columnCODBCOFNC
            End Get
        End Property
        
        Friend ReadOnly Property CODCGRFNCColumn As DataColumn
            Get
                Return Me.columnCODCGRFNC
            End Get
        End Property
        
        Friend ReadOnly Property NUMCPFFNCColumn As DataColumn
            Get
                Return Me.columnNUMCPFFNC
            End Get
        End Property
        
        Friend ReadOnly Property CODSNDFNCColumn As DataColumn
            Get
                Return Me.columnCODSNDFNC
            End Get
        End Property
        
        Friend ReadOnly Property DATNSCColumn As DataColumn
            Get
                Return Me.columnDATNSC
            End Get
        End Property
        
        Friend ReadOnly Property CODUNDNGCColumn As DataColumn
            Get
                Return Me.columnCODUNDNGC
            End Get
        End Property
        
        Friend ReadOnly Property CODFILEMPColumn As DataColumn
            Get
                Return Me.columnCODFILEMP
            End Get
        End Property
        
        Friend ReadOnly Property CODUNDREGColumn As DataColumn
            Get
                Return Me.columnCODUNDREG
            End Get
        End Property
        
        Friend ReadOnly Property CODSGMMCDCTBColumn As DataColumn
            Get
                Return Me.columnCODSGMMCDCTB
            End Get
        End Property
        
        Friend ReadOnly Property NUMRMLTLFColumn As DataColumn
            Get
                Return Me.columnNUMRMLTLF
            End Get
        End Property
        
        Friend ReadOnly Property DESPSWFNCPADColumn As DataColumn
            Get
                Return Me.columnDESPSWFNCPAD
            End Get
        End Property
        
        Friend ReadOnly Property DESPSWCDFColumn As DataColumn
            Get
                Return Me.columnDESPSWCDF
            End Get
        End Property
        
        Friend ReadOnly Property DESENDCREETNFNCColumn As DataColumn
            Get
                Return Me.columnDESENDCREETNFNC
            End Get
        End Property
        
        Friend ReadOnly Property CODNIVFNCColumn As DataColumn
            Get
                Return Me.columnCODNIVFNC
            End Get
        End Property
        
        Friend ReadOnly Property INDTRBFNCColumn As DataColumn
            Get
                Return Me.columnINDTRBFNC
            End Get
        End Property
        
        Friend ReadOnly Property NUMCARCCPColumn As DataColumn
            Get
                Return Me.columnNUMCARCCP
            End Get
        End Property
        
        Friend ReadOnly Property NUMCARRLPColumn As DataColumn
            Get
                Return Me.columnNUMCARRLP
            End Get
        End Property
        
        Friend ReadOnly Property DATVLDCARCCPColumn As DataColumn
            Get
                Return Me.columnDATVLDCARCCP
            End Get
        End Property
        
        Friend ReadOnly Property DATVLDCARRLPColumn As DataColumn
            Get
                Return Me.columnDATVLDCARRLP
            End Get
        End Property
        
        Friend ReadOnly Property DATPRVDEMFNCColumn As DataColumn
            Get
                Return Me.columnDATPRVDEMFNC
            End Get
        End Property
        
        Friend ReadOnly Property NUMCPFColumn As DataColumn
            Get
                Return Me.columnNUMCPF
            End Get
        End Property
        
        Friend ReadOnly Property DATALTCADFNCColumn As DataColumn
            Get
                Return Me.columnDATALTCADFNC
            End Get
        End Property
        
        Friend ReadOnly Property TIPFNCColumn As DataColumn
            Get
                Return Me.columnTIPFNC
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As T0100361Row
            Get
                Return CType(Me.Rows(index),T0100361Row)
            End Get
        End Property
        
        Public Event T0100361RowChanged As T0100361RowChangeEventHandler
        
        Public Event T0100361RowChanging As T0100361RowChangeEventHandler
        
        Public Event T0100361RowDeleted As T0100361RowChangeEventHandler
        
        Public Event T0100361RowDeleting As T0100361RowChangeEventHandler
        
        Public Overloads Sub AddT0100361Row(ByVal row As T0100361Row)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function AddT0100361Row( _
                    ByVal CODFNC As Decimal,  _
                    ByVal NOMFNC As String,  _
                    ByVal CODDPT As Decimal,  _
                    ByVal CODSEC As Decimal,  _
                    ByVal CODEMP As Decimal,  _
                    ByVal DATADSFNC As Date,  _
                    ByVal DATDEMFNC As Date,  _
                    ByVal ENDFNC As String,  _
                    ByVal CODCID As Decimal,  _
                    ByVal CODBAIFNC As Decimal,  _
                    ByVal CODCEPFNC As Decimal,  _
                    ByVal NUMTLFFNC As String,  _
                    ByVal CODFILFNC As Decimal,  _
                    ByVal CODSEXFNC As String,  _
                    ByVal CODDRT As Decimal,  _
                    ByVal CODDIV As Decimal,  _
                    ByVal CODCENCST As String,  _
                    ByVal CODGRPPGTFNC As Decimal,  _
                    ByVal CODSETFNC As Decimal,  _
                    ByVal NUMCNTCRRFNC As String,  _
                    ByVal CODAGEBCOFNC As Decimal,  _
                    ByVal CODBCOFNC As Decimal,  _
                    ByVal CODCGRFNC As Decimal,  _
                    ByVal NUMCPFFNC As String,  _
                    ByVal CODSNDFNC As Decimal,  _
                    ByVal DATNSC As Date,  _
                    ByVal CODUNDNGC As Decimal,  _
                    ByVal CODFILEMP As Decimal,  _
                    ByVal CODUNDREG As Decimal,  _
                    ByVal CODSGMMCDCTB As Decimal,  _
                    ByVal NUMRMLTLF As String,  _
                    ByVal DESPSWFNCPAD As String,  _
                    ByVal DESPSWCDF As String,  _
                    ByVal DESENDCREETNFNC As String,  _
                    ByVal CODNIVFNC As Decimal,  _
                    ByVal INDTRBFNC As Decimal,  _
                    ByVal NUMCARCCP As String,  _
                    ByVal NUMCARRLP As String,  _
                    ByVal DATVLDCARCCP As Date,  _
                    ByVal DATVLDCARRLP As Date,  _
                    ByVal DATPRVDEMFNC As Date,  _
                    ByVal NUMCPF As String,  _
                    ByVal DATALTCADFNC As Date,  _
                    ByVal TIPFNC As String) As T0100361Row
            Dim rowT0100361Row As T0100361Row = CType(Me.NewRow,T0100361Row)
            rowT0100361Row.ItemArray = New Object() {CODFNC, NOMFNC, CODDPT, CODSEC, CODEMP, DATADSFNC, DATDEMFNC, ENDFNC, CODCID, CODBAIFNC, CODCEPFNC, NUMTLFFNC, CODFILFNC, CODSEXFNC, CODDRT, CODDIV, CODCENCST, CODGRPPGTFNC, CODSETFNC, NUMCNTCRRFNC, CODAGEBCOFNC, CODBCOFNC, CODCGRFNC, NUMCPFFNC, CODSNDFNC, DATNSC, CODUNDNGC, CODFILEMP, CODUNDREG, CODSGMMCDCTB, NUMRMLTLF, DESPSWFNCPAD, DESPSWCDF, DESENDCREETNFNC, CODNIVFNC, INDTRBFNC, NUMCARCCP, NUMCARRLP, DATVLDCARCCP, DATVLDCARRLP, DATPRVDEMFNC, NUMCPF, DATALTCADFNC, TIPFNC}
            Me.Rows.Add(rowT0100361Row)
            Return rowT0100361Row
        End Function
        
        Public Function FindByCODFNC(ByVal CODFNC As Decimal) As T0100361Row
            Return CType(Me.Rows.Find(New Object() {CODFNC}),T0100361Row)
        End Function
        
        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As DataTable
            Dim cln As T0100361DataTable = CType(MyBase.Clone,T0100361DataTable)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function CreateInstance() As DataTable
            Return New T0100361DataTable
        End Function
        
        Friend Sub InitVars()
            Me.columnCODFNC = Me.Columns("CODFNC")
            Me.columnNOMFNC = Me.Columns("NOMFNC")
            Me.columnCODDPT = Me.Columns("CODDPT")
            Me.columnCODSEC = Me.Columns("CODSEC")
            Me.columnCODEMP = Me.Columns("CODEMP")
            Me.columnDATADSFNC = Me.Columns("DATADSFNC")
            Me.columnDATDEMFNC = Me.Columns("DATDEMFNC")
            Me.columnENDFNC = Me.Columns("ENDFNC")
            Me.columnCODCID = Me.Columns("CODCID")
            Me.columnCODBAIFNC = Me.Columns("CODBAIFNC")
            Me.columnCODCEPFNC = Me.Columns("CODCEPFNC")
            Me.columnNUMTLFFNC = Me.Columns("NUMTLFFNC")
            Me.columnCODFILFNC = Me.Columns("CODFILFNC")
            Me.columnCODSEXFNC = Me.Columns("CODSEXFNC")
            Me.columnCODDRT = Me.Columns("CODDRT")
            Me.columnCODDIV = Me.Columns("CODDIV")
            Me.columnCODCENCST = Me.Columns("CODCENCST")
            Me.columnCODGRPPGTFNC = Me.Columns("CODGRPPGTFNC")
            Me.columnCODSETFNC = Me.Columns("CODSETFNC")
            Me.columnNUMCNTCRRFNC = Me.Columns("NUMCNTCRRFNC")
            Me.columnCODAGEBCOFNC = Me.Columns("CODAGEBCOFNC")
            Me.columnCODBCOFNC = Me.Columns("CODBCOFNC")
            Me.columnCODCGRFNC = Me.Columns("CODCGRFNC")
            Me.columnNUMCPFFNC = Me.Columns("NUMCPFFNC")
            Me.columnCODSNDFNC = Me.Columns("CODSNDFNC")
            Me.columnDATNSC = Me.Columns("DATNSC")
            Me.columnCODUNDNGC = Me.Columns("CODUNDNGC")
            Me.columnCODFILEMP = Me.Columns("CODFILEMP")
            Me.columnCODUNDREG = Me.Columns("CODUNDREG")
            Me.columnCODSGMMCDCTB = Me.Columns("CODSGMMCDCTB")
            Me.columnNUMRMLTLF = Me.Columns("NUMRMLTLF")
            Me.columnDESPSWFNCPAD = Me.Columns("DESPSWFNCPAD")
            Me.columnDESPSWCDF = Me.Columns("DESPSWCDF")
            Me.columnDESENDCREETNFNC = Me.Columns("DESENDCREETNFNC")
            Me.columnCODNIVFNC = Me.Columns("CODNIVFNC")
            Me.columnINDTRBFNC = Me.Columns("INDTRBFNC")
            Me.columnNUMCARCCP = Me.Columns("NUMCARCCP")
            Me.columnNUMCARRLP = Me.Columns("NUMCARRLP")
            Me.columnDATVLDCARCCP = Me.Columns("DATVLDCARCCP")
            Me.columnDATVLDCARRLP = Me.Columns("DATVLDCARRLP")
            Me.columnDATPRVDEMFNC = Me.Columns("DATPRVDEMFNC")
            Me.columnNUMCPF = Me.Columns("NUMCPF")
            Me.columnDATALTCADFNC = Me.Columns("DATALTCADFNC")
            Me.columnTIPFNC = Me.Columns("TIPFNC")
        End Sub
        
        Private Sub InitClass()
            Me.columnCODFNC = New DataColumn("CODFNC", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCODFNC)
            Me.columnNOMFNC = New DataColumn("NOMFNC", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnNOMFNC)
            Me.columnCODDPT = New DataColumn("CODDPT", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCODDPT)
            Me.columnCODSEC = New DataColumn("CODSEC", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCODSEC)
            Me.columnCODEMP = New DataColumn("CODEMP", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCODEMP)
            Me.columnDATADSFNC = New DataColumn("DATADSFNC", GetType(System.DateTime), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnDATADSFNC)
            Me.columnDATDEMFNC = New DataColumn("DATDEMFNC", GetType(System.DateTime), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnDATDEMFNC)
            Me.columnENDFNC = New DataColumn("ENDFNC", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnENDFNC)
            Me.columnCODCID = New DataColumn("CODCID", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCODCID)
            Me.columnCODBAIFNC = New DataColumn("CODBAIFNC", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCODBAIFNC)
            Me.columnCODCEPFNC = New DataColumn("CODCEPFNC", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCODCEPFNC)
            Me.columnNUMTLFFNC = New DataColumn("NUMTLFFNC", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnNUMTLFFNC)
            Me.columnCODFILFNC = New DataColumn("CODFILFNC", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCODFILFNC)
            Me.columnCODSEXFNC = New DataColumn("CODSEXFNC", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCODSEXFNC)
            Me.columnCODDRT = New DataColumn("CODDRT", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCODDRT)
            Me.columnCODDIV = New DataColumn("CODDIV", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCODDIV)
            Me.columnCODCENCST = New DataColumn("CODCENCST", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCODCENCST)
            Me.columnCODGRPPGTFNC = New DataColumn("CODGRPPGTFNC", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCODGRPPGTFNC)
            Me.columnCODSETFNC = New DataColumn("CODSETFNC", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCODSETFNC)
            Me.columnNUMCNTCRRFNC = New DataColumn("NUMCNTCRRFNC", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnNUMCNTCRRFNC)
            Me.columnCODAGEBCOFNC = New DataColumn("CODAGEBCOFNC", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCODAGEBCOFNC)
            Me.columnCODBCOFNC = New DataColumn("CODBCOFNC", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCODBCOFNC)
            Me.columnCODCGRFNC = New DataColumn("CODCGRFNC", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCODCGRFNC)
            Me.columnNUMCPFFNC = New DataColumn("NUMCPFFNC", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnNUMCPFFNC)
            Me.columnCODSNDFNC = New DataColumn("CODSNDFNC", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCODSNDFNC)
            Me.columnDATNSC = New DataColumn("DATNSC", GetType(System.DateTime), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnDATNSC)
            Me.columnCODUNDNGC = New DataColumn("CODUNDNGC", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCODUNDNGC)
            Me.columnCODFILEMP = New DataColumn("CODFILEMP", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCODFILEMP)
            Me.columnCODUNDREG = New DataColumn("CODUNDREG", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCODUNDREG)
            Me.columnCODSGMMCDCTB = New DataColumn("CODSGMMCDCTB", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCODSGMMCDCTB)
            Me.columnNUMRMLTLF = New DataColumn("NUMRMLTLF", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnNUMRMLTLF)
            Me.columnDESPSWFNCPAD = New DataColumn("DESPSWFNCPAD", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnDESPSWFNCPAD)
            Me.columnDESPSWCDF = New DataColumn("DESPSWCDF", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnDESPSWCDF)
            Me.columnDESENDCREETNFNC = New DataColumn("DESENDCREETNFNC", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnDESENDCREETNFNC)
            Me.columnCODNIVFNC = New DataColumn("CODNIVFNC", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCODNIVFNC)
            Me.columnINDTRBFNC = New DataColumn("INDTRBFNC", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnINDTRBFNC)
            Me.columnNUMCARCCP = New DataColumn("NUMCARCCP", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnNUMCARCCP)
            Me.columnNUMCARRLP = New DataColumn("NUMCARRLP", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnNUMCARRLP)
            Me.columnDATVLDCARCCP = New DataColumn("DATVLDCARCCP", GetType(System.DateTime), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnDATVLDCARCCP)
            Me.columnDATVLDCARRLP = New DataColumn("DATVLDCARRLP", GetType(System.DateTime), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnDATVLDCARRLP)
            Me.columnDATPRVDEMFNC = New DataColumn("DATPRVDEMFNC", GetType(System.DateTime), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnDATPRVDEMFNC)
            Me.columnNUMCPF = New DataColumn("NUMCPF", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnNUMCPF)
            Me.columnDATALTCADFNC = New DataColumn("DATALTCADFNC", GetType(System.DateTime), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnDATALTCADFNC)
            Me.columnTIPFNC = New DataColumn("TIPFNC", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnTIPFNC)
            Me.Constraints.Add(New UniqueConstraint("DatasetFuncionarioKey1", New DataColumn() {Me.columnCODFNC}, true))
            Me.columnCODFNC.AllowDBNull = false
            Me.columnCODFNC.Unique = true
            Me.columnNOMFNC.AllowDBNull = false
            Me.columnCODDPT.AllowDBNull = false
            Me.columnCODSEC.AllowDBNull = false
            Me.columnCODEMP.AllowDBNull = false
            Me.columnDATADSFNC.AllowDBNull = false
            Me.columnENDFNC.AllowDBNull = false
            Me.columnCODBAIFNC.AllowDBNull = false
            Me.columnCODCEPFNC.AllowDBNull = false
            Me.columnCODSEXFNC.AllowDBNull = false
            Me.columnCODDRT.AllowDBNull = false
            Me.columnCODDIV.AllowDBNull = false
            Me.columnCODCENCST.AllowDBNull = false
            Me.columnCODGRPPGTFNC.AllowDBNull = false
            Me.columnCODSETFNC.AllowDBNull = false
            Me.columnCODCGRFNC.AllowDBNull = false
            Me.columnCODSNDFNC.AllowDBNull = false
            Me.columnNUMRMLTLF.AllowDBNull = false
            Me.columnDESENDCREETNFNC.AllowDBNull = false
            Me.columnCODNIVFNC.AllowDBNull = false
            Me.columnNUMCARCCP.AllowDBNull = false
            Me.columnNUMCARRLP.AllowDBNull = false
            Me.columnDATVLDCARCCP.AllowDBNull = false
            Me.columnDATVLDCARRLP.AllowDBNull = false
        End Sub
        
        Public Function NewT0100361Row() As T0100361Row
            Return CType(Me.NewRow,T0100361Row)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New T0100361Row(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(T0100361Row)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.T0100361RowChangedEvent) Is Nothing) Then
                RaiseEvent T0100361RowChanged(Me, New T0100361RowChangeEvent(CType(e.Row,T0100361Row), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.T0100361RowChangingEvent) Is Nothing) Then
                RaiseEvent T0100361RowChanging(Me, New T0100361RowChangeEvent(CType(e.Row,T0100361Row), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.T0100361RowDeletedEvent) Is Nothing) Then
                RaiseEvent T0100361RowDeleted(Me, New T0100361RowChangeEvent(CType(e.Row,T0100361Row), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.T0100361RowDeletingEvent) Is Nothing) Then
                RaiseEvent T0100361RowDeleting(Me, New T0100361RowChangeEvent(CType(e.Row,T0100361Row), e.Action))
            End If
        End Sub
        
        Public Sub RemoveT0100361Row(ByVal row As T0100361Row)
            Me.Rows.Remove(row)
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class T0100361Row
        Inherits DataRow
        
        Private tableT0100361 As T0100361DataTable
        
        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tableT0100361 = CType(Me.Table,T0100361DataTable)
        End Sub
        
        Public Property CODFNC As Decimal
            Get
                Return CType(Me(Me.tableT0100361.CODFNCColumn),Decimal)
            End Get
            Set
                Me(Me.tableT0100361.CODFNCColumn) = value
            End Set
        End Property
        
        Public Property NOMFNC As String
            Get
                Return CType(Me(Me.tableT0100361.NOMFNCColumn),String)
            End Get
            Set
                Me(Me.tableT0100361.NOMFNCColumn) = value
            End Set
        End Property
        
        Public Property CODDPT As Decimal
            Get
                Return CType(Me(Me.tableT0100361.CODDPTColumn),Decimal)
            End Get
            Set
                Me(Me.tableT0100361.CODDPTColumn) = value
            End Set
        End Property
        
        Public Property CODSEC As Decimal
            Get
                Return CType(Me(Me.tableT0100361.CODSECColumn),Decimal)
            End Get
            Set
                Me(Me.tableT0100361.CODSECColumn) = value
            End Set
        End Property
        
        Public Property CODEMP As Decimal
            Get
                Return CType(Me(Me.tableT0100361.CODEMPColumn),Decimal)
            End Get
            Set
                Me(Me.tableT0100361.CODEMPColumn) = value
            End Set
        End Property
        
        Public Property DATADSFNC As Date
            Get
                Return CType(Me(Me.tableT0100361.DATADSFNCColumn),Date)
            End Get
            Set
                Me(Me.tableT0100361.DATADSFNCColumn) = value
            End Set
        End Property
        
        Public Property DATDEMFNC As Date
            Get
                Try 
                    Return CType(Me(Me.tableT0100361.DATDEMFNCColumn),Date)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableT0100361.DATDEMFNCColumn) = value
            End Set
        End Property
        
        Public Property ENDFNC As String
            Get
                Return CType(Me(Me.tableT0100361.ENDFNCColumn),String)
            End Get
            Set
                Me(Me.tableT0100361.ENDFNCColumn) = value
            End Set
        End Property
        
        Public Property CODCID As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableT0100361.CODCIDColumn),Decimal)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableT0100361.CODCIDColumn) = value
            End Set
        End Property
        
        Public Property CODBAIFNC As Decimal
            Get
                Return CType(Me(Me.tableT0100361.CODBAIFNCColumn),Decimal)
            End Get
            Set
                Me(Me.tableT0100361.CODBAIFNCColumn) = value
            End Set
        End Property
        
        Public Property CODCEPFNC As Decimal
            Get
                Return CType(Me(Me.tableT0100361.CODCEPFNCColumn),Decimal)
            End Get
            Set
                Me(Me.tableT0100361.CODCEPFNCColumn) = value
            End Set
        End Property
        
        Public Property NUMTLFFNC As String
            Get
                Try 
                    Return CType(Me(Me.tableT0100361.NUMTLFFNCColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableT0100361.NUMTLFFNCColumn) = value
            End Set
        End Property
        
        Public Property CODFILFNC As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableT0100361.CODFILFNCColumn),Decimal)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableT0100361.CODFILFNCColumn) = value
            End Set
        End Property
        
        Public Property CODSEXFNC As String
            Get
                Return CType(Me(Me.tableT0100361.CODSEXFNCColumn),String)
            End Get
            Set
                Me(Me.tableT0100361.CODSEXFNCColumn) = value
            End Set
        End Property
        
        Public Property CODDRT As Decimal
            Get
                Return CType(Me(Me.tableT0100361.CODDRTColumn),Decimal)
            End Get
            Set
                Me(Me.tableT0100361.CODDRTColumn) = value
            End Set
        End Property
        
        Public Property CODDIV As Decimal
            Get
                Return CType(Me(Me.tableT0100361.CODDIVColumn),Decimal)
            End Get
            Set
                Me(Me.tableT0100361.CODDIVColumn) = value
            End Set
        End Property
        
        Public Property CODCENCST As String
            Get
                Return CType(Me(Me.tableT0100361.CODCENCSTColumn),String)
            End Get
            Set
                Me(Me.tableT0100361.CODCENCSTColumn) = value
            End Set
        End Property
        
        Public Property CODGRPPGTFNC As Decimal
            Get
                Return CType(Me(Me.tableT0100361.CODGRPPGTFNCColumn),Decimal)
            End Get
            Set
                Me(Me.tableT0100361.CODGRPPGTFNCColumn) = value
            End Set
        End Property
        
        Public Property CODSETFNC As Decimal
            Get
                Return CType(Me(Me.tableT0100361.CODSETFNCColumn),Decimal)
            End Get
            Set
                Me(Me.tableT0100361.CODSETFNCColumn) = value
            End Set
        End Property
        
        Public Property NUMCNTCRRFNC As String
            Get
                Try 
                    Return CType(Me(Me.tableT0100361.NUMCNTCRRFNCColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableT0100361.NUMCNTCRRFNCColumn) = value
            End Set
        End Property
        
        Public Property CODAGEBCOFNC As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableT0100361.CODAGEBCOFNCColumn),Decimal)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableT0100361.CODAGEBCOFNCColumn) = value
            End Set
        End Property
        
        Public Property CODBCOFNC As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableT0100361.CODBCOFNCColumn),Decimal)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableT0100361.CODBCOFNCColumn) = value
            End Set
        End Property
        
        Public Property CODCGRFNC As Decimal
            Get
                Return CType(Me(Me.tableT0100361.CODCGRFNCColumn),Decimal)
            End Get
            Set
                Me(Me.tableT0100361.CODCGRFNCColumn) = value
            End Set
        End Property
        
        Public Property NUMCPFFNC As String
            Get
                Try 
                    Return CType(Me(Me.tableT0100361.NUMCPFFNCColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableT0100361.NUMCPFFNCColumn) = value
            End Set
        End Property
        
        Public Property CODSNDFNC As Decimal
            Get
                Return CType(Me(Me.tableT0100361.CODSNDFNCColumn),Decimal)
            End Get
            Set
                Me(Me.tableT0100361.CODSNDFNCColumn) = value
            End Set
        End Property
        
        Public Property DATNSC As Date
            Get
                Try 
                    Return CType(Me(Me.tableT0100361.DATNSCColumn),Date)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableT0100361.DATNSCColumn) = value
            End Set
        End Property
        
        Public Property CODUNDNGC As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableT0100361.CODUNDNGCColumn),Decimal)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableT0100361.CODUNDNGCColumn) = value
            End Set
        End Property
        
        Public Property CODFILEMP As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableT0100361.CODFILEMPColumn),Decimal)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableT0100361.CODFILEMPColumn) = value
            End Set
        End Property
        
        Public Property CODUNDREG As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableT0100361.CODUNDREGColumn),Decimal)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableT0100361.CODUNDREGColumn) = value
            End Set
        End Property
        
        Public Property CODSGMMCDCTB As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableT0100361.CODSGMMCDCTBColumn),Decimal)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableT0100361.CODSGMMCDCTBColumn) = value
            End Set
        End Property
        
        Public Property NUMRMLTLF As String
            Get
                Return CType(Me(Me.tableT0100361.NUMRMLTLFColumn),String)
            End Get
            Set
                Me(Me.tableT0100361.NUMRMLTLFColumn) = value
            End Set
        End Property
        
        Public Property DESPSWFNCPAD As String
            Get
                Try 
                    Return CType(Me(Me.tableT0100361.DESPSWFNCPADColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableT0100361.DESPSWFNCPADColumn) = value
            End Set
        End Property
        
        Public Property DESPSWCDF As String
            Get
                Try 
                    Return CType(Me(Me.tableT0100361.DESPSWCDFColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableT0100361.DESPSWCDFColumn) = value
            End Set
        End Property
        
        Public Property DESENDCREETNFNC As String
            Get
                Return CType(Me(Me.tableT0100361.DESENDCREETNFNCColumn),String)
            End Get
            Set
                Me(Me.tableT0100361.DESENDCREETNFNCColumn) = value
            End Set
        End Property
        
        Public Property CODNIVFNC As Decimal
            Get
                Return CType(Me(Me.tableT0100361.CODNIVFNCColumn),Decimal)
            End Get
            Set
                Me(Me.tableT0100361.CODNIVFNCColumn) = value
            End Set
        End Property
        
        Public Property INDTRBFNC As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableT0100361.INDTRBFNCColumn),Decimal)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableT0100361.INDTRBFNCColumn) = value
            End Set
        End Property
        
        Public Property NUMCARCCP As String
            Get
                Return CType(Me(Me.tableT0100361.NUMCARCCPColumn),String)
            End Get
            Set
                Me(Me.tableT0100361.NUMCARCCPColumn) = value
            End Set
        End Property
        
        Public Property NUMCARRLP As String
            Get
                Return CType(Me(Me.tableT0100361.NUMCARRLPColumn),String)
            End Get
            Set
                Me(Me.tableT0100361.NUMCARRLPColumn) = value
            End Set
        End Property
        
        Public Property DATVLDCARCCP As Date
            Get
                Return CType(Me(Me.tableT0100361.DATVLDCARCCPColumn),Date)
            End Get
            Set
                Me(Me.tableT0100361.DATVLDCARCCPColumn) = value
            End Set
        End Property
        
        Public Property DATVLDCARRLP As Date
            Get
                Return CType(Me(Me.tableT0100361.DATVLDCARRLPColumn),Date)
            End Get
            Set
                Me(Me.tableT0100361.DATVLDCARRLPColumn) = value
            End Set
        End Property
        
        Public Property DATPRVDEMFNC As Date
            Get
                Try 
                    Return CType(Me(Me.tableT0100361.DATPRVDEMFNCColumn),Date)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableT0100361.DATPRVDEMFNCColumn) = value
            End Set
        End Property
        
        Public Property NUMCPF As String
            Get
                Try 
                    Return CType(Me(Me.tableT0100361.NUMCPFColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableT0100361.NUMCPFColumn) = value
            End Set
        End Property
        
        Public Property DATALTCADFNC As Date
            Get
                Try 
                    Return CType(Me(Me.tableT0100361.DATALTCADFNCColumn),Date)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableT0100361.DATALTCADFNCColumn) = value
            End Set
        End Property
        
        Public Property TIPFNC As String
            Get
                Try 
                    Return CType(Me(Me.tableT0100361.TIPFNCColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableT0100361.TIPFNCColumn) = value
            End Set
        End Property
        
        Public Function IsDATDEMFNCNull() As Boolean
            Return Me.IsNull(Me.tableT0100361.DATDEMFNCColumn)
        End Function
        
        Public Sub SetDATDEMFNCNull()
            Me(Me.tableT0100361.DATDEMFNCColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsCODCIDNull() As Boolean
            Return Me.IsNull(Me.tableT0100361.CODCIDColumn)
        End Function
        
        Public Sub SetCODCIDNull()
            Me(Me.tableT0100361.CODCIDColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsNUMTLFFNCNull() As Boolean
            Return Me.IsNull(Me.tableT0100361.NUMTLFFNCColumn)
        End Function
        
        Public Sub SetNUMTLFFNCNull()
            Me(Me.tableT0100361.NUMTLFFNCColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsCODFILFNCNull() As Boolean
            Return Me.IsNull(Me.tableT0100361.CODFILFNCColumn)
        End Function
        
        Public Sub SetCODFILFNCNull()
            Me(Me.tableT0100361.CODFILFNCColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsNUMCNTCRRFNCNull() As Boolean
            Return Me.IsNull(Me.tableT0100361.NUMCNTCRRFNCColumn)
        End Function
        
        Public Sub SetNUMCNTCRRFNCNull()
            Me(Me.tableT0100361.NUMCNTCRRFNCColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsCODAGEBCOFNCNull() As Boolean
            Return Me.IsNull(Me.tableT0100361.CODAGEBCOFNCColumn)
        End Function
        
        Public Sub SetCODAGEBCOFNCNull()
            Me(Me.tableT0100361.CODAGEBCOFNCColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsCODBCOFNCNull() As Boolean
            Return Me.IsNull(Me.tableT0100361.CODBCOFNCColumn)
        End Function
        
        Public Sub SetCODBCOFNCNull()
            Me(Me.tableT0100361.CODBCOFNCColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsNUMCPFFNCNull() As Boolean
            Return Me.IsNull(Me.tableT0100361.NUMCPFFNCColumn)
        End Function
        
        Public Sub SetNUMCPFFNCNull()
            Me(Me.tableT0100361.NUMCPFFNCColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsDATNSCNull() As Boolean
            Return Me.IsNull(Me.tableT0100361.DATNSCColumn)
        End Function
        
        Public Sub SetDATNSCNull()
            Me(Me.tableT0100361.DATNSCColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsCODUNDNGCNull() As Boolean
            Return Me.IsNull(Me.tableT0100361.CODUNDNGCColumn)
        End Function
        
        Public Sub SetCODUNDNGCNull()
            Me(Me.tableT0100361.CODUNDNGCColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsCODFILEMPNull() As Boolean
            Return Me.IsNull(Me.tableT0100361.CODFILEMPColumn)
        End Function
        
        Public Sub SetCODFILEMPNull()
            Me(Me.tableT0100361.CODFILEMPColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsCODUNDREGNull() As Boolean
            Return Me.IsNull(Me.tableT0100361.CODUNDREGColumn)
        End Function
        
        Public Sub SetCODUNDREGNull()
            Me(Me.tableT0100361.CODUNDREGColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsCODSGMMCDCTBNull() As Boolean
            Return Me.IsNull(Me.tableT0100361.CODSGMMCDCTBColumn)
        End Function
        
        Public Sub SetCODSGMMCDCTBNull()
            Me(Me.tableT0100361.CODSGMMCDCTBColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsDESPSWFNCPADNull() As Boolean
            Return Me.IsNull(Me.tableT0100361.DESPSWFNCPADColumn)
        End Function
        
        Public Sub SetDESPSWFNCPADNull()
            Me(Me.tableT0100361.DESPSWFNCPADColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsDESPSWCDFNull() As Boolean
            Return Me.IsNull(Me.tableT0100361.DESPSWCDFColumn)
        End Function
        
        Public Sub SetDESPSWCDFNull()
            Me(Me.tableT0100361.DESPSWCDFColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsINDTRBFNCNull() As Boolean
            Return Me.IsNull(Me.tableT0100361.INDTRBFNCColumn)
        End Function
        
        Public Sub SetINDTRBFNCNull()
            Me(Me.tableT0100361.INDTRBFNCColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsDATPRVDEMFNCNull() As Boolean
            Return Me.IsNull(Me.tableT0100361.DATPRVDEMFNCColumn)
        End Function
        
        Public Sub SetDATPRVDEMFNCNull()
            Me(Me.tableT0100361.DATPRVDEMFNCColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsNUMCPFNull() As Boolean
            Return Me.IsNull(Me.tableT0100361.NUMCPFColumn)
        End Function
        
        Public Sub SetNUMCPFNull()
            Me(Me.tableT0100361.NUMCPFColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsDATALTCADFNCNull() As Boolean
            Return Me.IsNull(Me.tableT0100361.DATALTCADFNCColumn)
        End Function
        
        Public Sub SetDATALTCADFNCNull()
            Me(Me.tableT0100361.DATALTCADFNCColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsTIPFNCNull() As Boolean
            Return Me.IsNull(Me.tableT0100361.TIPFNCColumn)
        End Function
        
        Public Sub SetTIPFNCNull()
            Me(Me.tableT0100361.TIPFNCColumn) = System.Convert.DBNull
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class T0100361RowChangeEvent
        Inherits EventArgs
        
        Private eventRow As T0100361Row
        
        Private eventAction As DataRowAction
        
        Public Sub New(ByVal row As T0100361Row, ByVal action As DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row As T0100361Row
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
