'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2407
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Data
Imports System.Runtime.Serialization
Imports System.Xml


<Serializable(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Diagnostics.DebuggerStepThrough(),  _
 System.ComponentModel.ToolboxItem(true)>  _
Public Class DatasetReservaSaldoFornecedor
    Inherits DataSet
    
    Private tableT0123159 As T0123159DataTable
    
    Public Sub New()
        MyBase.New
        Me.InitClass
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    Protected Sub New(ByVal info As SerializationInfo, ByVal context As StreamingContext)
        MyBase.New
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(System.String)),String)
        If (Not (strSchema) Is Nothing) Then
            Dim ds As DataSet = New DataSet
            ds.ReadXmlSchema(New XmlTextReader(New System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("T0123159")) Is Nothing) Then
                Me.Tables.Add(New T0123159DataTable(ds.Tables("T0123159")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.InitClass
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property T0123159 As T0123159DataTable
        Get
            Return Me.tableT0123159
        End Get
    End Property
    
    Public Overrides Function Clone() As DataSet
        Dim cln As DatasetReservaSaldoFornecedor = CType(MyBase.Clone,DatasetReservaSaldoFornecedor)
        cln.InitVars
        Return cln
    End Function
    
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As XmlReader)
        Me.Reset
        Dim ds As DataSet = New DataSet
        ds.ReadXml(reader)
        If (Not (ds.Tables("T0123159")) Is Nothing) Then
            Me.Tables.Add(New T0123159DataTable(ds.Tables("T0123159")))
        End If
        Me.DataSetName = ds.DataSetName
        Me.Prefix = ds.Prefix
        Me.Namespace = ds.Namespace
        Me.Locale = ds.Locale
        Me.CaseSensitive = ds.CaseSensitive
        Me.EnforceConstraints = ds.EnforceConstraints
        Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
        Me.InitVars
    End Sub
    
    Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
        Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
        Me.WriteXmlSchema(New XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return System.Xml.Schema.XmlSchema.Read(New XmlTextReader(stream), Nothing)
    End Function
    
    Friend Sub InitVars()
        Me.tableT0123159 = CType(Me.Tables("T0123159"),T0123159DataTable)
        If (Not (Me.tableT0123159) Is Nothing) Then
            Me.tableT0123159.InitVars
        End If
    End Sub
    
    Private Sub InitClass()
        Me.DataSetName = "DatasetReservaSaldoFornecedor"
        Me.Prefix = ""
        Me.Namespace = "http://tempuri.org/DatasetReservaSaldoFornecedor.xsd"
        Me.Locale = New System.Globalization.CultureInfo("en-US")
        Me.CaseSensitive = false
        Me.EnforceConstraints = true
        Me.tableT0123159 = New T0123159DataTable
        Me.Tables.Add(Me.tableT0123159)
    End Sub
    
    Private Function ShouldSerializeT0123159() As Boolean
        Return false
    End Function
    
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    Public Delegate Sub T0123159RowChangeEventHandler(ByVal sender As Object, ByVal e As T0123159RowChangeEvent)
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class T0123159DataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable
        
        Private columnCODFRN As DataColumn
        
        Private columnCODACOCMC As DataColumn
        
        Private columnTIPDSNDSCBNF As DataColumn
        
        Private columnVLRSLDRSVFRN As DataColumn
        
        Private columnFLGAPVACOCMC As DataColumn
        
        Private columnFLGLMTCNTCRR As DataColumn
        
        Private columnTIPACOCMC As DataColumn
        
        Private columnDATAPVACOCMC As DataColumn
        
        Private columnVLRRLZACOCMC As DataColumn
        
        Private columnDATACEACOCMC As DataColumn
        
        Private columnVLRACEACOCMC As DataColumn
        
        Private columnVLRACRCAPACOCMC As DataColumn
        
        Friend Sub New()
            MyBase.New("T0123159")
            Me.InitClass
        End Sub
        
        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Friend ReadOnly Property CODFRNColumn As DataColumn
            Get
                Return Me.columnCODFRN
            End Get
        End Property
        
        Friend ReadOnly Property CODACOCMCColumn As DataColumn
            Get
                Return Me.columnCODACOCMC
            End Get
        End Property
        
        Friend ReadOnly Property TIPDSNDSCBNFColumn As DataColumn
            Get
                Return Me.columnTIPDSNDSCBNF
            End Get
        End Property
        
        Friend ReadOnly Property VLRSLDRSVFRNColumn As DataColumn
            Get
                Return Me.columnVLRSLDRSVFRN
            End Get
        End Property
        
        Friend ReadOnly Property FLGAPVACOCMCColumn As DataColumn
            Get
                Return Me.columnFLGAPVACOCMC
            End Get
        End Property
        
        Friend ReadOnly Property FLGLMTCNTCRRColumn As DataColumn
            Get
                Return Me.columnFLGLMTCNTCRR
            End Get
        End Property
        
        Friend ReadOnly Property TIPACOCMCColumn As DataColumn
            Get
                Return Me.columnTIPACOCMC
            End Get
        End Property
        
        Friend ReadOnly Property DATAPVACOCMCColumn As DataColumn
            Get
                Return Me.columnDATAPVACOCMC
            End Get
        End Property
        
        Friend ReadOnly Property VLRRLZACOCMCColumn As DataColumn
            Get
                Return Me.columnVLRRLZACOCMC
            End Get
        End Property
        
        Friend ReadOnly Property DATACEACOCMCColumn As DataColumn
            Get
                Return Me.columnDATACEACOCMC
            End Get
        End Property
        
        Friend ReadOnly Property VLRACEACOCMCColumn As DataColumn
            Get
                Return Me.columnVLRACEACOCMC
            End Get
        End Property
        
        Friend ReadOnly Property VLRACRCAPACOCMCColumn As DataColumn
            Get
                Return Me.columnVLRACRCAPACOCMC
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As T0123159Row
            Get
                Return CType(Me.Rows(index),T0123159Row)
            End Get
        End Property
        
        Public Event T0123159RowChanged As T0123159RowChangeEventHandler
        
        Public Event T0123159RowChanging As T0123159RowChangeEventHandler
        
        Public Event T0123159RowDeleted As T0123159RowChangeEventHandler
        
        Public Event T0123159RowDeleting As T0123159RowChangeEventHandler
        
        Public Overloads Sub AddT0123159Row(ByVal row As T0123159Row)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function AddT0123159Row(ByVal CODFRN As Decimal, ByVal CODACOCMC As String, ByVal TIPDSNDSCBNF As Decimal, ByVal VLRSLDRSVFRN As Decimal, ByVal FLGAPVACOCMC As String, ByVal FLGLMTCNTCRR As String, ByVal TIPACOCMC As String, ByVal DATAPVACOCMC As Date, ByVal VLRRLZACOCMC As Decimal, ByVal DATACEACOCMC As Date, ByVal VLRACEACOCMC As Decimal, ByVal VLRACRCAPACOCMC As Decimal) As T0123159Row
            Dim rowT0123159Row As T0123159Row = CType(Me.NewRow,T0123159Row)
            rowT0123159Row.ItemArray = New Object() {CODFRN, CODACOCMC, TIPDSNDSCBNF, VLRSLDRSVFRN, FLGAPVACOCMC, FLGLMTCNTCRR, TIPACOCMC, DATAPVACOCMC, VLRRLZACOCMC, DATACEACOCMC, VLRACEACOCMC, VLRACRCAPACOCMC}
            Me.Rows.Add(rowT0123159Row)
            Return rowT0123159Row
        End Function
        
        Public Function FindByCODFRNCODACOCMCTIPDSNDSCBNF(ByVal CODFRN As Decimal, ByVal CODACOCMC As String, ByVal TIPDSNDSCBNF As Decimal) As T0123159Row
            Return CType(Me.Rows.Find(New Object() {CODFRN, CODACOCMC, TIPDSNDSCBNF}),T0123159Row)
        End Function
        
        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As DataTable
            Dim cln As T0123159DataTable = CType(MyBase.Clone,T0123159DataTable)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function CreateInstance() As DataTable
            Return New T0123159DataTable
        End Function
        
        Friend Sub InitVars()
            Me.columnCODFRN = Me.Columns("CODFRN")
            Me.columnCODACOCMC = Me.Columns("CODACOCMC")
            Me.columnTIPDSNDSCBNF = Me.Columns("TIPDSNDSCBNF")
            Me.columnVLRSLDRSVFRN = Me.Columns("VLRSLDRSVFRN")
            Me.columnFLGAPVACOCMC = Me.Columns("FLGAPVACOCMC")
            Me.columnFLGLMTCNTCRR = Me.Columns("FLGLMTCNTCRR")
            Me.columnTIPACOCMC = Me.Columns("TIPACOCMC")
            Me.columnDATAPVACOCMC = Me.Columns("DATAPVACOCMC")
            Me.columnVLRRLZACOCMC = Me.Columns("VLRRLZACOCMC")
            Me.columnDATACEACOCMC = Me.Columns("DATACEACOCMC")
            Me.columnVLRACEACOCMC = Me.Columns("VLRACEACOCMC")
            Me.columnVLRACRCAPACOCMC = Me.Columns("VLRACRCAPACOCMC")
        End Sub
        
        Private Sub InitClass()
            Me.columnCODFRN = New DataColumn("CODFRN", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCODFRN)
            Me.columnCODACOCMC = New DataColumn("CODACOCMC", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCODACOCMC)
            Me.columnTIPDSNDSCBNF = New DataColumn("TIPDSNDSCBNF", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnTIPDSNDSCBNF)
            Me.columnVLRSLDRSVFRN = New DataColumn("VLRSLDRSVFRN", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnVLRSLDRSVFRN)
            Me.columnFLGAPVACOCMC = New DataColumn("FLGAPVACOCMC", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnFLGAPVACOCMC)
            Me.columnFLGLMTCNTCRR = New DataColumn("FLGLMTCNTCRR", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnFLGLMTCNTCRR)
            Me.columnTIPACOCMC = New DataColumn("TIPACOCMC", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnTIPACOCMC)
            Me.columnDATAPVACOCMC = New DataColumn("DATAPVACOCMC", GetType(System.DateTime), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnDATAPVACOCMC)
            Me.columnVLRRLZACOCMC = New DataColumn("VLRRLZACOCMC", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnVLRRLZACOCMC)
            Me.columnDATACEACOCMC = New DataColumn("DATACEACOCMC", GetType(System.DateTime), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnDATACEACOCMC)
            Me.columnVLRACEACOCMC = New DataColumn("VLRACEACOCMC", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnVLRACEACOCMC)
            Me.columnVLRACRCAPACOCMC = New DataColumn("VLRACRCAPACOCMC", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnVLRACRCAPACOCMC)
            Me.Constraints.Add(New UniqueConstraint("DatasetReservaSaldoFornecedorKey1", New DataColumn() {Me.columnCODFRN, Me.columnCODACOCMC, Me.columnTIPDSNDSCBNF}, true))
            Me.columnCODFRN.AllowDBNull = false
            Me.columnCODACOCMC.AllowDBNull = false
            Me.columnTIPDSNDSCBNF.AllowDBNull = false
            Me.columnVLRSLDRSVFRN.AllowDBNull = false
            Me.columnFLGAPVACOCMC.AllowDBNull = false
            Me.columnFLGLMTCNTCRR.AllowDBNull = false
        End Sub
        
        Public Function NewT0123159Row() As T0123159Row
            Return CType(Me.NewRow,T0123159Row)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New T0123159Row(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(T0123159Row)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.T0123159RowChangedEvent) Is Nothing) Then
                RaiseEvent T0123159RowChanged(Me, New T0123159RowChangeEvent(CType(e.Row,T0123159Row), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.T0123159RowChangingEvent) Is Nothing) Then
                RaiseEvent T0123159RowChanging(Me, New T0123159RowChangeEvent(CType(e.Row,T0123159Row), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.T0123159RowDeletedEvent) Is Nothing) Then
                RaiseEvent T0123159RowDeleted(Me, New T0123159RowChangeEvent(CType(e.Row,T0123159Row), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.T0123159RowDeletingEvent) Is Nothing) Then
                RaiseEvent T0123159RowDeleting(Me, New T0123159RowChangeEvent(CType(e.Row,T0123159Row), e.Action))
            End If
        End Sub
        
        Public Sub RemoveT0123159Row(ByVal row As T0123159Row)
            Me.Rows.Remove(row)
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class T0123159Row
        Inherits DataRow
        
        Private tableT0123159 As T0123159DataTable
        
        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tableT0123159 = CType(Me.Table,T0123159DataTable)
        End Sub
        
        Public Property CODFRN As Decimal
            Get
                Return CType(Me(Me.tableT0123159.CODFRNColumn),Decimal)
            End Get
            Set
                Me(Me.tableT0123159.CODFRNColumn) = value
            End Set
        End Property
        
        Public Property CODACOCMC As String
            Get
                Return CType(Me(Me.tableT0123159.CODACOCMCColumn),String)
            End Get
            Set
                Me(Me.tableT0123159.CODACOCMCColumn) = value
            End Set
        End Property
        
        Public Property TIPDSNDSCBNF As Decimal
            Get
                Return CType(Me(Me.tableT0123159.TIPDSNDSCBNFColumn),Decimal)
            End Get
            Set
                Me(Me.tableT0123159.TIPDSNDSCBNFColumn) = value
            End Set
        End Property
        
        Public Property VLRSLDRSVFRN As Decimal
            Get
                Return CType(Me(Me.tableT0123159.VLRSLDRSVFRNColumn),Decimal)
            End Get
            Set
                Me(Me.tableT0123159.VLRSLDRSVFRNColumn) = value
            End Set
        End Property
        
        Public Property FLGAPVACOCMC As String
            Get
                Return CType(Me(Me.tableT0123159.FLGAPVACOCMCColumn),String)
            End Get
            Set
                Me(Me.tableT0123159.FLGAPVACOCMCColumn) = value
            End Set
        End Property
        
        Public Property FLGLMTCNTCRR As String
            Get
                Return CType(Me(Me.tableT0123159.FLGLMTCNTCRRColumn),String)
            End Get
            Set
                Me(Me.tableT0123159.FLGLMTCNTCRRColumn) = value
            End Set
        End Property
        
        Public Property TIPACOCMC As String
            Get
                Try 
                    Return CType(Me(Me.tableT0123159.TIPACOCMCColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableT0123159.TIPACOCMCColumn) = value
            End Set
        End Property
        
        Public Property DATAPVACOCMC As Date
            Get
                Try 
                    Return CType(Me(Me.tableT0123159.DATAPVACOCMCColumn),Date)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableT0123159.DATAPVACOCMCColumn) = value
            End Set
        End Property
        
        Public Property VLRRLZACOCMC As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableT0123159.VLRRLZACOCMCColumn),Decimal)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableT0123159.VLRRLZACOCMCColumn) = value
            End Set
        End Property
        
        Public Property DATACEACOCMC As Date
            Get
                Try 
                    Return CType(Me(Me.tableT0123159.DATACEACOCMCColumn),Date)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableT0123159.DATACEACOCMCColumn) = value
            End Set
        End Property
        
        Public Property VLRACEACOCMC As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableT0123159.VLRACEACOCMCColumn),Decimal)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableT0123159.VLRACEACOCMCColumn) = value
            End Set
        End Property
        
        Public Property VLRACRCAPACOCMC As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableT0123159.VLRACRCAPACOCMCColumn),Decimal)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableT0123159.VLRACRCAPACOCMCColumn) = value
            End Set
        End Property
        
        Public Function IsTIPACOCMCNull() As Boolean
            Return Me.IsNull(Me.tableT0123159.TIPACOCMCColumn)
        End Function
        
        Public Sub SetTIPACOCMCNull()
            Me(Me.tableT0123159.TIPACOCMCColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsDATAPVACOCMCNull() As Boolean
            Return Me.IsNull(Me.tableT0123159.DATAPVACOCMCColumn)
        End Function
        
        Public Sub SetDATAPVACOCMCNull()
            Me(Me.tableT0123159.DATAPVACOCMCColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsVLRRLZACOCMCNull() As Boolean
            Return Me.IsNull(Me.tableT0123159.VLRRLZACOCMCColumn)
        End Function
        
        Public Sub SetVLRRLZACOCMCNull()
            Me(Me.tableT0123159.VLRRLZACOCMCColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsDATACEACOCMCNull() As Boolean
            Return Me.IsNull(Me.tableT0123159.DATACEACOCMCColumn)
        End Function
        
        Public Sub SetDATACEACOCMCNull()
            Me(Me.tableT0123159.DATACEACOCMCColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsVLRACEACOCMCNull() As Boolean
            Return Me.IsNull(Me.tableT0123159.VLRACEACOCMCColumn)
        End Function
        
        Public Sub SetVLRACEACOCMCNull()
            Me(Me.tableT0123159.VLRACEACOCMCColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsVLRACRCAPACOCMCNull() As Boolean
            Return Me.IsNull(Me.tableT0123159.VLRACRCAPACOCMCColumn)
        End Function
        
        Public Sub SetVLRACRCAPACOCMCNull()
            Me(Me.tableT0123159.VLRACRCAPACOCMCColumn) = System.Convert.DBNull
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class T0123159RowChangeEvent
        Inherits EventArgs
        
        Private eventRow As T0123159Row
        
        Private eventAction As DataRowAction
        
        Public Sub New(ByVal row As T0123159Row, ByVal action As DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row As T0123159Row
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
