'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2407
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Data
Imports System.Runtime.Serialization
Imports System.Xml


<Serializable(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Diagnostics.DebuggerStepThrough(),  _
 System.ComponentModel.ToolboxItem(true)>  _
Public Class DatasetCalendarioAnual
    Inherits DataSet
    
    Private tableT0102321 As T0102321DataTable
    
    Public Sub New()
        MyBase.New
        Me.InitClass
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    Protected Sub New(ByVal info As SerializationInfo, ByVal context As StreamingContext)
        MyBase.New
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(System.String)),String)
        If (Not (strSchema) Is Nothing) Then
            Dim ds As DataSet = New DataSet
            ds.ReadXmlSchema(New XmlTextReader(New System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("T0102321")) Is Nothing) Then
                Me.Tables.Add(New T0102321DataTable(ds.Tables("T0102321")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.InitClass
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property T0102321 As T0102321DataTable
        Get
            Return Me.tableT0102321
        End Get
    End Property
    
    Public Overrides Function Clone() As DataSet
        Dim cln As DatasetCalendarioAnual = CType(MyBase.Clone,DatasetCalendarioAnual)
        cln.InitVars
        Return cln
    End Function
    
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As XmlReader)
        Me.Reset
        Dim ds As DataSet = New DataSet
        ds.ReadXml(reader)
        If (Not (ds.Tables("T0102321")) Is Nothing) Then
            Me.Tables.Add(New T0102321DataTable(ds.Tables("T0102321")))
        End If
        Me.DataSetName = ds.DataSetName
        Me.Prefix = ds.Prefix
        Me.Namespace = ds.Namespace
        Me.Locale = ds.Locale
        Me.CaseSensitive = ds.CaseSensitive
        Me.EnforceConstraints = ds.EnforceConstraints
        Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
        Me.InitVars
    End Sub
    
    Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
        Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
        Me.WriteXmlSchema(New XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return System.Xml.Schema.XmlSchema.Read(New XmlTextReader(stream), Nothing)
    End Function
    
    Friend Sub InitVars()
        Me.tableT0102321 = CType(Me.Tables("T0102321"),T0102321DataTable)
        If (Not (Me.tableT0102321) Is Nothing) Then
            Me.tableT0102321.InitVars
        End If
    End Sub
    
    Private Sub InitClass()
        Me.DataSetName = "DatasetCalendarioAnual"
        Me.Prefix = ""
        Me.Namespace = "http://tempuri.org/DatasetCalendarioAnual.xsd"
        Me.Locale = New System.Globalization.CultureInfo("en-US")
        Me.CaseSensitive = false
        Me.EnforceConstraints = true
        Me.tableT0102321 = New T0102321DataTable
        Me.Tables.Add(Me.tableT0102321)
    End Sub
    
    Private Function ShouldSerializeT0102321() As Boolean
        Return false
    End Function
    
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    Public Delegate Sub T0102321RowChangeEventHandler(ByVal sender As Object, ByVal e As T0102321RowChangeEvent)
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class T0102321DataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable
        
        Private columnDATREF As DataColumn
        
        Private columnFLGFATDIA As DataColumn
        
        Private columnNUMDIASMN As DataColumn
        
        Private columnFLGFRDBCO As DataColumn
        
        Private columnNUMSMNMES As DataColumn
        
        Private columnFLGDIAACEVGMMOT As DataColumn
        
        Private columnDATTRNLMTCTBACEVGM As DataColumn
        
        Private columnFLGFRDFRMPCO As DataColumn
        
        Private columnPERPRVVNDDIA As DataColumn
        
        Private columnDATREFSGNDIASMN As DataColumn
        
        Private columnFLGFRDLEGTRB As DataColumn
        
        Private columnFLGFRDNAC As DataColumn
        
        Private columnMESREF As DataColumn
        
        Private columnFLGFRDEPD As DataColumn
        
        Private columnFLGORDPGTREP As DataColumn
        
        Private columnANOMESREF As DataColumn
        
        Private columnINDFRDFOLPGT As DataColumn
        
        Friend Sub New()
            MyBase.New("T0102321")
            Me.InitClass
        End Sub
        
        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Friend ReadOnly Property DATREFColumn As DataColumn
            Get
                Return Me.columnDATREF
            End Get
        End Property
        
        Friend ReadOnly Property FLGFATDIAColumn As DataColumn
            Get
                Return Me.columnFLGFATDIA
            End Get
        End Property
        
        Friend ReadOnly Property NUMDIASMNColumn As DataColumn
            Get
                Return Me.columnNUMDIASMN
            End Get
        End Property
        
        Friend ReadOnly Property FLGFRDBCOColumn As DataColumn
            Get
                Return Me.columnFLGFRDBCO
            End Get
        End Property
        
        Friend ReadOnly Property NUMSMNMESColumn As DataColumn
            Get
                Return Me.columnNUMSMNMES
            End Get
        End Property
        
        Friend ReadOnly Property FLGDIAACEVGMMOTColumn As DataColumn
            Get
                Return Me.columnFLGDIAACEVGMMOT
            End Get
        End Property
        
        Friend ReadOnly Property DATTRNLMTCTBACEVGMColumn As DataColumn
            Get
                Return Me.columnDATTRNLMTCTBACEVGM
            End Get
        End Property
        
        Friend ReadOnly Property FLGFRDFRMPCOColumn As DataColumn
            Get
                Return Me.columnFLGFRDFRMPCO
            End Get
        End Property
        
        Friend ReadOnly Property PERPRVVNDDIAColumn As DataColumn
            Get
                Return Me.columnPERPRVVNDDIA
            End Get
        End Property
        
        Friend ReadOnly Property DATREFSGNDIASMNColumn As DataColumn
            Get
                Return Me.columnDATREFSGNDIASMN
            End Get
        End Property
        
        Friend ReadOnly Property FLGFRDLEGTRBColumn As DataColumn
            Get
                Return Me.columnFLGFRDLEGTRB
            End Get
        End Property
        
        Friend ReadOnly Property FLGFRDNACColumn As DataColumn
            Get
                Return Me.columnFLGFRDNAC
            End Get
        End Property
        
        Friend ReadOnly Property MESREFColumn As DataColumn
            Get
                Return Me.columnMESREF
            End Get
        End Property
        
        Friend ReadOnly Property FLGFRDEPDColumn As DataColumn
            Get
                Return Me.columnFLGFRDEPD
            End Get
        End Property
        
        Friend ReadOnly Property FLGORDPGTREPColumn As DataColumn
            Get
                Return Me.columnFLGORDPGTREP
            End Get
        End Property
        
        Friend ReadOnly Property ANOMESREFColumn As DataColumn
            Get
                Return Me.columnANOMESREF
            End Get
        End Property
        
        Friend ReadOnly Property INDFRDFOLPGTColumn As DataColumn
            Get
                Return Me.columnINDFRDFOLPGT
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As T0102321Row
            Get
                Return CType(Me.Rows(index),T0102321Row)
            End Get
        End Property
        
        Public Event T0102321RowChanged As T0102321RowChangeEventHandler
        
        Public Event T0102321RowChanging As T0102321RowChangeEventHandler
        
        Public Event T0102321RowDeleted As T0102321RowChangeEventHandler
        
        Public Event T0102321RowDeleting As T0102321RowChangeEventHandler
        
        Public Overloads Sub AddT0102321Row(ByVal row As T0102321Row)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function AddT0102321Row( _
                    ByVal DATREF As Date,  _
                    ByVal FLGFATDIA As String,  _
                    ByVal NUMDIASMN As Decimal,  _
                    ByVal FLGFRDBCO As String,  _
                    ByVal NUMSMNMES As Decimal,  _
                    ByVal FLGDIAACEVGMMOT As String,  _
                    ByVal DATTRNLMTCTBACEVGM As Date,  _
                    ByVal FLGFRDFRMPCO As String,  _
                    ByVal PERPRVVNDDIA As Decimal,  _
                    ByVal DATREFSGNDIASMN As Date,  _
                    ByVal FLGFRDLEGTRB As String,  _
                    ByVal FLGFRDNAC As String,  _
                    ByVal MESREF As Decimal,  _
                    ByVal FLGFRDEPD As String,  _
                    ByVal FLGORDPGTREP As String,  _
                    ByVal ANOMESREF As Decimal,  _
                    ByVal INDFRDFOLPGT As Decimal) As T0102321Row
            Dim rowT0102321Row As T0102321Row = CType(Me.NewRow,T0102321Row)
            rowT0102321Row.ItemArray = New Object() {DATREF, FLGFATDIA, NUMDIASMN, FLGFRDBCO, NUMSMNMES, FLGDIAACEVGMMOT, DATTRNLMTCTBACEVGM, FLGFRDFRMPCO, PERPRVVNDDIA, DATREFSGNDIASMN, FLGFRDLEGTRB, FLGFRDNAC, MESREF, FLGFRDEPD, FLGORDPGTREP, ANOMESREF, INDFRDFOLPGT}
            Me.Rows.Add(rowT0102321Row)
            Return rowT0102321Row
        End Function
        
        Public Function FindByDATREF(ByVal DATREF As Date) As T0102321Row
            Return CType(Me.Rows.Find(New Object() {DATREF}),T0102321Row)
        End Function
        
        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As DataTable
            Dim cln As T0102321DataTable = CType(MyBase.Clone,T0102321DataTable)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function CreateInstance() As DataTable
            Return New T0102321DataTable
        End Function
        
        Friend Sub InitVars()
            Me.columnDATREF = Me.Columns("DATREF")
            Me.columnFLGFATDIA = Me.Columns("FLGFATDIA")
            Me.columnNUMDIASMN = Me.Columns("NUMDIASMN")
            Me.columnFLGFRDBCO = Me.Columns("FLGFRDBCO")
            Me.columnNUMSMNMES = Me.Columns("NUMSMNMES")
            Me.columnFLGDIAACEVGMMOT = Me.Columns("FLGDIAACEVGMMOT")
            Me.columnDATTRNLMTCTBACEVGM = Me.Columns("DATTRNLMTCTBACEVGM")
            Me.columnFLGFRDFRMPCO = Me.Columns("FLGFRDFRMPCO")
            Me.columnPERPRVVNDDIA = Me.Columns("PERPRVVNDDIA")
            Me.columnDATREFSGNDIASMN = Me.Columns("DATREFSGNDIASMN")
            Me.columnFLGFRDLEGTRB = Me.Columns("FLGFRDLEGTRB")
            Me.columnFLGFRDNAC = Me.Columns("FLGFRDNAC")
            Me.columnMESREF = Me.Columns("MESREF")
            Me.columnFLGFRDEPD = Me.Columns("FLGFRDEPD")
            Me.columnFLGORDPGTREP = Me.Columns("FLGORDPGTREP")
            Me.columnANOMESREF = Me.Columns("ANOMESREF")
            Me.columnINDFRDFOLPGT = Me.Columns("INDFRDFOLPGT")
        End Sub
        
        Private Sub InitClass()
            Me.columnDATREF = New DataColumn("DATREF", GetType(System.DateTime), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnDATREF)
            Me.columnFLGFATDIA = New DataColumn("FLGFATDIA", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnFLGFATDIA)
            Me.columnNUMDIASMN = New DataColumn("NUMDIASMN", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnNUMDIASMN)
            Me.columnFLGFRDBCO = New DataColumn("FLGFRDBCO", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnFLGFRDBCO)
            Me.columnNUMSMNMES = New DataColumn("NUMSMNMES", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnNUMSMNMES)
            Me.columnFLGDIAACEVGMMOT = New DataColumn("FLGDIAACEVGMMOT", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnFLGDIAACEVGMMOT)
            Me.columnDATTRNLMTCTBACEVGM = New DataColumn("DATTRNLMTCTBACEVGM", GetType(System.DateTime), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnDATTRNLMTCTBACEVGM)
            Me.columnFLGFRDFRMPCO = New DataColumn("FLGFRDFRMPCO", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnFLGFRDFRMPCO)
            Me.columnPERPRVVNDDIA = New DataColumn("PERPRVVNDDIA", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnPERPRVVNDDIA)
            Me.columnDATREFSGNDIASMN = New DataColumn("DATREFSGNDIASMN", GetType(System.DateTime), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnDATREFSGNDIASMN)
            Me.columnFLGFRDLEGTRB = New DataColumn("FLGFRDLEGTRB", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnFLGFRDLEGTRB)
            Me.columnFLGFRDNAC = New DataColumn("FLGFRDNAC", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnFLGFRDNAC)
            Me.columnMESREF = New DataColumn("MESREF", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnMESREF)
            Me.columnFLGFRDEPD = New DataColumn("FLGFRDEPD", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnFLGFRDEPD)
            Me.columnFLGORDPGTREP = New DataColumn("FLGORDPGTREP", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnFLGORDPGTREP)
            Me.columnANOMESREF = New DataColumn("ANOMESREF", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnANOMESREF)
            Me.columnINDFRDFOLPGT = New DataColumn("INDFRDFOLPGT", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnINDFRDFOLPGT)
            Me.Constraints.Add(New UniqueConstraint("DatasetCalendarioAnualKey1", New DataColumn() {Me.columnDATREF}, true))
            Me.columnDATREF.AllowDBNull = false
            Me.columnDATREF.Unique = true
            Me.columnFLGFATDIA.AllowDBNull = false
            Me.columnNUMDIASMN.AllowDBNull = false
            Me.columnFLGFRDBCO.AllowDBNull = false
            Me.columnNUMSMNMES.AllowDBNull = false
            Me.columnFLGDIAACEVGMMOT.AllowDBNull = false
            Me.columnDATTRNLMTCTBACEVGM.AllowDBNull = false
            Me.columnFLGFRDFRMPCO.AllowDBNull = false
            Me.columnPERPRVVNDDIA.AllowDBNull = false
            Me.columnDATREFSGNDIASMN.AllowDBNull = false
            Me.columnFLGFRDLEGTRB.AllowDBNull = false
            Me.columnFLGFRDNAC.AllowDBNull = false
            Me.columnMESREF.AllowDBNull = false
            Me.columnFLGFRDEPD.AllowDBNull = false
            Me.columnFLGORDPGTREP.AllowDBNull = false
            Me.columnANOMESREF.AllowDBNull = false
            Me.columnINDFRDFOLPGT.AllowDBNull = false
        End Sub
        
        Public Function NewT0102321Row() As T0102321Row
            Return CType(Me.NewRow,T0102321Row)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New T0102321Row(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(T0102321Row)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.T0102321RowChangedEvent) Is Nothing) Then
                RaiseEvent T0102321RowChanged(Me, New T0102321RowChangeEvent(CType(e.Row,T0102321Row), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.T0102321RowChangingEvent) Is Nothing) Then
                RaiseEvent T0102321RowChanging(Me, New T0102321RowChangeEvent(CType(e.Row,T0102321Row), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.T0102321RowDeletedEvent) Is Nothing) Then
                RaiseEvent T0102321RowDeleted(Me, New T0102321RowChangeEvent(CType(e.Row,T0102321Row), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.T0102321RowDeletingEvent) Is Nothing) Then
                RaiseEvent T0102321RowDeleting(Me, New T0102321RowChangeEvent(CType(e.Row,T0102321Row), e.Action))
            End If
        End Sub
        
        Public Sub RemoveT0102321Row(ByVal row As T0102321Row)
            Me.Rows.Remove(row)
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class T0102321Row
        Inherits DataRow
        
        Private tableT0102321 As T0102321DataTable
        
        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tableT0102321 = CType(Me.Table,T0102321DataTable)
        End Sub
        
        Public Property DATREF As Date
            Get
                Return CType(Me(Me.tableT0102321.DATREFColumn),Date)
            End Get
            Set
                Me(Me.tableT0102321.DATREFColumn) = value
            End Set
        End Property
        
        Public Property FLGFATDIA As String
            Get
                Return CType(Me(Me.tableT0102321.FLGFATDIAColumn),String)
            End Get
            Set
                Me(Me.tableT0102321.FLGFATDIAColumn) = value
            End Set
        End Property
        
        Public Property NUMDIASMN As Decimal
            Get
                Return CType(Me(Me.tableT0102321.NUMDIASMNColumn),Decimal)
            End Get
            Set
                Me(Me.tableT0102321.NUMDIASMNColumn) = value
            End Set
        End Property
        
        Public Property FLGFRDBCO As String
            Get
                Return CType(Me(Me.tableT0102321.FLGFRDBCOColumn),String)
            End Get
            Set
                Me(Me.tableT0102321.FLGFRDBCOColumn) = value
            End Set
        End Property
        
        Public Property NUMSMNMES As Decimal
            Get
                Return CType(Me(Me.tableT0102321.NUMSMNMESColumn),Decimal)
            End Get
            Set
                Me(Me.tableT0102321.NUMSMNMESColumn) = value
            End Set
        End Property
        
        Public Property FLGDIAACEVGMMOT As String
            Get
                Return CType(Me(Me.tableT0102321.FLGDIAACEVGMMOTColumn),String)
            End Get
            Set
                Me(Me.tableT0102321.FLGDIAACEVGMMOTColumn) = value
            End Set
        End Property
        
        Public Property DATTRNLMTCTBACEVGM As Date
            Get
                Return CType(Me(Me.tableT0102321.DATTRNLMTCTBACEVGMColumn),Date)
            End Get
            Set
                Me(Me.tableT0102321.DATTRNLMTCTBACEVGMColumn) = value
            End Set
        End Property
        
        Public Property FLGFRDFRMPCO As String
            Get
                Return CType(Me(Me.tableT0102321.FLGFRDFRMPCOColumn),String)
            End Get
            Set
                Me(Me.tableT0102321.FLGFRDFRMPCOColumn) = value
            End Set
        End Property
        
        Public Property PERPRVVNDDIA As Decimal
            Get
                Return CType(Me(Me.tableT0102321.PERPRVVNDDIAColumn),Decimal)
            End Get
            Set
                Me(Me.tableT0102321.PERPRVVNDDIAColumn) = value
            End Set
        End Property
        
        Public Property DATREFSGNDIASMN As Date
            Get
                Return CType(Me(Me.tableT0102321.DATREFSGNDIASMNColumn),Date)
            End Get
            Set
                Me(Me.tableT0102321.DATREFSGNDIASMNColumn) = value
            End Set
        End Property
        
        Public Property FLGFRDLEGTRB As String
            Get
                Return CType(Me(Me.tableT0102321.FLGFRDLEGTRBColumn),String)
            End Get
            Set
                Me(Me.tableT0102321.FLGFRDLEGTRBColumn) = value
            End Set
        End Property
        
        Public Property FLGFRDNAC As String
            Get
                Return CType(Me(Me.tableT0102321.FLGFRDNACColumn),String)
            End Get
            Set
                Me(Me.tableT0102321.FLGFRDNACColumn) = value
            End Set
        End Property
        
        Public Property MESREF As Decimal
            Get
                Return CType(Me(Me.tableT0102321.MESREFColumn),Decimal)
            End Get
            Set
                Me(Me.tableT0102321.MESREFColumn) = value
            End Set
        End Property
        
        Public Property FLGFRDEPD As String
            Get
                Return CType(Me(Me.tableT0102321.FLGFRDEPDColumn),String)
            End Get
            Set
                Me(Me.tableT0102321.FLGFRDEPDColumn) = value
            End Set
        End Property
        
        Public Property FLGORDPGTREP As String
            Get
                Return CType(Me(Me.tableT0102321.FLGORDPGTREPColumn),String)
            End Get
            Set
                Me(Me.tableT0102321.FLGORDPGTREPColumn) = value
            End Set
        End Property
        
        Public Property ANOMESREF As Decimal
            Get
                Return CType(Me(Me.tableT0102321.ANOMESREFColumn),Decimal)
            End Get
            Set
                Me(Me.tableT0102321.ANOMESREFColumn) = value
            End Set
        End Property
        
        Public Property INDFRDFOLPGT As Decimal
            Get
                Return CType(Me(Me.tableT0102321.INDFRDFOLPGTColumn),Decimal)
            End Get
            Set
                Me(Me.tableT0102321.INDFRDFOLPGTColumn) = value
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class T0102321RowChangeEvent
        Inherits EventArgs
        
        Private eventRow As T0102321Row
        
        Private eventAction As DataRowAction
        
        Public Sub New(ByVal row As T0102321Row, ByVal action As DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row As T0102321Row
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
